// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package store

import (
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type Membership struct {
	OrgID          uuid.UUID
	ID             uuid.UUID
	UserID         uuid.UUID
	Kind           string
	Role           string
	Status         string
	Source         string
	IdpSubject     pgtype.Text
	JobTitle       pgtype.Text
	Department     pgtype.Text
	Division       pgtype.Text
	Manager        pgtype.Text
	EmployeeType   pgtype.Text
	Location       pgtype.Text
	Country        pgtype.Text
	City           pgtype.Text
	Attributes     []byte
	LastActiveAt   pgtype.Timestamptz
	DeactivatedAt  pgtype.Timestamptz
	ExternalID     pgtype.Text
	Scim           []byte
	ScimActive     pgtype.Bool
	AnonymisedAt   pgtype.Timestamptz
	CreatedBy      string
	CreatedAt      time.Time
	LastModifiedBy string
	LastModifiedAt time.Time
}

type ScimGroup struct {
	OrgID          uuid.UUID
	ID             uuid.UUID
	ExternalID     pgtype.Text
	DisplayName    string
	CreatedBy      string
	CreatedAt      time.Time
	LastModifiedBy string
	LastModifiedAt time.Time
}

type ScimGroupMember struct {
	OrgID          uuid.UUID
	GroupID        uuid.UUID
	MembershipID   uuid.UUID
	CreatedBy      string
	CreatedAt      time.Time
	LastModifiedBy string
	LastModifiedAt time.Time
}

type ScimLog struct {
	OrgID          uuid.UUID
	ID             uuid.UUID
	Operation      string
	MembershipID   pgtype.UUID
	GroupID        pgtype.UUID
	Outcome        string
	Error          pgtype.Text
	Details        []byte
	CreatedBy      string
	CreatedAt      time.Time
	LastModifiedBy string
	LastModifiedAt time.Time
}

type ScimState struct {
	OrgID          uuid.UUID
	LastCallAt     pgtype.Timestamptz
	LastOperation  pgtype.Text
	HaltedAt       pgtype.Timestamptz
	HaltedReason   pgtype.Text
	HaltedChanges  []byte
	CreatedBy      string
	CreatedAt      time.Time
	LastModifiedBy string
	LastModifiedAt time.Time
}

type ScimToken struct {
	OrgID          uuid.UUID
	ID             uuid.UUID
	Prefix         string
	Hash           []byte
	ExpiresAt      pgtype.Timestamptz
	RevokedAt      pgtype.Timestamptz
	LastUsedAt     pgtype.Timestamptz
	CreatedBy      string
	CreatedAt      time.Time
	LastModifiedBy string
	LastModifiedAt time.Time
}

// global: one identity across every org; memberships are per org
type User struct {
	ID                  uuid.UUID
	Email               string
	Name                string
	DeletedAt           pgtype.Timestamptz
	DisplayName         pgtype.Text
	TimeZone            pgtype.Text
	WorkingHours        []byte
	PhotoKey            pgtype.Text
	Theme               string
	Language            pgtype.Text
	DeletionRequestedAt pgtype.Timestamptz
	DeletionAfter       pgtype.Timestamptz
	CreatedBy           string
	CreatedAt           time.Time
	LastModifiedBy      string
	LastModifiedAt      time.Time
}
