// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: users.sql

package store

import (
	"context"

	"github.com/google/uuid"
)

const getUser = `-- name: GetUser :one
SELECT id, email, name, deleted_at, display_name, time_zone, working_hours, photo_key, theme, language, deletion_requested_at, deletion_after, created_by, created_at, last_modified_by, last_modified_at FROM users WHERE id = $1 AND deleted_at IS NULL
`

// global: a user is one identity across every org.
func (q *Queries) GetUser(ctx context.Context, id uuid.UUID) (User, error) {
	row := q.db.QueryRow(ctx, getUser, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Name,
		&i.DeletedAt,
		&i.DisplayName,
		&i.TimeZone,
		&i.WorkingHours,
		&i.PhotoKey,
		&i.Theme,
		&i.Language,
		&i.DeletionRequestedAt,
		&i.DeletionAfter,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.LastModifiedBy,
		&i.LastModifiedAt,
	)
	return i, err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, email, name, deleted_at, display_name, time_zone, working_hours, photo_key, theme, language, deletion_requested_at, deletion_after, created_by, created_at, last_modified_by, last_modified_at FROM users WHERE email = $1 AND deleted_at IS NULL
`

// global: email is the platform-wide identity.
func (q *Queries) GetUserByEmail(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Name,
		&i.DeletedAt,
		&i.DisplayName,
		&i.TimeZone,
		&i.WorkingHours,
		&i.PhotoKey,
		&i.Theme,
		&i.Language,
		&i.DeletionRequestedAt,
		&i.DeletionAfter,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.LastModifiedBy,
		&i.LastModifiedAt,
	)
	return i, err
}

const insertUser = `-- name: InsertUser :one
INSERT INTO users (id, email, name) VALUES ($1, $2, $3)
ON CONFLICT (email) WHERE deleted_at IS NULL DO NOTHING
RETURNING id, email, name, deleted_at, display_name, time_zone, working_hours, photo_key, theme, language, deletion_requested_at, deletion_after, created_by, created_at, last_modified_by, last_modified_at
`

type InsertUserParams struct {
	ID    uuid.UUID
	Email string
	Name  string
}

// global: created on first sign-in or first invite, before any org is
// known. A second org inviting the same email finds this row instead.
func (q *Queries) InsertUser(ctx context.Context, arg InsertUserParams) (User, error) {
	row := q.db.QueryRow(ctx, insertUser, arg.ID, arg.Email, arg.Name)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Name,
		&i.DeletedAt,
		&i.DisplayName,
		&i.TimeZone,
		&i.WorkingHours,
		&i.PhotoKey,
		&i.Theme,
		&i.Language,
		&i.DeletionRequestedAt,
		&i.DeletionAfter,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.LastModifiedBy,
		&i.LastModifiedAt,
	)
	return i, err
}

const updateUserName = `-- name: UpdateUserName :one
UPDATE users SET name = $1 WHERE id = $2 AND deleted_at IS NULL
RETURNING id, email, name, deleted_at, display_name, time_zone, working_hours, photo_key, theme, language, deletion_requested_at, deletion_after, created_by, created_at, last_modified_by, last_modified_at
`

type UpdateUserNameParams struct {
	Name string
	ID   uuid.UUID
}

// global: the name is the person's, not an org's.
func (q *Queries) UpdateUserName(ctx context.Context, arg UpdateUserNameParams) (User, error) {
	row := q.db.QueryRow(ctx, updateUserName, arg.Name, arg.ID)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Name,
		&i.DeletedAt,
		&i.DisplayName,
		&i.TimeZone,
		&i.WorkingHours,
		&i.PhotoKey,
		&i.Theme,
		&i.Language,
		&i.DeletionRequestedAt,
		&i.DeletionAfter,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.LastModifiedBy,
		&i.LastModifiedAt,
	)
	return i, err
}
