//go:build go1.22

// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.8.0 DO NOT EDIT.
package api

import (
	"bytes"
	"context"
	"encoding/json"
	"errors"
	"fmt"
	"net/http"
	"time"

	"github.com/oapi-codegen/runtime"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

// Defines values for BandPreviewApplies.
const (
	Now       BandPreviewApplies = "now"
	PeriodEnd BandPreviewApplies = "period_end"
)

// Valid indicates whether the value is a known member of the BandPreviewApplies enum.
func (e BandPreviewApplies) Valid() bool {
	switch e {
	case Now:
		return true
	case PeriodEnd:
		return true
	default:
		return false
	}
}

// Defines values for BillingState.
const (
	Active    BillingState = "active"
	Cancelled BillingState = "cancelled"
	Free      BillingState = "free"
	Invoiced  BillingState = "invoiced"
	PastDue   BillingState = "past_due"
	Trialing  BillingState = "trialing"
)

// Valid indicates whether the value is a known member of the BillingState enum.
func (e BillingState) Valid() bool {
	switch e {
	case Active:
		return true
	case Cancelled:
		return true
	case Free:
		return true
	case Invoiced:
		return true
	case PastDue:
		return true
	case Trialing:
		return true
	default:
		return false
	}
}

// Band A plan band, one of the bands the deployment registers.
type Band = string

// BandPreview defines model for BandPreview.
type BandPreview struct {
	// AmountToday Charged now, with proration; 0 for a change at the period's end.
	AmountToday int64              `json:"amount_today"`
	Applies     BandPreviewApplies `json:"applies"`

	// Band A plan band, one of the bands the deployment registers.
	Band     Band   `json:"band"`
	Currency string `json:"currency"`
}

// BandPreviewApplies defines model for BandPreview.Applies.
type BandPreviewApplies string

// Billing defines model for Billing.
type Billing struct {
	ActiveMembers int  `json:"active_members"`
	AutoUpgrade   bool `json:"auto_upgrade"`

	// Band A plan band, one of the bands the deployment registers.
	Band Band `json:"band"`

	// Bands Every band the billing page may offer, lowest first: the lowest
	// band, which has no price (a move to it is a downgrade at the
	// period's end, or the end of a trial), then every self-serve band.
	// Contractual bands are never listed. Labels and what each allows are
	// at the organization service's GET /v1/plans.
	Bands []Band `json:"bands"`

	// CanManageAutoUpgrade Whether the caller is an Owner, who alone may change it.
	CanManageAutoUpgrade bool `json:"can_manage_auto_upgrade"`
	Card                 *struct {
		Brand string `json:"brand"`
		Last4 string `json:"last4"`
	} `json:"card,omitempty"`

	// GraceDaysLeft While past due, days left before the org drops to free.
	GraceDaysLeft *int `json:"grace_days_left,omitempty"`

	// Invoiced Enterprise, invoiced by contract; no controls.
	Invoiced bool `json:"invoiced"`

	// NextBand A plan band, one of the bands the deployment registers.
	NextBand *Band `json:"next_band,omitempty"`

	// PendingBand A plan band, one of the bands the deployment registers.
	PendingBand *Band      `json:"pending_band,omitempty"`
	PeriodEnd   *time.Time `json:"period_end,omitempty"`

	// Prices The price of each band the payment provider sells, by band. A band in bands with no entry here costs nothing.
	Prices         map[string]Price `json:"prices"`
	State          BillingState     `json:"state"`
	TrialAvailable bool             `json:"trial_available"`
	TrialEndsAt    *time.Time       `json:"trial_ends_at,omitempty"`

	// UsersCap 0 means no cap.
	UsersCap int `json:"users_cap"`
}

// BillingState defines model for Billing.State.
type BillingState string

// DataPart defines model for DataPart.
type DataPart struct {
	Data  map[string]interface{} `json:"data"`
	Files []struct {
		Key  string `json:"key"`
		Name string `json:"name"`
	} `json:"files"`
	Service string `json:"service"`
}

// DataPurged defines model for DataPurged.
type DataPurged struct {
	Remaining int `json:"remaining"`
}

// Error defines model for Error.
type Error struct {
	Code    string             `json:"code"`
	Fields  *map[string]string `json:"fields,omitempty"`
	Message string             `json:"message"`
}

// Invoice defines model for Invoice.
type Invoice struct {
	Amount      int64      `json:"amount"`
	Created     time.Time  `json:"created"`
	Currency    string     `json:"currency"`
	Id          string     `json:"id"`
	NextAttempt *time.Time `json:"next_attempt,omitempty"`
	Number      *string    `json:"number,omitempty"`
	PayUrl      *string    `json:"pay_url,omitempty"`
	Pdf         *string    `json:"pdf,omitempty"`
	Status      string     `json:"status"`
}

// Price defines model for Price.
type Price struct {
	// Amount Minor units.
	Amount   int64  `json:"amount"`
	Currency string `json:"currency"`
	Interval string `json:"interval"`
}

// OrgId defines model for OrgId.
type OrgId = openapi_types.UUID

// MakeRoomJSONBody defines parameters for MakeRoom.
type MakeRoomJSONBody struct {
	Members int `json:"members"`
}

// MembersChangedJSONBody defines parameters for MembersChanged.
type MembersChangedJSONBody struct {
	Members int `json:"members"`
}

// ExportUserDataParams defines parameters for ExportUserData.
type ExportUserDataParams struct {
	// Membership Each of the person's memberships, as org_id:membership_id.
	Membership *[]string `form:"membership,omitempty" json:"membership,omitempty"`
}

// SetAutoUpgradeJSONBody defines parameters for SetAutoUpgrade.
type SetAutoUpgradeJSONBody struct {
	On bool `json:"on"`
}

// ChangeBandJSONBody defines parameters for ChangeBand.
type ChangeBandJSONBody struct {
	// Band A plan band, one of the bands the deployment registers.
	Band Band `json:"band"`
}

// PreviewBandParams defines parameters for PreviewBand.
type PreviewBandParams struct {
	Band Band `form:"band" json:"band"`
}

// MakeRoomJSONRequestBody defines body for MakeRoom for application/json ContentType.
type MakeRoomJSONRequestBody MakeRoomJSONBody

// MembersChangedJSONRequestBody defines body for MembersChanged for application/json ContentType.
type MembersChangedJSONRequestBody MembersChangedJSONBody

// SetAutoUpgradeJSONRequestBody defines body for SetAutoUpgrade for application/json ContentType.
type SetAutoUpgradeJSONRequestBody SetAutoUpgradeJSONBody

// ChangeBandJSONRequestBody defines body for ChangeBand for application/json ContentType.
type ChangeBandJSONRequestBody ChangeBandJSONBody

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// MakeRoom Room for this many active members, by an automatic upgrade if it is on (the user service only)
	// (POST /v1/internal/organizations/{org_id}/capacity)
	MakeRoom(w http.ResponseWriter, r *http.Request, orgId OrgId)
	// CloseAccount The org is closing; cancel its subscription now (the organization service only)
	// (POST /v1/internal/organizations/{org_id}/close)
	CloseAccount(w http.ResponseWriter, r *http.Request, orgId OrgId)
	// PurgeOrgData Delete everything this service keeps for an org, and count what is left (the organization service only)
	// (DELETE /v1/internal/organizations/{org_id}/data)
	PurgeOrgData(w http.ResponseWriter, r *http.Request, orgId OrgId)
	// ExportOrgData Everything this service keeps for an org, for its export (the organization service only)
	// (GET /v1/internal/organizations/{org_id}/data)
	ExportOrgData(w http.ResponseWriter, r *http.Request, orgId OrgId)
	// MembersChanged The active member count moved (the user service only); billing warns at 80% of the cap
	// (POST /v1/internal/organizations/{org_id}/members-changed)
	MembersChanged(w http.ResponseWriter, r *http.Request, orgId OrgId)
	// ExportUserData What this service keeps about one person, for their own export (the organization service only)
	// (GET /v1/internal/users/{user_id}/data)
	ExportUserData(w http.ResponseWriter, r *http.Request, userId openapi_types.UUID, params ExportUserDataParams)
	// GetBilling What the org is on and paying, for the billing page and its banners
	// (GET /v1/organizations/{org_id}/billing)
	GetBilling(w http.ResponseWriter, r *http.Request, orgId OrgId)
	// SetAutoUpgrade Turn automatic upgrade on or off (Owner only)
	// (PUT /v1/organizations/{org_id}/billing/auto-upgrade)
	SetAutoUpgrade(w http.ResponseWriter, r *http.Request, orgId OrgId)
	// ChangeBand Move to another band; up applies now with proration, down at the period's end
	// (PUT /v1/organizations/{org_id}/billing/band)
	ChangeBand(w http.ResponseWriter, r *http.Request, orgId OrgId)
	// PreviewBand What moving to a band would charge today
	// (GET /v1/organizations/{org_id}/billing/band-preview)
	PreviewBand(w http.ResponseWriter, r *http.Request, orgId OrgId, params PreviewBandParams)
	// ListInvoices The org's invoices from the provider, newest first
	// (GET /v1/organizations/{org_id}/billing/invoices)
	ListInvoices(w http.ResponseWriter, r *http.Request, orgId OrgId)
	// CancelPending Cancel a scheduled downgrade
	// (DELETE /v1/organizations/{org_id}/billing/pending)
	CancelPending(w http.ResponseWriter, r *http.Request, orgId OrgId)
	// StartSetup The provider's hosted form, to add or replace the payment method, address and tax ID
	// (POST /v1/organizations/{org_id}/billing/setup)
	StartSetup(w http.ResponseWriter, r *http.Request, orgId OrgId)
	// StartTrial Start the one team trial, 14 days, on a free org
	// (POST /v1/organizations/{org_id}/billing/trial)
	StartTrial(w http.ResponseWriter, r *http.Request, orgId OrgId)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// MakeRoom operation middleware
func (siw *ServerInterfaceWrapper) MakeRoom(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "org_id" -------------
	var orgId OrgId

	err = runtime.BindStyledParameterWithOptions("simple", "org_id", r.PathValue("org_id"), &orgId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "org_id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.MakeRoom(w, r, orgId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// CloseAccount operation middleware
func (siw *ServerInterfaceWrapper) CloseAccount(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "org_id" -------------
	var orgId OrgId

	err = runtime.BindStyledParameterWithOptions("simple", "org_id", r.PathValue("org_id"), &orgId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "org_id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CloseAccount(w, r, orgId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// PurgeOrgData operation middleware
func (siw *ServerInterfaceWrapper) PurgeOrgData(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "org_id" -------------
	var orgId OrgId

	err = runtime.BindStyledParameterWithOptions("simple", "org_id", r.PathValue("org_id"), &orgId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "org_id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PurgeOrgData(w, r, orgId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ExportOrgData operation middleware
func (siw *ServerInterfaceWrapper) ExportOrgData(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "org_id" -------------
	var orgId OrgId

	err = runtime.BindStyledParameterWithOptions("simple", "org_id", r.PathValue("org_id"), &orgId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "org_id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ExportOrgData(w, r, orgId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// MembersChanged operation middleware
func (siw *ServerInterfaceWrapper) MembersChanged(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "org_id" -------------
	var orgId OrgId

	err = runtime.BindStyledParameterWithOptions("simple", "org_id", r.PathValue("org_id"), &orgId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "org_id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.MembersChanged(w, r, orgId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ExportUserData operation middleware
func (siw *ServerInterfaceWrapper) ExportUserData(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "user_id" -------------
	var userId openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "user_id", r.PathValue("user_id"), &userId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "user_id", Err: err})
		return
	}

	// Parameter object where we will unmarshal all parameters from the context
	var params ExportUserDataParams

	// ------------- Optional query parameter "membership" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "membership", r.URL.Query(), &params.Membership, runtime.BindQueryParameterOptions{Type: "array", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "membership"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "membership", Err: err})
		}
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ExportUserData(w, r, userId, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetBilling operation middleware
func (siw *ServerInterfaceWrapper) GetBilling(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "org_id" -------------
	var orgId OrgId

	err = runtime.BindStyledParameterWithOptions("simple", "org_id", r.PathValue("org_id"), &orgId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "org_id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetBilling(w, r, orgId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// SetAutoUpgrade operation middleware
func (siw *ServerInterfaceWrapper) SetAutoUpgrade(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "org_id" -------------
	var orgId OrgId

	err = runtime.BindStyledParameterWithOptions("simple", "org_id", r.PathValue("org_id"), &orgId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "org_id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.SetAutoUpgrade(w, r, orgId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ChangeBand operation middleware
func (siw *ServerInterfaceWrapper) ChangeBand(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "org_id" -------------
	var orgId OrgId

	err = runtime.BindStyledParameterWithOptions("simple", "org_id", r.PathValue("org_id"), &orgId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "org_id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ChangeBand(w, r, orgId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// PreviewBand operation middleware
func (siw *ServerInterfaceWrapper) PreviewBand(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "org_id" -------------
	var orgId OrgId

	err = runtime.BindStyledParameterWithOptions("simple", "org_id", r.PathValue("org_id"), &orgId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "org_id", Err: err})
		return
	}

	// Parameter object where we will unmarshal all parameters from the context
	var params PreviewBandParams

	// ------------- Required query parameter "band" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, true, "band", r.URL.Query(), &params.Band, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "band"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "band", Err: err})
		}
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PreviewBand(w, r, orgId, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListInvoices operation middleware
func (siw *ServerInterfaceWrapper) ListInvoices(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "org_id" -------------
	var orgId OrgId

	err = runtime.BindStyledParameterWithOptions("simple", "org_id", r.PathValue("org_id"), &orgId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "org_id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListInvoices(w, r, orgId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// CancelPending operation middleware
func (siw *ServerInterfaceWrapper) CancelPending(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "org_id" -------------
	var orgId OrgId

	err = runtime.BindStyledParameterWithOptions("simple", "org_id", r.PathValue("org_id"), &orgId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "org_id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CancelPending(w, r, orgId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// StartSetup operation middleware
func (siw *ServerInterfaceWrapper) StartSetup(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "org_id" -------------
	var orgId OrgId

	err = runtime.BindStyledParameterWithOptions("simple", "org_id", r.PathValue("org_id"), &orgId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "org_id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.StartSetup(w, r, orgId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// StartTrial operation middleware
func (siw *ServerInterfaceWrapper) StartTrial(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "org_id" -------------
	var orgId OrgId

	err = runtime.BindStyledParameterWithOptions("simple", "org_id", r.PathValue("org_id"), &orgId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "org_id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.StartTrial(w, r, orgId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{})
}

// ServeMux is an abstraction of [http.ServeMux].
type ServeMux interface {
	HandleFunc(pattern string, handler func(http.ResponseWriter, *http.Request))
	http.Handler
}

type StdHTTPServerOptions struct {
	BaseURL          string
	BaseRouter       ServeMux
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, m ServeMux) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{
		BaseRouter: m,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, m ServeMux, baseURL string) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{
		BaseURL:    baseURL,
		BaseRouter: m,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options StdHTTPServerOptions) http.Handler {
	m := options.BaseRouter

	if m == nil {
		m = http.NewServeMux()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}

	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/v1/organizations/{org_id}/billing", wrapper.GetBilling)
	m.HandleFunc(http.MethodPost+" "+options.BaseURL+"/v1/organizations/{org_id}/billing/setup", wrapper.StartSetup)
	m.HandleFunc(http.MethodPut+" "+options.BaseURL+"/v1/organizations/{org_id}/billing/band", wrapper.ChangeBand)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/v1/organizations/{org_id}/billing/band-preview", wrapper.PreviewBand)
	m.HandleFunc(http.MethodDelete+" "+options.BaseURL+"/v1/organizations/{org_id}/billing/pending", wrapper.CancelPending)
	m.HandleFunc(http.MethodPost+" "+options.BaseURL+"/v1/organizations/{org_id}/billing/trial", wrapper.StartTrial)
	m.HandleFunc(http.MethodPut+" "+options.BaseURL+"/v1/organizations/{org_id}/billing/auto-upgrade", wrapper.SetAutoUpgrade)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/v1/organizations/{org_id}/billing/invoices", wrapper.ListInvoices)
	m.HandleFunc(http.MethodPost+" "+options.BaseURL+"/v1/internal/organizations/{org_id}/capacity", wrapper.MakeRoom)
	m.HandleFunc(http.MethodPost+" "+options.BaseURL+"/v1/internal/organizations/{org_id}/members-changed", wrapper.MembersChanged)
	m.HandleFunc(http.MethodDelete+" "+options.BaseURL+"/v1/internal/organizations/{org_id}/data", wrapper.PurgeOrgData)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/v1/internal/organizations/{org_id}/data", wrapper.ExportOrgData)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/v1/internal/users/{user_id}/data", wrapper.ExportUserData)
	m.HandleFunc(http.MethodPost+" "+options.BaseURL+"/v1/internal/organizations/{org_id}/close", wrapper.CloseAccount)

	return m
}

type ErrorJSONResponse Error

type MakeRoomRequestObject struct {
	OrgId OrgId `json:"org_id"`
	Body  *MakeRoomJSONRequestBody
}

type MakeRoomResponseObject interface {
	VisitMakeRoomResponse(w http.ResponseWriter) error
}

type MakeRoom200JSONResponse struct {
	// Band A plan band, one of the bands the deployment registers.
	Band     Band `json:"band"`
	Upgraded bool `json:"upgraded"`
}

func (response MakeRoom200JSONResponse) VisitMakeRoomResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type MakeRoom403JSONResponse struct{ ErrorJSONResponse }

func (response MakeRoom403JSONResponse) VisitMakeRoomResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(403)
	_, err := buf.WriteTo(w)
	return err
}

type MakeRoom409JSONResponse Error

func (response MakeRoom409JSONResponse) VisitMakeRoomResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(409)
	_, err := buf.WriteTo(w)
	return err
}

type MakeRoomdefaultJSONResponse struct {
	Body       Error
	StatusCode int
}

func (response MakeRoomdefaultJSONResponse) VisitMakeRoomResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(response.StatusCode)
	_, err := buf.WriteTo(w)
	return err
}

type CloseAccountRequestObject struct {
	OrgId OrgId `json:"org_id"`
}

type CloseAccountResponseObject interface {
	VisitCloseAccountResponse(w http.ResponseWriter) error
}

type CloseAccount204Response struct {
}

func (response CloseAccount204Response) VisitCloseAccountResponse(w http.ResponseWriter) error {
	w.WriteHeader(204)
	return nil
}

type CloseAccount403JSONResponse struct{ ErrorJSONResponse }

func (response CloseAccount403JSONResponse) VisitCloseAccountResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(403)
	_, err := buf.WriteTo(w)
	return err
}

type CloseAccountdefaultJSONResponse struct {
	Body       Error
	StatusCode int
}

func (response CloseAccountdefaultJSONResponse) VisitCloseAccountResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(response.StatusCode)
	_, err := buf.WriteTo(w)
	return err
}

type PurgeOrgDataRequestObject struct {
	OrgId OrgId `json:"org_id"`
}

type PurgeOrgDataResponseObject interface {
	VisitPurgeOrgDataResponse(w http.ResponseWriter) error
}

type PurgeOrgData200JSONResponse DataPurged

func (response PurgeOrgData200JSONResponse) VisitPurgeOrgDataResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type PurgeOrgData403JSONResponse struct{ ErrorJSONResponse }

func (response PurgeOrgData403JSONResponse) VisitPurgeOrgDataResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(403)
	_, err := buf.WriteTo(w)
	return err
}

type PurgeOrgDatadefaultJSONResponse struct {
	Body       Error
	StatusCode int
}

func (response PurgeOrgDatadefaultJSONResponse) VisitPurgeOrgDataResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(response.StatusCode)
	_, err := buf.WriteTo(w)
	return err
}

type ExportOrgDataRequestObject struct {
	OrgId OrgId `json:"org_id"`
}

type ExportOrgDataResponseObject interface {
	VisitExportOrgDataResponse(w http.ResponseWriter) error
}

type ExportOrgData200JSONResponse DataPart

func (response ExportOrgData200JSONResponse) VisitExportOrgDataResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type ExportOrgData403JSONResponse struct{ ErrorJSONResponse }

func (response ExportOrgData403JSONResponse) VisitExportOrgDataResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(403)
	_, err := buf.WriteTo(w)
	return err
}

type ExportOrgDatadefaultJSONResponse struct {
	Body       Error
	StatusCode int
}

func (response ExportOrgDatadefaultJSONResponse) VisitExportOrgDataResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(response.StatusCode)
	_, err := buf.WriteTo(w)
	return err
}

type MembersChangedRequestObject struct {
	OrgId OrgId `json:"org_id"`
	Body  *MembersChangedJSONRequestBody
}

type MembersChangedResponseObject interface {
	VisitMembersChangedResponse(w http.ResponseWriter) error
}

type MembersChanged204Response struct {
}

func (response MembersChanged204Response) VisitMembersChangedResponse(w http.ResponseWriter) error {
	w.WriteHeader(204)
	return nil
}

type MembersChanged403JSONResponse struct{ ErrorJSONResponse }

func (response MembersChanged403JSONResponse) VisitMembersChangedResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(403)
	_, err := buf.WriteTo(w)
	return err
}

type MembersChangeddefaultJSONResponse struct {
	Body       Error
	StatusCode int
}

func (response MembersChangeddefaultJSONResponse) VisitMembersChangedResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(response.StatusCode)
	_, err := buf.WriteTo(w)
	return err
}

type ExportUserDataRequestObject struct {
	UserId openapi_types.UUID `json:"user_id"`
	Params ExportUserDataParams
}

type ExportUserDataResponseObject interface {
	VisitExportUserDataResponse(w http.ResponseWriter) error
}

type ExportUserData200JSONResponse DataPart

func (response ExportUserData200JSONResponse) VisitExportUserDataResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type ExportUserData400JSONResponse struct{ ErrorJSONResponse }

func (response ExportUserData400JSONResponse) VisitExportUserDataResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)
	_, err := buf.WriteTo(w)
	return err
}

type ExportUserData403JSONResponse Error

func (response ExportUserData403JSONResponse) VisitExportUserDataResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(403)
	_, err := buf.WriteTo(w)
	return err
}

type ExportUserDatadefaultJSONResponse struct {
	Body       Error
	StatusCode int
}

func (response ExportUserDatadefaultJSONResponse) VisitExportUserDataResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(response.StatusCode)
	_, err := buf.WriteTo(w)
	return err
}

type GetBillingRequestObject struct {
	OrgId OrgId `json:"org_id"`
}

type GetBillingResponseObject interface {
	VisitGetBillingResponse(w http.ResponseWriter) error
}

type GetBilling200JSONResponse Billing

func (response GetBilling200JSONResponse) VisitGetBillingResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type GetBilling403JSONResponse struct{ ErrorJSONResponse }

func (response GetBilling403JSONResponse) VisitGetBillingResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(403)
	_, err := buf.WriteTo(w)
	return err
}

type GetBillingdefaultJSONResponse struct {
	Body       Error
	StatusCode int
}

func (response GetBillingdefaultJSONResponse) VisitGetBillingResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(response.StatusCode)
	_, err := buf.WriteTo(w)
	return err
}

type SetAutoUpgradeRequestObject struct {
	OrgId OrgId `json:"org_id"`
	Body  *SetAutoUpgradeJSONRequestBody
}

type SetAutoUpgradeResponseObject interface {
	VisitSetAutoUpgradeResponse(w http.ResponseWriter) error
}

type SetAutoUpgrade200JSONResponse Billing

func (response SetAutoUpgrade200JSONResponse) VisitSetAutoUpgradeResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type SetAutoUpgrade403JSONResponse struct{ ErrorJSONResponse }

func (response SetAutoUpgrade403JSONResponse) VisitSetAutoUpgradeResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(403)
	_, err := buf.WriteTo(w)
	return err
}

type SetAutoUpgradedefaultJSONResponse struct {
	Body       Error
	StatusCode int
}

func (response SetAutoUpgradedefaultJSONResponse) VisitSetAutoUpgradeResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(response.StatusCode)
	_, err := buf.WriteTo(w)
	return err
}

type ChangeBandRequestObject struct {
	OrgId OrgId `json:"org_id"`
	Body  *ChangeBandJSONRequestBody
}

type ChangeBandResponseObject interface {
	VisitChangeBandResponse(w http.ResponseWriter) error
}

type ChangeBand200JSONResponse Billing

func (response ChangeBand200JSONResponse) VisitChangeBandResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type ChangeBand400JSONResponse struct{ ErrorJSONResponse }

func (response ChangeBand400JSONResponse) VisitChangeBandResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)
	_, err := buf.WriteTo(w)
	return err
}

type ChangeBand403JSONResponse Error

func (response ChangeBand403JSONResponse) VisitChangeBandResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(403)
	_, err := buf.WriteTo(w)
	return err
}

type ChangeBand409JSONResponse Error

func (response ChangeBand409JSONResponse) VisitChangeBandResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(409)
	_, err := buf.WriteTo(w)
	return err
}

type ChangeBanddefaultJSONResponse struct {
	Body       Error
	StatusCode int
}

func (response ChangeBanddefaultJSONResponse) VisitChangeBandResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(response.StatusCode)
	_, err := buf.WriteTo(w)
	return err
}

type PreviewBandRequestObject struct {
	OrgId  OrgId `json:"org_id"`
	Params PreviewBandParams
}

type PreviewBandResponseObject interface {
	VisitPreviewBandResponse(w http.ResponseWriter) error
}

type PreviewBand200JSONResponse BandPreview

func (response PreviewBand200JSONResponse) VisitPreviewBandResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type PreviewBand400JSONResponse struct{ ErrorJSONResponse }

func (response PreviewBand400JSONResponse) VisitPreviewBandResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)
	_, err := buf.WriteTo(w)
	return err
}

type PreviewBand403JSONResponse Error

func (response PreviewBand403JSONResponse) VisitPreviewBandResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(403)
	_, err := buf.WriteTo(w)
	return err
}

type PreviewBanddefaultJSONResponse struct {
	Body       Error
	StatusCode int
}

func (response PreviewBanddefaultJSONResponse) VisitPreviewBandResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(response.StatusCode)
	_, err := buf.WriteTo(w)
	return err
}

type ListInvoicesRequestObject struct {
	OrgId OrgId `json:"org_id"`
}

type ListInvoicesResponseObject interface {
	VisitListInvoicesResponse(w http.ResponseWriter) error
}

type ListInvoices200JSONResponse struct {
	Invoices []Invoice `json:"invoices"`
}

func (response ListInvoices200JSONResponse) VisitListInvoicesResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type ListInvoices403JSONResponse struct{ ErrorJSONResponse }

func (response ListInvoices403JSONResponse) VisitListInvoicesResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(403)
	_, err := buf.WriteTo(w)
	return err
}

type ListInvoicesdefaultJSONResponse struct {
	Body       Error
	StatusCode int
}

func (response ListInvoicesdefaultJSONResponse) VisitListInvoicesResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(response.StatusCode)
	_, err := buf.WriteTo(w)
	return err
}

type CancelPendingRequestObject struct {
	OrgId OrgId `json:"org_id"`
}

type CancelPendingResponseObject interface {
	VisitCancelPendingResponse(w http.ResponseWriter) error
}

type CancelPending200JSONResponse Billing

func (response CancelPending200JSONResponse) VisitCancelPendingResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type CancelPending403JSONResponse struct{ ErrorJSONResponse }

func (response CancelPending403JSONResponse) VisitCancelPendingResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(403)
	_, err := buf.WriteTo(w)
	return err
}

type CancelPendingdefaultJSONResponse struct {
	Body       Error
	StatusCode int
}

func (response CancelPendingdefaultJSONResponse) VisitCancelPendingResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(response.StatusCode)
	_, err := buf.WriteTo(w)
	return err
}

type StartSetupRequestObject struct {
	OrgId OrgId `json:"org_id"`
}

type StartSetupResponseObject interface {
	VisitStartSetupResponse(w http.ResponseWriter) error
}

type StartSetup200JSONResponse struct {
	Url string `json:"url"`
}

func (response StartSetup200JSONResponse) VisitStartSetupResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type StartSetup403JSONResponse struct{ ErrorJSONResponse }

func (response StartSetup403JSONResponse) VisitStartSetupResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(403)
	_, err := buf.WriteTo(w)
	return err
}

type StartSetupdefaultJSONResponse struct {
	Body       Error
	StatusCode int
}

func (response StartSetupdefaultJSONResponse) VisitStartSetupResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(response.StatusCode)
	_, err := buf.WriteTo(w)
	return err
}

type StartTrialRequestObject struct {
	OrgId OrgId `json:"org_id"`
}

type StartTrialResponseObject interface {
	VisitStartTrialResponse(w http.ResponseWriter) error
}

type StartTrial200JSONResponse Billing

func (response StartTrial200JSONResponse) VisitStartTrialResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type StartTrial403JSONResponse struct{ ErrorJSONResponse }

func (response StartTrial403JSONResponse) VisitStartTrialResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(403)
	_, err := buf.WriteTo(w)
	return err
}

type StartTrial409JSONResponse Error

func (response StartTrial409JSONResponse) VisitStartTrialResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(409)
	_, err := buf.WriteTo(w)
	return err
}

type StartTrialdefaultJSONResponse struct {
	Body       Error
	StatusCode int
}

func (response StartTrialdefaultJSONResponse) VisitStartTrialResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(response.StatusCode)
	_, err := buf.WriteTo(w)
	return err
}

// StrictServerInterface represents all server handlers.
type StrictServerInterface interface {
	// MakeRoom Room for this many active members, by an automatic upgrade if it is on (the user service only)
	// (POST /v1/internal/organizations/{org_id}/capacity)
	MakeRoom(ctx context.Context, request MakeRoomRequestObject) (MakeRoomResponseObject, error)
	// CloseAccount The org is closing; cancel its subscription now (the organization service only)
	// (POST /v1/internal/organizations/{org_id}/close)
	CloseAccount(ctx context.Context, request CloseAccountRequestObject) (CloseAccountResponseObject, error)
	// PurgeOrgData Delete everything this service keeps for an org, and count what is left (the organization service only)
	// (DELETE /v1/internal/organizations/{org_id}/data)
	PurgeOrgData(ctx context.Context, request PurgeOrgDataRequestObject) (PurgeOrgDataResponseObject, error)
	// ExportOrgData Everything this service keeps for an org, for its export (the organization service only)
	// (GET /v1/internal/organizations/{org_id}/data)
	ExportOrgData(ctx context.Context, request ExportOrgDataRequestObject) (ExportOrgDataResponseObject, error)
	// MembersChanged The active member count moved (the user service only); billing warns at 80% of the cap
	// (POST /v1/internal/organizations/{org_id}/members-changed)
	MembersChanged(ctx context.Context, request MembersChangedRequestObject) (MembersChangedResponseObject, error)
	// ExportUserData What this service keeps about one person, for their own export (the organization service only)
	// (GET /v1/internal/users/{user_id}/data)
	ExportUserData(ctx context.Context, request ExportUserDataRequestObject) (ExportUserDataResponseObject, error)
	// GetBilling What the org is on and paying, for the billing page and its banners
	// (GET /v1/organizations/{org_id}/billing)
	GetBilling(ctx context.Context, request GetBillingRequestObject) (GetBillingResponseObject, error)
	// SetAutoUpgrade Turn automatic upgrade on or off (Owner only)
	// (PUT /v1/organizations/{org_id}/billing/auto-upgrade)
	SetAutoUpgrade(ctx context.Context, request SetAutoUpgradeRequestObject) (SetAutoUpgradeResponseObject, error)
	// ChangeBand Move to another band; up applies now with proration, down at the period's end
	// (PUT /v1/organizations/{org_id}/billing/band)
	ChangeBand(ctx context.Context, request ChangeBandRequestObject) (ChangeBandResponseObject, error)
	// PreviewBand What moving to a band would charge today
	// (GET /v1/organizations/{org_id}/billing/band-preview)
	PreviewBand(ctx context.Context, request PreviewBandRequestObject) (PreviewBandResponseObject, error)
	// ListInvoices The org's invoices from the provider, newest first
	// (GET /v1/organizations/{org_id}/billing/invoices)
	ListInvoices(ctx context.Context, request ListInvoicesRequestObject) (ListInvoicesResponseObject, error)
	// CancelPending Cancel a scheduled downgrade
	// (DELETE /v1/organizations/{org_id}/billing/pending)
	CancelPending(ctx context.Context, request CancelPendingRequestObject) (CancelPendingResponseObject, error)
	// StartSetup The provider's hosted form, to add or replace the payment method, address and tax ID
	// (POST /v1/organizations/{org_id}/billing/setup)
	StartSetup(ctx context.Context, request StartSetupRequestObject) (StartSetupResponseObject, error)
	// StartTrial Start the one team trial, 14 days, on a free org
	// (POST /v1/organizations/{org_id}/billing/trial)
	StartTrial(ctx context.Context, request StartTrialRequestObject) (StartTrialResponseObject, error)
}

type StrictHandlerFunc func(ctx context.Context, w http.ResponseWriter, r *http.Request, request any) (any, error)
type StrictMiddlewareFunc func(f StrictHandlerFunc, operationID string) StrictHandlerFunc

type StrictHTTPServerOptions struct {
	RequestErrorHandlerFunc  func(w http.ResponseWriter, r *http.Request, err error)
	ResponseErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

func NewStrictHandler(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: StrictHTTPServerOptions{
		RequestErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		},
		ResponseErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusInternalServerError)
		},
	}}
}

func NewStrictHandlerWithOptions(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc, options StrictHTTPServerOptions) ServerInterface {
	if options.RequestErrorHandlerFunc == nil {
		options.RequestErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}
	if options.ResponseErrorHandlerFunc == nil {
		options.ResponseErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusInternalServerError)
		}
	}
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: options}
}

type strictHandler struct {
	ssi         StrictServerInterface
	middlewares []StrictMiddlewareFunc
	options     StrictHTTPServerOptions
}

// MakeRoom operation middleware
func (sh *strictHandler) MakeRoom(w http.ResponseWriter, r *http.Request, orgId OrgId) {
	var request MakeRoomRequestObject

	request.OrgId = orgId

	var body MakeRoomJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.MakeRoom(ctx, request.(MakeRoomRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "MakeRoom")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(MakeRoomResponseObject); ok {
		if err := validResponse.VisitMakeRoomResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// CloseAccount operation middleware
func (sh *strictHandler) CloseAccount(w http.ResponseWriter, r *http.Request, orgId OrgId) {
	var request CloseAccountRequestObject

	request.OrgId = orgId

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.CloseAccount(ctx, request.(CloseAccountRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "CloseAccount")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(CloseAccountResponseObject); ok {
		if err := validResponse.VisitCloseAccountResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// PurgeOrgData operation middleware
func (sh *strictHandler) PurgeOrgData(w http.ResponseWriter, r *http.Request, orgId OrgId) {
	var request PurgeOrgDataRequestObject

	request.OrgId = orgId

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.PurgeOrgData(ctx, request.(PurgeOrgDataRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "PurgeOrgData")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(PurgeOrgDataResponseObject); ok {
		if err := validResponse.VisitPurgeOrgDataResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// ExportOrgData operation middleware
func (sh *strictHandler) ExportOrgData(w http.ResponseWriter, r *http.Request, orgId OrgId) {
	var request ExportOrgDataRequestObject

	request.OrgId = orgId

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.ExportOrgData(ctx, request.(ExportOrgDataRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "ExportOrgData")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(ExportOrgDataResponseObject); ok {
		if err := validResponse.VisitExportOrgDataResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// MembersChanged operation middleware
func (sh *strictHandler) MembersChanged(w http.ResponseWriter, r *http.Request, orgId OrgId) {
	var request MembersChangedRequestObject

	request.OrgId = orgId

	var body MembersChangedJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.MembersChanged(ctx, request.(MembersChangedRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "MembersChanged")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(MembersChangedResponseObject); ok {
		if err := validResponse.VisitMembersChangedResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// ExportUserData operation middleware
func (sh *strictHandler) ExportUserData(w http.ResponseWriter, r *http.Request, userId openapi_types.UUID, params ExportUserDataParams) {
	var request ExportUserDataRequestObject

	request.UserId = userId
	request.Params = params

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.ExportUserData(ctx, request.(ExportUserDataRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "ExportUserData")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(ExportUserDataResponseObject); ok {
		if err := validResponse.VisitExportUserDataResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetBilling operation middleware
func (sh *strictHandler) GetBilling(w http.ResponseWriter, r *http.Request, orgId OrgId) {
	var request GetBillingRequestObject

	request.OrgId = orgId

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetBilling(ctx, request.(GetBillingRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetBilling")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetBillingResponseObject); ok {
		if err := validResponse.VisitGetBillingResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// SetAutoUpgrade operation middleware
func (sh *strictHandler) SetAutoUpgrade(w http.ResponseWriter, r *http.Request, orgId OrgId) {
	var request SetAutoUpgradeRequestObject

	request.OrgId = orgId

	var body SetAutoUpgradeJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.SetAutoUpgrade(ctx, request.(SetAutoUpgradeRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "SetAutoUpgrade")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(SetAutoUpgradeResponseObject); ok {
		if err := validResponse.VisitSetAutoUpgradeResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// ChangeBand operation middleware
func (sh *strictHandler) ChangeBand(w http.ResponseWriter, r *http.Request, orgId OrgId) {
	var request ChangeBandRequestObject

	request.OrgId = orgId

	var body ChangeBandJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.ChangeBand(ctx, request.(ChangeBandRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "ChangeBand")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(ChangeBandResponseObject); ok {
		if err := validResponse.VisitChangeBandResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// PreviewBand operation middleware
func (sh *strictHandler) PreviewBand(w http.ResponseWriter, r *http.Request, orgId OrgId, params PreviewBandParams) {
	var request PreviewBandRequestObject

	request.OrgId = orgId
	request.Params = params

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.PreviewBand(ctx, request.(PreviewBandRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "PreviewBand")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(PreviewBandResponseObject); ok {
		if err := validResponse.VisitPreviewBandResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// ListInvoices operation middleware
func (sh *strictHandler) ListInvoices(w http.ResponseWriter, r *http.Request, orgId OrgId) {
	var request ListInvoicesRequestObject

	request.OrgId = orgId

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.ListInvoices(ctx, request.(ListInvoicesRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "ListInvoices")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(ListInvoicesResponseObject); ok {
		if err := validResponse.VisitListInvoicesResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// CancelPending operation middleware
func (sh *strictHandler) CancelPending(w http.ResponseWriter, r *http.Request, orgId OrgId) {
	var request CancelPendingRequestObject

	request.OrgId = orgId

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.CancelPending(ctx, request.(CancelPendingRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "CancelPending")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(CancelPendingResponseObject); ok {
		if err := validResponse.VisitCancelPendingResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// StartSetup operation middleware
func (sh *strictHandler) StartSetup(w http.ResponseWriter, r *http.Request, orgId OrgId) {
	var request StartSetupRequestObject

	request.OrgId = orgId

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.StartSetup(ctx, request.(StartSetupRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "StartSetup")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(StartSetupResponseObject); ok {
		if err := validResponse.VisitStartSetupResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// StartTrial operation middleware
func (sh *strictHandler) StartTrial(w http.ResponseWriter, r *http.Request, orgId OrgId) {
	var request StartTrialRequestObject

	request.OrgId = orgId

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.StartTrial(ctx, request.(StartTrialRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "StartTrial")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(StartTrialResponseObject); ok {
		if err := validResponse.VisitStartTrialResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}
