// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: projects.sql

package store

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const addMember = `-- name: AddMember :one
INSERT INTO project_members (org_id, project_id, membership_id)
VALUES ($1, $2, $3)
ON CONFLICT (org_id, project_id, membership_id) DO NOTHING
RETURNING org_id, project_id, membership_id, created_by, created_at, last_modified_by, last_modified_at
`

type AddMemberParams struct {
	OrgID        uuid.UUID
	ProjectID    uuid.UUID
	MembershipID uuid.UUID
}

// Nothing when already a member: the caller reads it back.
func (q *Queries) AddMember(ctx context.Context, arg AddMemberParams) (ProjectMember, error) {
	row := q.db.QueryRow(ctx, addMember, arg.OrgID, arg.ProjectID, arg.MembershipID)
	var i ProjectMember
	err := row.Scan(
		&i.OrgID,
		&i.ProjectID,
		&i.MembershipID,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.LastModifiedBy,
		&i.LastModifiedAt,
	)
	return i, err
}

const countMembers = `-- name: CountMembers :one
SELECT count(*) FROM project_members WHERE org_id = $1 AND project_id = $2
`

type CountMembersParams struct {
	OrgID     uuid.UUID
	ProjectID uuid.UUID
}

func (q *Queries) CountMembers(ctx context.Context, arg CountMembersParams) (int64, error) {
	row := q.db.QueryRow(ctx, countMembers, arg.OrgID, arg.ProjectID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countOrgRows = `-- name: CountOrgRows :one
SELECT (SELECT count(*) FROM projects p WHERE p.org_id = $1)
     + (SELECT count(*) FROM project_members m WHERE m.org_id = $1) AS remaining
`

// What is left of the org, across every table here.
func (q *Queries) CountOrgRows(ctx context.Context, orgID uuid.UUID) (int32, error) {
	row := q.db.QueryRow(ctx, countOrgRows, orgID)
	var remaining int32
	err := row.Scan(&remaining)
	return remaining, err
}

const countProjects = `-- name: CountProjects :one
SELECT count(*) FROM projects WHERE org_id = $1
`

func (q *Queries) CountProjects(ctx context.Context, orgID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countProjects, orgID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const deleteProject = `-- name: DeleteProject :execrows
DELETE FROM projects WHERE org_id = $1 AND id = $2
`

type DeleteProjectParams struct {
	OrgID uuid.UUID
	ID    uuid.UUID
}

func (q *Queries) DeleteProject(ctx context.Context, arg DeleteProjectParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteProject, arg.OrgID, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const exportMembers = `-- name: ExportMembers :many
SELECT org_id, project_id, membership_id, created_by, created_at, last_modified_by, last_modified_at FROM project_members WHERE org_id = $1 ORDER BY project_id, created_at, membership_id
`

func (q *Queries) ExportMembers(ctx context.Context, orgID uuid.UUID) ([]ProjectMember, error) {
	rows, err := q.db.Query(ctx, exportMembers, orgID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ProjectMember{}
	for rows.Next() {
		var i ProjectMember
		if err := rows.Scan(
			&i.OrgID,
			&i.ProjectID,
			&i.MembershipID,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.LastModifiedBy,
			&i.LastModifiedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const exportProjects = `-- name: ExportProjects :many

SELECT org_id, id, name, description, cover_key, cover_content_type, idempotency_key, created_by, created_at, last_modified_by, last_modified_at FROM projects WHERE org_id = $1 ORDER BY created_at, id
`

// An org's data, for its export and its purge; a person's, for their own
// export and for forgetting them.
func (q *Queries) ExportProjects(ctx context.Context, orgID uuid.UUID) ([]Project, error) {
	rows, err := q.db.Query(ctx, exportProjects, orgID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Project{}
	for rows.Next() {
		var i Project
		if err := rows.Scan(
			&i.OrgID,
			&i.ID,
			&i.Name,
			&i.Description,
			&i.CoverKey,
			&i.CoverContentType,
			&i.IdempotencyKey,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.LastModifiedBy,
			&i.LastModifiedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const forgetMembership = `-- name: ForgetMembership :execrows
DELETE FROM project_members WHERE org_id = $1 AND membership_id = $2
`

type ForgetMembershipParams struct {
	OrgID        uuid.UUID
	MembershipID uuid.UUID
}

func (q *Queries) ForgetMembership(ctx context.Context, arg ForgetMembershipParams) (int64, error) {
	result, err := q.db.Exec(ctx, forgetMembership, arg.OrgID, arg.MembershipID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getMember = `-- name: GetMember :one
SELECT org_id, project_id, membership_id, created_by, created_at, last_modified_by, last_modified_at FROM project_members WHERE org_id = $1 AND project_id = $2 AND membership_id = $3
`

type GetMemberParams struct {
	OrgID        uuid.UUID
	ProjectID    uuid.UUID
	MembershipID uuid.UUID
}

func (q *Queries) GetMember(ctx context.Context, arg GetMemberParams) (ProjectMember, error) {
	row := q.db.QueryRow(ctx, getMember, arg.OrgID, arg.ProjectID, arg.MembershipID)
	var i ProjectMember
	err := row.Scan(
		&i.OrgID,
		&i.ProjectID,
		&i.MembershipID,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.LastModifiedBy,
		&i.LastModifiedAt,
	)
	return i, err
}

const getProject = `-- name: GetProject :one
SELECT org_id, id, name, description, cover_key, cover_content_type, idempotency_key, created_by, created_at, last_modified_by, last_modified_at FROM projects WHERE org_id = $1 AND id = $2
`

type GetProjectParams struct {
	OrgID uuid.UUID
	ID    uuid.UUID
}

func (q *Queries) GetProject(ctx context.Context, arg GetProjectParams) (Project, error) {
	row := q.db.QueryRow(ctx, getProject, arg.OrgID, arg.ID)
	var i Project
	err := row.Scan(
		&i.OrgID,
		&i.ID,
		&i.Name,
		&i.Description,
		&i.CoverKey,
		&i.CoverContentType,
		&i.IdempotencyKey,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.LastModifiedBy,
		&i.LastModifiedAt,
	)
	return i, err
}

const insertProject = `-- name: InsertProject :one
INSERT INTO projects (org_id, id, name, description, idempotency_key)
VALUES ($1, $2, $3, $4, $5)
ON CONFLICT (org_id, created_by, idempotency_key) WHERE idempotency_key IS NOT NULL DO NOTHING
RETURNING org_id, id, name, description, cover_key, cover_content_type, idempotency_key, created_by, created_at, last_modified_by, last_modified_at
`

type InsertProjectParams struct {
	OrgID          uuid.UUID
	ID             uuid.UUID
	Name           string
	Description    string
	IdempotencyKey pgtype.Text
}

// A retried create carries the same idempotency key, and the partial unique
// index on (org_id, created_by, idempotency_key) makes the second insert do
// nothing; the caller then finds the first with ProjectByIdempotencyKey.
func (q *Queries) InsertProject(ctx context.Context, arg InsertProjectParams) (Project, error) {
	row := q.db.QueryRow(ctx, insertProject,
		arg.OrgID,
		arg.ID,
		arg.Name,
		arg.Description,
		arg.IdempotencyKey,
	)
	var i Project
	err := row.Scan(
		&i.OrgID,
		&i.ID,
		&i.Name,
		&i.Description,
		&i.CoverKey,
		&i.CoverContentType,
		&i.IdempotencyKey,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.LastModifiedBy,
		&i.LastModifiedAt,
	)
	return i, err
}

const listMembers = `-- name: ListMembers :many
SELECT org_id, project_id, membership_id, created_by, created_at, last_modified_by, last_modified_at FROM project_members WHERE org_id = $1 AND project_id = $2
ORDER BY created_at, membership_id
LIMIT 500
`

type ListMembersParams struct {
	OrgID     uuid.UUID
	ProjectID uuid.UUID
}

func (q *Queries) ListMembers(ctx context.Context, arg ListMembersParams) ([]ProjectMember, error) {
	rows, err := q.db.Query(ctx, listMembers, arg.OrgID, arg.ProjectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ProjectMember{}
	for rows.Next() {
		var i ProjectMember
		if err := rows.Scan(
			&i.OrgID,
			&i.ProjectID,
			&i.MembershipID,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.LastModifiedBy,
			&i.LastModifiedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProjects = `-- name: ListProjects :many
SELECT org_id, id, name, description, cover_key, cover_content_type, idempotency_key, created_by, created_at, last_modified_by, last_modified_at FROM projects
WHERE org_id = $1
  AND (NOT $2::boolean OR (created_at, id) < ($3::timestamptz, $4::uuid))
ORDER BY created_at DESC, id DESC
LIMIT $5
`

type ListProjectsParams struct {
	OrgID    uuid.UUID
	After    bool
	CursorAt time.Time
	CursorID uuid.UUID
	PageSize int32
}

// Newest first. The cursor is the last row seen: (created_at, id) below it.
func (q *Queries) ListProjects(ctx context.Context, arg ListProjectsParams) ([]Project, error) {
	rows, err := q.db.Query(ctx, listProjects,
		arg.OrgID,
		arg.After,
		arg.CursorAt,
		arg.CursorID,
		arg.PageSize,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Project{}
	for rows.Next() {
		var i Project
		if err := rows.Scan(
			&i.OrgID,
			&i.ID,
			&i.Name,
			&i.Description,
			&i.CoverKey,
			&i.CoverContentType,
			&i.IdempotencyKey,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.LastModifiedBy,
			&i.LastModifiedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockOrgProjects = `-- name: LockOrgProjects :exec
SELECT pg_advisory_xact_lock(hashtextextended('projects.create:' || $1::text, 0))
`

// Creates in one org queue here, so two at the plan's cap cannot both pass
// the count. Held until the transaction ends.
func (q *Queries) LockOrgProjects(ctx context.Context, orgID string) error {
	_, err := q.db.Exec(ctx, lockOrgProjects, orgID)
	return err
}

const memberCounts = `-- name: MemberCounts :many
SELECT project_id, count(*) AS members FROM project_members
WHERE org_id = $1 AND project_id = ANY($2::uuid[])
GROUP BY project_id
`

type MemberCountsParams struct {
	OrgID      uuid.UUID
	ProjectIds []uuid.UUID
}

type MemberCountsRow struct {
	ProjectID uuid.UUID
	Members   int64
}

func (q *Queries) MemberCounts(ctx context.Context, arg MemberCountsParams) ([]MemberCountsRow, error) {
	rows, err := q.db.Query(ctx, memberCounts, arg.OrgID, arg.ProjectIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []MemberCountsRow{}
	for rows.Next() {
		var i MemberCountsRow
		if err := rows.Scan(&i.ProjectID, &i.Members); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const projectByIdempotencyKey = `-- name: ProjectByIdempotencyKey :one
SELECT org_id, id, name, description, cover_key, cover_content_type, idempotency_key, created_by, created_at, last_modified_by, last_modified_at FROM projects
WHERE org_id = $1 AND created_by = $2 AND idempotency_key = $3
`

type ProjectByIdempotencyKeyParams struct {
	OrgID          uuid.UUID
	CreatedBy      string
	IdempotencyKey pgtype.Text
}

func (q *Queries) ProjectByIdempotencyKey(ctx context.Context, arg ProjectByIdempotencyKeyParams) (Project, error) {
	row := q.db.QueryRow(ctx, projectByIdempotencyKey, arg.OrgID, arg.CreatedBy, arg.IdempotencyKey)
	var i Project
	err := row.Scan(
		&i.OrgID,
		&i.ID,
		&i.Name,
		&i.Description,
		&i.CoverKey,
		&i.CoverContentType,
		&i.IdempotencyKey,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.LastModifiedBy,
		&i.LastModifiedAt,
	)
	return i, err
}

const projectsOfMembership = `-- name: ProjectsOfMembership :many
SELECT p.id, p.name, m.created_at AS added_at
FROM project_members m JOIN projects p ON p.org_id = m.org_id AND p.id = m.project_id
WHERE m.org_id = $1 AND m.membership_id = $2
ORDER BY m.created_at, p.id
`

type ProjectsOfMembershipParams struct {
	OrgID        uuid.UUID
	MembershipID uuid.UUID
}

type ProjectsOfMembershipRow struct {
	ID      uuid.UUID
	Name    string
	AddedAt time.Time
}

func (q *Queries) ProjectsOfMembership(ctx context.Context, arg ProjectsOfMembershipParams) ([]ProjectsOfMembershipRow, error) {
	rows, err := q.db.Query(ctx, projectsOfMembership, arg.OrgID, arg.MembershipID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ProjectsOfMembershipRow{}
	for rows.Next() {
		var i ProjectsOfMembershipRow
		if err := rows.Scan(&i.ID, &i.Name, &i.AddedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const purgeProjects = `-- name: PurgeProjects :execrows
DELETE FROM projects WHERE org_id = $1
`

// Members go with their projects (ON DELETE CASCADE).
func (q *Queries) PurgeProjects(ctx context.Context, orgID uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, purgeProjects, orgID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const removeMember = `-- name: RemoveMember :execrows
DELETE FROM project_members WHERE org_id = $1 AND project_id = $2 AND membership_id = $3
`

type RemoveMemberParams struct {
	OrgID        uuid.UUID
	ProjectID    uuid.UUID
	MembershipID uuid.UUID
}

func (q *Queries) RemoveMember(ctx context.Context, arg RemoveMemberParams) (int64, error) {
	result, err := q.db.Exec(ctx, removeMember, arg.OrgID, arg.ProjectID, arg.MembershipID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const setCover = `-- name: SetCover :one
UPDATE projects SET cover_key = $1, cover_content_type = $2
WHERE org_id = $3 AND id = $4
RETURNING org_id, id, name, description, cover_key, cover_content_type, idempotency_key, created_by, created_at, last_modified_by, last_modified_at
`

type SetCoverParams struct {
	CoverKey         pgtype.Text
	CoverContentType pgtype.Text
	OrgID            uuid.UUID
	ID               uuid.UUID
}

func (q *Queries) SetCover(ctx context.Context, arg SetCoverParams) (Project, error) {
	row := q.db.QueryRow(ctx, setCover,
		arg.CoverKey,
		arg.CoverContentType,
		arg.OrgID,
		arg.ID,
	)
	var i Project
	err := row.Scan(
		&i.OrgID,
		&i.ID,
		&i.Name,
		&i.Description,
		&i.CoverKey,
		&i.CoverContentType,
		&i.IdempotencyKey,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.LastModifiedBy,
		&i.LastModifiedAt,
	)
	return i, err
}

const updateProject = `-- name: UpdateProject :one
UPDATE projects
SET name = coalesce($1, name),
    description = coalesce($2, description)
WHERE org_id = $3 AND id = $4
RETURNING org_id, id, name, description, cover_key, cover_content_type, idempotency_key, created_by, created_at, last_modified_by, last_modified_at
`

type UpdateProjectParams struct {
	Name        pgtype.Text
	Description pgtype.Text
	OrgID       uuid.UUID
	ID          uuid.UUID
}

func (q *Queries) UpdateProject(ctx context.Context, arg UpdateProjectParams) (Project, error) {
	row := q.db.QueryRow(ctx, updateProject,
		arg.Name,
		arg.Description,
		arg.OrgID,
		arg.ID,
	)
	var i Project
	err := row.Scan(
		&i.OrgID,
		&i.ID,
		&i.Name,
		&i.Description,
		&i.CoverKey,
		&i.CoverContentType,
		&i.IdempotencyKey,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.LastModifiedBy,
		&i.LastModifiedAt,
	)
	return i, err
}
