// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: api_keys.sql

package store

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const aPIKeyByHash = `-- name: APIKeyByHash :one
SELECT org_id, id, kind, name, prefix, token_hash, groups, user_id, membership_id, expires_at, last_used_at, revoked_at, created_by, created_at, last_modified_by, last_modified_at FROM api_keys WHERE token_hash = $1
`

// global: the bearer token names no org; it is found by its hash.
func (q *Queries) APIKeyByHash(ctx context.Context, tokenHash []byte) (ApiKey, error) {
	row := q.db.QueryRow(ctx, aPIKeyByHash, tokenHash)
	var i ApiKey
	err := row.Scan(
		&i.OrgID,
		&i.ID,
		&i.Kind,
		&i.Name,
		&i.Prefix,
		&i.TokenHash,
		&i.Groups,
		&i.UserID,
		&i.MembershipID,
		&i.ExpiresAt,
		&i.LastUsedAt,
		&i.RevokedAt,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.LastModifiedBy,
		&i.LastModifiedAt,
	)
	return i, err
}

const deleteAPIKeysOfOrg = `-- name: DeleteAPIKeysOfOrg :execrows
DELETE FROM api_keys WHERE org_id = $1
`

func (q *Queries) DeleteAPIKeysOfOrg(ctx context.Context, orgID uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, deleteAPIKeysOfOrg, orgID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteAPIKeysOfUser = `-- name: DeleteAPIKeysOfUser :execrows
DELETE FROM api_keys WHERE user_id = $1::uuid
`

// global: a person's personal access tokens, in every org, deleted with them.
func (q *Queries) DeleteAPIKeysOfUser(ctx context.Context, userID uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, deleteAPIKeysOfUser, userID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getAPIKey = `-- name: GetAPIKey :one
SELECT org_id, id, kind, name, prefix, token_hash, groups, user_id, membership_id, expires_at, last_used_at, revoked_at, created_by, created_at, last_modified_by, last_modified_at FROM api_keys WHERE org_id = $1 AND id = $2
`

type GetAPIKeyParams struct {
	OrgID uuid.UUID
	ID    uuid.UUID
}

func (q *Queries) GetAPIKey(ctx context.Context, arg GetAPIKeyParams) (ApiKey, error) {
	row := q.db.QueryRow(ctx, getAPIKey, arg.OrgID, arg.ID)
	var i ApiKey
	err := row.Scan(
		&i.OrgID,
		&i.ID,
		&i.Kind,
		&i.Name,
		&i.Prefix,
		&i.TokenHash,
		&i.Groups,
		&i.UserID,
		&i.MembershipID,
		&i.ExpiresAt,
		&i.LastUsedAt,
		&i.RevokedAt,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.LastModifiedBy,
		&i.LastModifiedAt,
	)
	return i, err
}

const insertAPIKey = `-- name: InsertAPIKey :one
INSERT INTO api_keys (org_id, id, kind, name, prefix, token_hash, groups, user_id, membership_id, expires_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10)
RETURNING org_id, id, kind, name, prefix, token_hash, groups, user_id, membership_id, expires_at, last_used_at, revoked_at, created_by, created_at, last_modified_by, last_modified_at
`

type InsertAPIKeyParams struct {
	OrgID        uuid.UUID
	ID           uuid.UUID
	Kind         string
	Name         string
	Prefix       string
	TokenHash    []byte
	Groups       []string
	UserID       pgtype.UUID
	MembershipID pgtype.UUID
	ExpiresAt    pgtype.Timestamptz
}

func (q *Queries) InsertAPIKey(ctx context.Context, arg InsertAPIKeyParams) (ApiKey, error) {
	row := q.db.QueryRow(ctx, insertAPIKey,
		arg.OrgID,
		arg.ID,
		arg.Kind,
		arg.Name,
		arg.Prefix,
		arg.TokenHash,
		arg.Groups,
		arg.UserID,
		arg.MembershipID,
		arg.ExpiresAt,
	)
	var i ApiKey
	err := row.Scan(
		&i.OrgID,
		&i.ID,
		&i.Kind,
		&i.Name,
		&i.Prefix,
		&i.TokenHash,
		&i.Groups,
		&i.UserID,
		&i.MembershipID,
		&i.ExpiresAt,
		&i.LastUsedAt,
		&i.RevokedAt,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.LastModifiedBy,
		&i.LastModifiedAt,
	)
	return i, err
}

const listAPIKeysOfOrg = `-- name: ListAPIKeysOfOrg :many
SELECT org_id, id, kind, name, prefix, token_hash, groups, user_id, membership_id, expires_at, last_used_at, revoked_at, created_by, created_at, last_modified_by, last_modified_at FROM api_keys WHERE org_id = $1 ORDER BY created_at DESC, id DESC
`

// Every key and personal access token in the org, newest first.
func (q *Queries) ListAPIKeysOfOrg(ctx context.Context, orgID uuid.UUID) ([]ApiKey, error) {
	rows, err := q.db.Query(ctx, listAPIKeysOfOrg, orgID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ApiKey{}
	for rows.Next() {
		var i ApiKey
		if err := rows.Scan(
			&i.OrgID,
			&i.ID,
			&i.Kind,
			&i.Name,
			&i.Prefix,
			&i.TokenHash,
			&i.Groups,
			&i.UserID,
			&i.MembershipID,
			&i.ExpiresAt,
			&i.LastUsedAt,
			&i.RevokedAt,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.LastModifiedBy,
			&i.LastModifiedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPersonalTokens = `-- name: ListPersonalTokens :many
SELECT org_id, id, kind, name, prefix, token_hash, groups, user_id, membership_id, expires_at, last_used_at, revoked_at, created_by, created_at, last_modified_by, last_modified_at FROM api_keys WHERE org_id = $1 AND membership_id = $2 ORDER BY created_at DESC, id DESC
`

type ListPersonalTokensParams struct {
	OrgID        uuid.UUID
	MembershipID pgtype.UUID
}

// One person's personal access tokens in the org, newest first.
func (q *Queries) ListPersonalTokens(ctx context.Context, arg ListPersonalTokensParams) ([]ApiKey, error) {
	rows, err := q.db.Query(ctx, listPersonalTokens, arg.OrgID, arg.MembershipID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ApiKey{}
	for rows.Next() {
		var i ApiKey
		if err := rows.Scan(
			&i.OrgID,
			&i.ID,
			&i.Kind,
			&i.Name,
			&i.Prefix,
			&i.TokenHash,
			&i.Groups,
			&i.UserID,
			&i.MembershipID,
			&i.ExpiresAt,
			&i.LastUsedAt,
			&i.RevokedAt,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.LastModifiedBy,
			&i.LastModifiedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markAPIKeyFirstUse = `-- name: MarkAPIKeyFirstUse :execrows
UPDATE api_keys SET last_used_at = $1
WHERE org_id = $2 AND id = $3 AND last_used_at IS NULL
`

type MarkAPIKeyFirstUseParams struct {
	Now   pgtype.Timestamptz
	OrgID uuid.UUID
	ID    uuid.UUID
}

// The first use, once: of two racing first requests only one sees a row.
func (q *Queries) MarkAPIKeyFirstUse(ctx context.Context, arg MarkAPIKeyFirstUseParams) (int64, error) {
	result, err := q.db.Exec(ctx, markAPIKeyFirstUse, arg.Now, arg.OrgID, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const revokeAPIKey = `-- name: RevokeAPIKey :one
UPDATE api_keys SET revoked_at = now()
WHERE org_id = $1 AND id = $2 AND revoked_at IS NULL
RETURNING org_id, id, kind, name, prefix, token_hash, groups, user_id, membership_id, expires_at, last_used_at, revoked_at, created_by, created_at, last_modified_by, last_modified_at
`

type RevokeAPIKeyParams struct {
	OrgID uuid.UUID
	ID    uuid.UUID
}

// Revoked at once: the next request with it is refused.
func (q *Queries) RevokeAPIKey(ctx context.Context, arg RevokeAPIKeyParams) (ApiKey, error) {
	row := q.db.QueryRow(ctx, revokeAPIKey, arg.OrgID, arg.ID)
	var i ApiKey
	err := row.Scan(
		&i.OrgID,
		&i.ID,
		&i.Kind,
		&i.Name,
		&i.Prefix,
		&i.TokenHash,
		&i.Groups,
		&i.UserID,
		&i.MembershipID,
		&i.ExpiresAt,
		&i.LastUsedAt,
		&i.RevokedAt,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.LastModifiedBy,
		&i.LastModifiedAt,
	)
	return i, err
}

const touchAPIKey = `-- name: TouchAPIKey :execrows
UPDATE api_keys SET last_used_at = $1
WHERE org_id = $2 AND id = $3 AND last_used_at < $4
`

type TouchAPIKeyParams struct {
	Now   pgtype.Timestamptz
	OrgID uuid.UUID
	ID    uuid.UUID
	Since pgtype.Timestamptz
}

// The last use, written only when the one recorded is before since (a
// minute ago), so a busy key costs no write per request.
func (q *Queries) TouchAPIKey(ctx context.Context, arg TouchAPIKeyParams) (int64, error) {
	result, err := q.db.Exec(ctx, touchAPIKey,
		arg.Now,
		arg.OrgID,
		arg.ID,
		arg.Since,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
