// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package store

import (
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

// global: a sign-in is a person's, who may belong to several orgs, like the session it becomes
type DesktopSignInCode struct {
	ID                 uuid.UUID
	CodeHash           []byte
	UserID             uuid.UUID
	SignedInOrgID      uuid.UUID
	ActiveOrgID        pgtype.UUID
	ActiveMembershipID pgtype.UUID
	Provider           string
	Client             string
	AppChallenge       string
	ExpiresAt          time.Time
	UsedAt             pgtype.Timestamptz
	CreatedBy          string
	CreatedAt          time.Time
	LastModifiedBy     string
	LastModifiedAt     time.Time
}

// global: a verification is a person's, keyed by the token
type EmailVerification struct {
	ID             uuid.UUID
	UserID         uuid.UUID
	OrgID          uuid.UUID
	OrgName        string
	TokenHash      []byte
	ExpiresAt      time.Time
	UsedAt         pgtype.Timestamptz
	Purpose        string
	Address        pgtype.Text
	CreatedBy      string
	CreatedAt      time.Time
	LastModifiedBy string
	LastModifiedAt time.Time
}

type IdentityProvider struct {
	OrgID                uuid.UUID
	ID                   uuid.UUID
	Preset               string
	Issuer               string
	TenantID             pgtype.Text
	HostedDomain         pgtype.Text
	ClientID             string
	ClientSecret         []byte
	Scopes               []string
	EmailClaim           string
	NameClaim            string
	RequireEmailVerified bool
	Status               string
	VerifiedAt           pgtype.Timestamptz
	CreatedBy            string
	CreatedAt            time.Time
	LastModifiedBy       string
	LastModifiedAt       time.Time
}

type Invite struct {
	OrgID                 uuid.UUID
	ID                    uuid.UUID
	Email                 string
	Role                  string
	App                   string
	TokenHash             []byte
	ExpiresAt             time.Time
	AcceptedAt            pgtype.Timestamptz
	AcceptedUserID        pgtype.UUID
	AcceptedMembershipID  pgtype.UUID
	RevokedAt             pgtype.Timestamptz
	InvitedByMembershipID pgtype.UUID
	CreatedBy             string
	CreatedAt             time.Time
	LastModifiedBy        string
	LastModifiedAt        time.Time
}

// global: an account is a person's, who may belong to several orgs
type LocalAccount struct {
	UserID          uuid.UUID
	Email           string
	EmailVerifiedAt pgtype.Timestamptz
	PasswordHash    pgtype.Text
	PasswordSetAt   pgtype.Timestamptz
	CreatedBy       string
	CreatedAt       time.Time
	LastModifiedBy  string
	LastModifiedAt  time.Time
}

// global: a challenge is a person's sign-in in flight, keyed by its token
type MfaChallenge struct {
	ID                 uuid.UUID
	UserID             uuid.UUID
	TokenHash          []byte
	Kind               string
	SignedInOrgID      uuid.UUID
	ActiveOrgID        pgtype.UUID
	ActiveMembershipID pgtype.UUID
	ExpiresAt          time.Time
	UsedAt             pgtype.Timestamptz
	CreatedBy          string
	CreatedAt          time.Time
	LastModifiedBy     string
	LastModifiedAt     time.Time
}

// global: recovery codes are a person's
type MfaRecoveryCode struct {
	UserID         uuid.UUID
	ID             uuid.UUID
	CodeHash       []byte
	UsedAt         pgtype.Timestamptz
	CreatedBy      string
	CreatedAt      time.Time
	LastModifiedBy string
	LastModifiedAt time.Time
}

// global: an authenticator is a person's, who may belong to several orgs
type MfaTotp struct {
	UserID         uuid.UUID
	WrappedSecret  []byte
	KmsKeyVersion  string
	ConfirmedAt    pgtype.Timestamptz
	LastUsedStep   int64
	CreatedBy      string
	CreatedAt      time.Time
	LastModifiedBy string
	LastModifiedAt time.Time
}

// global: a session is a person's, who may belong to several orgs
type Session struct {
	ID                 uuid.UUID
	UserID             uuid.UUID
	ActiveOrgID        pgtype.UUID
	ActiveMembershipID pgtype.UUID
	RefreshTokenHash   []byte
	SignedInOrgID      uuid.UUID
	ExpiresAt          time.Time
	LastSeenAt         time.Time
	RevokedAt          pgtype.Timestamptz
	IdleTimeoutSeconds int32
	UserAgent          pgtype.Text
	RevokedReason      pgtype.Text
	CreatedBy          string
	CreatedAt          time.Time
	LastModifiedBy     string
	LastModifiedAt     time.Time
}

type SessionPolicy struct {
	OrgID              uuid.UUID
	LifetimeSeconds    int32
	IdleTimeoutSeconds int32
	MfaRequired        bool
	CreatedBy          string
	CreatedAt          time.Time
	LastModifiedBy     string
	LastModifiedAt     time.Time
}

type SignInAttempt struct {
	OrgID          uuid.UUID
	ID             uuid.UUID
	CodeVerifier   string
	Nonce          string
	NextPath       string
	App            string
	ExpiresAt      time.Time
	UsedAt         pgtype.Timestamptz
	Client         string
	AppChallenge   pgtype.Text
	CreatedBy      string
	CreatedAt      time.Time
	LastModifiedBy string
	LastModifiedAt time.Time
}

// global: the platform's token signing keys, not an org's
type SigningKey struct {
	ID             uuid.UUID
	Kid            string
	Algorithm      string
	WrappedPrivate []byte
	KmsKeyVersion  string
	PublicJwk      []byte
	State          string
	CreatedBy      string
	CreatedAt      time.Time
	LastModifiedBy string
	LastModifiedAt time.Time
}
