// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: onboarding.sql

package store

import (
	"context"

	"github.com/google/uuid"
)

const deleteOrgOnboardingDismissals = `-- name: DeleteOrgOnboardingDismissals :exec
DELETE FROM onboarding_dismissals WHERE org_id = $1
`

func (q *Queries) DeleteOrgOnboardingDismissals(ctx context.Context, orgID uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteOrgOnboardingDismissals, orgID)
	return err
}

const dismissOnboarding = `-- name: DismissOnboarding :execrows
INSERT INTO onboarding_dismissals (org_id, step_id) VALUES ($1, $2)
ON CONFLICT (org_id, step_id) DO NOTHING
`

type DismissOnboardingParams struct {
	OrgID  uuid.UUID
	StepID string
}

// Once: a second dismissal changes nothing.
func (q *Queries) DismissOnboarding(ctx context.Context, arg DismissOnboardingParams) (int64, error) {
	result, err := q.db.Exec(ctx, dismissOnboarding, arg.OrgID, arg.StepID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const listOnboardingDismissals = `-- name: ListOnboardingDismissals :many
SELECT step_id FROM onboarding_dismissals WHERE org_id = $1
`

func (q *Queries) ListOnboardingDismissals(ctx context.Context, orgID uuid.UUID) ([]string, error) {
	rows, err := q.db.Query(ctx, listOnboardingDismissals, orgID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var step_id string
		if err := rows.Scan(&step_id); err != nil {
			return nil, err
		}
		items = append(items, step_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const restoreOnboarding = `-- name: RestoreOnboarding :execrows
DELETE FROM onboarding_dismissals WHERE org_id = $1 AND step_id = $2
`

type RestoreOnboardingParams struct {
	OrgID  uuid.UUID
	StepID string
}

func (q *Queries) RestoreOnboarding(ctx context.Context, arg RestoreOnboardingParams) (int64, error) {
	result, err := q.db.Exec(ctx, restoreOnboarding, arg.OrgID, arg.StepID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
