// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: plan_overrides.sql

package store

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const deleteOrgPlanOverrides = `-- name: DeleteOrgPlanOverrides :exec
DELETE FROM plan_overrides WHERE org_id = $1
`

func (q *Queries) DeleteOrgPlanOverrides(ctx context.Context, orgID uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteOrgPlanOverrides, orgID)
	return err
}

const deletePlanOverride = `-- name: DeletePlanOverride :one
DELETE FROM plan_overrides WHERE org_id = $1 AND kind = $2 AND key = $3
RETURNING org_id, kind, key, cap, allowed, ends_at, created_by, created_at, last_modified_by, last_modified_at
`

type DeletePlanOverrideParams struct {
	OrgID uuid.UUID
	Kind  string
	Key   string
}

func (q *Queries) DeletePlanOverride(ctx context.Context, arg DeletePlanOverrideParams) (PlanOverride, error) {
	row := q.db.QueryRow(ctx, deletePlanOverride, arg.OrgID, arg.Kind, arg.Key)
	var i PlanOverride
	err := row.Scan(
		&i.OrgID,
		&i.Kind,
		&i.Key,
		&i.Cap,
		&i.Allowed,
		&i.EndsAt,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.LastModifiedBy,
		&i.LastModifiedAt,
	)
	return i, err
}

const getPlanOverride = `-- name: GetPlanOverride :one
SELECT org_id, kind, key, cap, allowed, ends_at, created_by, created_at, last_modified_by, last_modified_at FROM plan_overrides WHERE org_id = $1 AND kind = $2 AND key = $3
`

type GetPlanOverrideParams struct {
	OrgID uuid.UUID
	Kind  string
	Key   string
}

func (q *Queries) GetPlanOverride(ctx context.Context, arg GetPlanOverrideParams) (PlanOverride, error) {
	row := q.db.QueryRow(ctx, getPlanOverride, arg.OrgID, arg.Kind, arg.Key)
	var i PlanOverride
	err := row.Scan(
		&i.OrgID,
		&i.Kind,
		&i.Key,
		&i.Cap,
		&i.Allowed,
		&i.EndsAt,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.LastModifiedBy,
		&i.LastModifiedAt,
	)
	return i, err
}

const listPlanOverrides = `-- name: ListPlanOverrides :many
SELECT org_id, kind, key, cap, allowed, ends_at, created_by, created_at, last_modified_by, last_modified_at FROM plan_overrides WHERE org_id = $1 ORDER BY kind DESC, key
`

func (q *Queries) ListPlanOverrides(ctx context.Context, orgID uuid.UUID) ([]PlanOverride, error) {
	rows, err := q.db.Query(ctx, listPlanOverrides, orgID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PlanOverride{}
	for rows.Next() {
		var i PlanOverride
		if err := rows.Scan(
			&i.OrgID,
			&i.Kind,
			&i.Key,
			&i.Cap,
			&i.Allowed,
			&i.EndsAt,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.LastModifiedBy,
			&i.LastModifiedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertPlanOverride = `-- name: UpsertPlanOverride :one
INSERT INTO plan_overrides (org_id, kind, key, cap, allowed, ends_at)
VALUES ($1, $2, $3, $4, $5, $6)
ON CONFLICT (org_id, kind, key) DO UPDATE
SET cap = excluded.cap, allowed = excluded.allowed, ends_at = excluded.ends_at
RETURNING org_id, kind, key, cap, allowed, ends_at, created_by, created_at, last_modified_by, last_modified_at
`

type UpsertPlanOverrideParams struct {
	OrgID   uuid.UUID
	Kind    string
	Key     string
	Cap     pgtype.Int4
	Allowed pgtype.Bool
	EndsAt  pgtype.Timestamptz
}

func (q *Queries) UpsertPlanOverride(ctx context.Context, arg UpsertPlanOverrideParams) (PlanOverride, error) {
	row := q.db.QueryRow(ctx, upsertPlanOverride,
		arg.OrgID,
		arg.Kind,
		arg.Key,
		arg.Cap,
		arg.Allowed,
		arg.EndsAt,
	)
	var i PlanOverride
	err := row.Scan(
		&i.OrgID,
		&i.Kind,
		&i.Key,
		&i.Cap,
		&i.Allowed,
		&i.EndsAt,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.LastModifiedBy,
		&i.LastModifiedAt,
	)
	return i, err
}
