// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: signups.sql

package store

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const completeSignup = `-- name: CompleteSignup :one
UPDATE signups SET completed_at = now(), created_org_id = $1
WHERE id = $2 AND completed_at IS NULL
RETURNING id, email, name, org_name, time_zone, token_hash, expires_at, completed_at, created_org_id, created_by, created_at, last_modified_by, last_modified_at
`

type CompleteSignupParams struct {
	CreatedOrgID pgtype.UUID
	ID           uuid.UUID
}

// One completion, in the statement that finds it.
func (q *Queries) CompleteSignup(ctx context.Context, arg CompleteSignupParams) (Signup, error) {
	row := q.db.QueryRow(ctx, completeSignup, arg.CreatedOrgID, arg.ID)
	var i Signup
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Name,
		&i.OrgName,
		&i.TimeZone,
		&i.TokenHash,
		&i.ExpiresAt,
		&i.CompletedAt,
		&i.CreatedOrgID,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.LastModifiedBy,
		&i.LastModifiedAt,
	)
	return i, err
}

const countRecentSignups = `-- name: CountRecentSignups :one
SELECT count(*) FROM signups WHERE email = $1 AND created_at > now() - $2::interval
`

type CountRecentSignupsParams struct {
	Email string
	Since pgtype.Interval
}

// global: how many links an address was sent lately, before any org exists.
func (q *Queries) CountRecentSignups(ctx context.Context, arg CountRecentSignupsParams) (int64, error) {
	row := q.db.QueryRow(ctx, countRecentSignups, arg.Email, arg.Since)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const deleteOldSignups = `-- name: DeleteOldSignups :execrows
DELETE FROM signups WHERE expires_at < now() - interval '30 days'
`

// global: the daily sweep, across every signup.
func (q *Queries) DeleteOldSignups(ctx context.Context) (int64, error) {
	result, err := q.db.Exec(ctx, deleteOldSignups)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getSignupByToken = `-- name: GetSignupByToken :one
SELECT id, email, name, org_name, time_zone, token_hash, expires_at, completed_at, created_org_id, created_by, created_at, last_modified_by, last_modified_at FROM signups WHERE token_hash = $1
`

// global: found by the token in the link, which names no org.
func (q *Queries) GetSignupByToken(ctx context.Context, tokenHash []byte) (Signup, error) {
	row := q.db.QueryRow(ctx, getSignupByToken, tokenHash)
	var i Signup
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Name,
		&i.OrgName,
		&i.TimeZone,
		&i.TokenHash,
		&i.ExpiresAt,
		&i.CompletedAt,
		&i.CreatedOrgID,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.LastModifiedBy,
		&i.LastModifiedAt,
	)
	return i, err
}

const insertSignup = `-- name: InsertSignup :one

INSERT INTO signups (id, email, name, org_name, time_zone, token_hash, expires_at)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, email, name, org_name, time_zone, token_hash, expires_at, completed_at, created_org_id, created_by, created_at, last_modified_by, last_modified_at
`

type InsertSignupParams struct {
	ID        uuid.UUID
	Email     string
	Name      string
	OrgName   string
	TimeZone  string
	TokenHash []byte
	ExpiresAt time.Time
}

// Self-serve signups. Global: a signup precedes the org it creates.
// global: a signup precedes the org it creates.
func (q *Queries) InsertSignup(ctx context.Context, arg InsertSignupParams) (Signup, error) {
	row := q.db.QueryRow(ctx, insertSignup,
		arg.ID,
		arg.Email,
		arg.Name,
		arg.OrgName,
		arg.TimeZone,
		arg.TokenHash,
		arg.ExpiresAt,
	)
	var i Signup
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Name,
		&i.OrgName,
		&i.TimeZone,
		&i.TokenHash,
		&i.ExpiresAt,
		&i.CompletedAt,
		&i.CreatedOrgID,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.LastModifiedBy,
		&i.LastModifiedAt,
	)
	return i, err
}
