// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package store

import (
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type Account struct {
	OrgID           uuid.UUID
	Provider        string
	CustomerRef     pgtype.Text
	SubscriptionRef pgtype.Text
	ScheduleRef     pgtype.Text
	Band            string
	State           string
	PeriodEnd       pgtype.Timestamptz
	PendingBand     pgtype.Text
	CardBrand       pgtype.Text
	CardLast4       pgtype.Text
	AutoUpgrade     bool
	TrialUsed       bool
	TrialEndsAt     pgtype.Timestamptz
	GraceStartedAt  pgtype.Timestamptz
	Notices         []string
	CreatedBy       string
	CreatedAt       time.Time
	LastModifiedBy  string
	LastModifiedAt  time.Time
}

// global: an event id is the provider's, and is checked before the org is known
type ProcessedEvent struct {
	Provider       string
	EventID        string
	CreatedBy      string
	CreatedAt      time.Time
	LastModifiedBy string
	LastModifiedAt time.Time
}
