// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package store

import (
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type Attempt struct {
	OrgID          uuid.UUID
	ID             uuid.UUID
	DeliveryID     uuid.UUID
	AttemptedAt    time.Time
	Manual         bool
	StatusCode     pgtype.Int4
	LatencyMs      int32
	Error          pgtype.Text
	CreatedBy      string
	CreatedAt      time.Time
	LastModifiedBy string
	LastModifiedAt time.Time
}

type Delivery struct {
	OrgID          uuid.UUID
	ID             uuid.UUID
	MessageID      uuid.UUID
	EndpointID     uuid.UUID
	Status         string
	Attempts       int32
	NextAttemptAt  pgtype.Timestamptz
	LastAttemptAt  pgtype.Timestamptz
	LastStatusCode pgtype.Int4
	LastLatencyMs  pgtype.Int4
	LastError      pgtype.Text
	CreatedBy      string
	CreatedAt      time.Time
	LastModifiedBy string
	LastModifiedAt time.Time
}

type Endpoint struct {
	OrgID             uuid.UUID
	ID                uuid.UUID
	Url               string
	Description       string
	EventTypes        []string
	Enabled           bool
	Secret            []byte
	PreviousSecret    []byte
	PreviousExpiresAt pgtype.Timestamptz
	SecretRotatedAt   pgtype.Timestamptz
	CreatedBy         string
	CreatedAt         time.Time
	LastModifiedBy    string
	LastModifiedAt    time.Time
}

type Message struct {
	OrgID          uuid.UUID
	ID             uuid.UUID
	Type           string
	OccurredAt     time.Time
	Payload        []byte
	CreatedBy      string
	CreatedAt      time.Time
	LastModifiedBy string
	LastModifiedAt time.Time
}
