// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: audit_events.sql

package store

import (
	"context"
	"net/netip"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const allAuditEvents = `-- name: AllAuditEvents :many
SELECT org_id, id, occurred_at, actor, action, target_type, target_id, source_ip, request_id, details
FROM audit_events
WHERE org_id = $1
ORDER BY occurred_at, id
`

type AllAuditEventsRow struct {
	OrgID      uuid.UUID
	ID         uuid.UUID
	OccurredAt time.Time
	Actor      string
	Action     string
	TargetType string
	TargetID   string
	SourceIp   *netip.Addr
	RequestID  pgtype.Text
	Details    []byte
}

// Every entry of the org, oldest first, for its export.
func (q *Queries) AllAuditEvents(ctx context.Context, orgID uuid.UUID) ([]AllAuditEventsRow, error) {
	rows, err := q.db.Query(ctx, allAuditEvents, orgID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AllAuditEventsRow{}
	for rows.Next() {
		var i AllAuditEventsRow
		if err := rows.Scan(
			&i.OrgID,
			&i.ID,
			&i.OccurredAt,
			&i.Actor,
			&i.Action,
			&i.TargetType,
			&i.TargetID,
			&i.SourceIp,
			&i.RequestID,
			&i.Details,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const auditEventsByActors = `-- name: AuditEventsByActors :many
SELECT org_id, id, occurred_at, actor, action, target_type, target_id, source_ip, request_id, details
FROM audit_events
WHERE org_id = $1 AND actor = ANY($2::text[])
ORDER BY occurred_at, id
`

type AuditEventsByActorsParams struct {
	OrgID  uuid.UUID
	Actors []string
}

type AuditEventsByActorsRow struct {
	OrgID      uuid.UUID
	ID         uuid.UUID
	OccurredAt time.Time
	Actor      string
	Action     string
	TargetType string
	TargetID   string
	SourceIp   *netip.Addr
	RequestID  pgtype.Text
	Details    []byte
}

// The entries one person made in one org, as a user or as their membership,
// for their own export.
func (q *Queries) AuditEventsByActors(ctx context.Context, arg AuditEventsByActorsParams) ([]AuditEventsByActorsRow, error) {
	rows, err := q.db.Query(ctx, auditEventsByActors, arg.OrgID, arg.Actors)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AuditEventsByActorsRow{}
	for rows.Next() {
		var i AuditEventsByActorsRow
		if err := rows.Scan(
			&i.OrgID,
			&i.ID,
			&i.OccurredAt,
			&i.Actor,
			&i.Action,
			&i.TargetType,
			&i.TargetID,
			&i.SourceIp,
			&i.RequestID,
			&i.Details,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const countAuditEvents = `-- name: CountAuditEvents :one
SELECT count(*) FROM audit_events WHERE org_id = $1
`

func (q *Queries) CountAuditEvents(ctx context.Context, orgID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countAuditEvents, orgID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const expireAuditEvents = `-- name: ExpireAuditEvents :execrows

DELETE FROM audit_events WHERE org_id = $1 AND occurred_at < $2
`

type ExpireAuditEventsParams struct {
	OrgID  uuid.UUID
	Before time.Time
}

// Retention and purge (UO-183). The transaction first runs
// SET LOCAL audit.retention = 'on', without which the table refuses a DELETE.
// The org's entries older than its retention allows.
func (q *Queries) ExpireAuditEvents(ctx context.Context, arg ExpireAuditEventsParams) (int64, error) {
	result, err := q.db.Exec(ctx, expireAuditEvents, arg.OrgID, arg.Before)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const listAuditEvents = `-- name: ListAuditEvents :many
SELECT org_id, id, occurred_at, actor, action, target_type, target_id, source_ip, request_id, details
FROM audit_events
WHERE org_id = $1
  AND ($3::timestamptz IS NULL
       OR (occurred_at, id) < ($3::timestamptz, $4::uuid))
  AND ($5::text IS NULL OR action LIKE $5::text || '%')
  AND ($6::text IS NULL OR actor = $6::text)
  AND ($7::text IS NULL OR target_type = $7::text)
  AND ($8::text IS NULL OR target_id = $8::text)
  AND ($9::timestamptz IS NULL OR occurred_at >= $9::timestamptz)
  AND ($10::timestamptz IS NULL OR occurred_at < $10::timestamptz)
ORDER BY occurred_at DESC, id DESC
LIMIT $2
`

type ListAuditEventsParams struct {
	OrgID        uuid.UUID
	Limit        int32
	BeforeAt     pgtype.Timestamptz
	BeforeID     pgtype.UUID
	ActionPrefix pgtype.Text
	Actor        pgtype.Text
	TargetType   pgtype.Text
	TargetID     pgtype.Text
	FromAt       pgtype.Timestamptz
	ToAt         pgtype.Timestamptz
}

type ListAuditEventsRow struct {
	OrgID      uuid.UUID
	ID         uuid.UUID
	OccurredAt time.Time
	Actor      string
	Action     string
	TargetType string
	TargetID   string
	SourceIp   *netip.Addr
	RequestID  pgtype.Text
	Details    []byte
}

// Newest first. The cursor is the (occurred_at, id) of the last row seen;
// sqlc.narg values are NULL when the filter is not set. The date range is
// inclusive of its start and exclusive of its end.
func (q *Queries) ListAuditEvents(ctx context.Context, arg ListAuditEventsParams) ([]ListAuditEventsRow, error) {
	rows, err := q.db.Query(ctx, listAuditEvents,
		arg.OrgID,
		arg.Limit,
		arg.BeforeAt,
		arg.BeforeID,
		arg.ActionPrefix,
		arg.Actor,
		arg.TargetType,
		arg.TargetID,
		arg.FromAt,
		arg.ToAt,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAuditEventsRow{}
	for rows.Next() {
		var i ListAuditEventsRow
		if err := rows.Scan(
			&i.OrgID,
			&i.ID,
			&i.OccurredAt,
			&i.Actor,
			&i.Action,
			&i.TargetType,
			&i.TargetID,
			&i.SourceIp,
			&i.RequestID,
			&i.Details,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAuditEventsOldestFirst = `-- name: ListAuditEventsOldestFirst :many
SELECT org_id, id, occurred_at, actor, action, target_type, target_id, source_ip, request_id, details
FROM audit_events
WHERE org_id = $1
  AND ($3::timestamptz IS NULL
       OR (occurred_at, id) > ($3::timestamptz, $4::uuid))
  AND ($5::text IS NULL OR action LIKE $5::text || '%')
  AND ($6::text IS NULL OR actor = $6::text)
  AND ($7::text IS NULL OR target_type = $7::text)
  AND ($8::text IS NULL OR target_id = $8::text)
  AND ($9::timestamptz IS NULL OR occurred_at >= $9::timestamptz)
  AND ($10::timestamptz IS NULL OR occurred_at < $10::timestamptz)
ORDER BY occurred_at ASC, id ASC
LIMIT $2
`

type ListAuditEventsOldestFirstParams struct {
	OrgID        uuid.UUID
	Limit        int32
	AfterAt      pgtype.Timestamptz
	AfterID      pgtype.UUID
	ActionPrefix pgtype.Text
	Actor        pgtype.Text
	TargetType   pgtype.Text
	TargetID     pgtype.Text
	FromAt       pgtype.Timestamptz
	ToAt         pgtype.Timestamptz
}

type ListAuditEventsOldestFirstRow struct {
	OrgID      uuid.UUID
	ID         uuid.UUID
	OccurredAt time.Time
	Actor      string
	Action     string
	TargetType string
	TargetID   string
	SourceIp   *netip.Addr
	RequestID  pgtype.Text
	Details    []byte
}

// The same filters, oldest first: the cursor is the last row seen, and the
// next page is what came after it.
func (q *Queries) ListAuditEventsOldestFirst(ctx context.Context, arg ListAuditEventsOldestFirstParams) ([]ListAuditEventsOldestFirstRow, error) {
	rows, err := q.db.Query(ctx, listAuditEventsOldestFirst,
		arg.OrgID,
		arg.Limit,
		arg.AfterAt,
		arg.AfterID,
		arg.ActionPrefix,
		arg.Actor,
		arg.TargetType,
		arg.TargetID,
		arg.FromAt,
		arg.ToAt,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAuditEventsOldestFirstRow{}
	for rows.Next() {
		var i ListAuditEventsOldestFirstRow
		if err := rows.Scan(
			&i.OrgID,
			&i.ID,
			&i.OccurredAt,
			&i.Actor,
			&i.Action,
			&i.TargetType,
			&i.TargetID,
			&i.SourceIp,
			&i.RequestID,
			&i.Details,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const purgeAuditEvents = `-- name: PurgeAuditEvents :execrows
DELETE FROM audit_events WHERE org_id = $1
`

func (q *Queries) PurgeAuditEvents(ctx context.Context, orgID uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, purgeAuditEvents, orgID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const recordAuditEvent = `-- name: RecordAuditEvent :one
INSERT INTO audit_events (org_id, id, occurred_at, actor, action, target_type, target_id, source_ip, request_id, details)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10)
RETURNING org_id, id, occurred_at, actor, action, target_type, target_id, source_ip, request_id, details
`

type RecordAuditEventParams struct {
	OrgID      uuid.UUID
	ID         uuid.UUID
	OccurredAt time.Time
	Actor      string
	Action     string
	TargetType string
	TargetID   string
	SourceIp   *netip.Addr
	RequestID  pgtype.Text
	Details    []byte
}

type RecordAuditEventRow struct {
	OrgID      uuid.UUID
	ID         uuid.UUID
	OccurredAt time.Time
	Actor      string
	Action     string
	TargetType string
	TargetID   string
	SourceIp   *netip.Addr
	RequestID  pgtype.Text
	Details    []byte
}

func (q *Queries) RecordAuditEvent(ctx context.Context, arg RecordAuditEventParams) (RecordAuditEventRow, error) {
	row := q.db.QueryRow(ctx, recordAuditEvent,
		arg.OrgID,
		arg.ID,
		arg.OccurredAt,
		arg.Actor,
		arg.Action,
		arg.TargetType,
		arg.TargetID,
		arg.SourceIp,
		arg.RequestID,
		arg.Details,
	)
	var i RecordAuditEventRow
	err := row.Scan(
		&i.OrgID,
		&i.ID,
		&i.OccurredAt,
		&i.Actor,
		&i.Action,
		&i.TargetType,
		&i.TargetID,
		&i.SourceIp,
		&i.RequestID,
		&i.Details,
	)
	return i, err
}
