//go:build go1.22

// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.8.0 DO NOT EDIT.
package api

import (
	"bytes"
	"context"
	"encoding/json"
	"errors"
	"fmt"
	"net/http"
	"time"

	"github.com/oapi-codegen/runtime"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

// Defines values for OwnershipTransferStatus.
const (
	Accepted  OwnershipTransferStatus = "accepted"
	Cancelled OwnershipTransferStatus = "cancelled"
	Expired   OwnershipTransferStatus = "expired"
	Pending   OwnershipTransferStatus = "pending"
)

// Valid indicates whether the value is a known member of the OwnershipTransferStatus enum.
func (e OwnershipTransferStatus) Valid() bool {
	switch e {
	case Accepted:
		return true
	case Cancelled:
		return true
	case Expired:
		return true
	case Pending:
		return true
	default:
		return false
	}
}

// Defines values for Permission.
const (
	AssignRoles          Permission = "assign_roles"
	Audit                Permission = "audit"
	Billing              Permission = "billing"
	ClaimDomain          Permission = "claim_domain"
	ConfigurePermissions Permission = "configure_permissions"
	DeleteOrganization   Permission = "delete_organization"
	Offices              Permission = "offices"
	Providers            Permission = "providers"
	Settings             Permission = "settings"
	TransferOwnership    Permission = "transfer_ownership"
	Users                Permission = "users"
)

// Valid indicates whether the value is a known member of the Permission enum.
func (e Permission) Valid() bool {
	switch e {
	case AssignRoles:
		return true
	case Audit:
		return true
	case Billing:
		return true
	case ClaimDomain:
		return true
	case ConfigurePermissions:
		return true
	case DeleteOrganization:
		return true
	case Offices:
		return true
	case Providers:
		return true
	case Settings:
		return true
	case TransferOwnership:
		return true
	case Users:
		return true
	default:
		return false
	}
}

// Defines values for Role.
const (
	Admin        Role = "admin"
	BillingAdmin Role = "billing_admin"
	Guest        Role = "guest"
	Owner        Role = "owner"
	User         Role = "user"
)

// Valid indicates whether the value is a known member of the Role enum.
func (e Role) Valid() bool {
	switch e {
	case Admin:
		return true
	case BillingAdmin:
		return true
	case Guest:
		return true
	case Owner:
		return true
	case User:
		return true
	default:
		return false
	}
}

// DataPart defines model for DataPart.
type DataPart struct {
	Data  map[string]interface{} `json:"data"`
	Files []struct {
		Key  string `json:"key"`
		Name string `json:"name"`
	} `json:"files"`
	Service string `json:"service"`
}

// DataPurged defines model for DataPurged.
type DataPurged struct {
	Remaining int `json:"remaining"`
}

// Error defines model for Error.
type Error struct {
	Code    string             `json:"code"`
	Fields  *map[string]string `json:"fields,omitempty"`
	Message string             `json:"message"`
}

// Grant defines model for Grant.
type Grant struct {
	MembershipId openapi_types.UUID `json:"membership_id"`
	OrgId        openapi_types.UUID `json:"org_id"`
	Permissions  []Permission       `json:"permissions"`

	// Role An org role. Fixed in code; one per membership.
	Role Role `json:"role"`
}

// NewPermissionConfig defines model for NewPermissionConfig.
type NewPermissionConfig struct {
	// Admin The configurable groups the Admin role holds.
	Admin        []Permission `json:"admin"`
	BillingAdmin []Permission `json:"billing_admin"`
}

// OwnershipTransfer defines model for OwnershipTransfer.
type OwnershipTransfer struct {
	AcceptedAt *time.Time `json:"accepted_at,omitempty"`
	CreatedAt  time.Time  `json:"created_at"`
	ExpiresAt  time.Time  `json:"expires_at"`

	// FromMembershipId The Owner asking.
	FromMembershipId openapi_types.UUID      `json:"from_membership_id"`
	OrgId            openapi_types.UUID      `json:"org_id"`
	Status           OwnershipTransferStatus `json:"status"`

	// ToMembershipId The member asked.
	ToMembershipId openapi_types.UUID `json:"to_membership_id"`
	TransferId     openapi_types.UUID `json:"transfer_id"`
}

// OwnershipTransferStatus defines model for OwnershipTransfer.Status.
type OwnershipTransferStatus string

// Permission A configurable group, or an Owner-only action.
type Permission string

// PermissionConfig defines model for PermissionConfig.
type PermissionConfig struct {
	Admin        []Permission `json:"admin"`
	BillingAdmin []Permission `json:"billing_admin"`

	// Effective Every permission each role has under this configuration, by role.
	Effective map[string][]Permission `json:"effective"`
	OrgId     openapi_types.UUID      `json:"org_id"`

	// Warnings What this configuration leaves nobody but the Owner able to do.
	Warnings []string `json:"warnings"`
}

// Role An org role. Fixed in code; one per membership.
type Role string

// RoleAssignment defines model for RoleAssignment.
type RoleAssignment struct {
	MembershipId openapi_types.UUID `json:"membership_id"`
	OrgId        openapi_types.UUID `json:"org_id"`

	// Role An org role. Fixed in code; one per membership.
	Role Role `json:"role"`
}

// MembershipId defines model for MembershipId.
type MembershipId = openapi_types.UUID

// OrgId defines model for OrgId.
type OrgId = openapi_types.UUID

// TransferId defines model for TransferId.
type TransferId = openapi_types.UUID

// ExportUserDataParams defines parameters for ExportUserData.
type ExportUserDataParams struct {
	// Membership Each of the person's memberships, as org_id:membership_id.
	Membership *[]string `form:"membership,omitempty" json:"membership,omitempty"`
}

// SetRoleJSONBody defines parameters for SetRole.
type SetRoleJSONBody struct {
	// Role An org role. Fixed in code; one per membership.
	Role Role `json:"role"`
}

// RequestOwnershipTransferJSONBody defines parameters for RequestOwnershipTransfer.
type RequestOwnershipTransferJSONBody struct {
	ToMembershipId openapi_types.UUID `json:"to_membership_id"`
}

// SetRoleJSONRequestBody defines body for SetRole for application/json ContentType.
type SetRoleJSONRequestBody SetRoleJSONBody

// RequestOwnershipTransferJSONRequestBody defines body for RequestOwnershipTransfer for application/json ContentType.
type RequestOwnershipTransferJSONRequestBody RequestOwnershipTransferJSONBody

// SetPermissionsJSONRequestBody defines body for SetPermissions for application/json ContentType.
type SetPermissionsJSONRequestBody = NewPermissionConfig

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// PurgeOrgData Delete everything this service keeps for an org, and count what is left (the organization service only)
	// (DELETE /v1/internal/organizations/{org_id}/data)
	PurgeOrgData(w http.ResponseWriter, r *http.Request, orgId OrgId)
	// ExportOrgData Everything this service keeps for an org, for its export (the organization service only)
	// (GET /v1/internal/organizations/{org_id}/data)
	ExportOrgData(w http.ResponseWriter, r *http.Request, orgId OrgId)
	// GetGrant What one membership may do right now (services only)
	// (GET /v1/internal/organizations/{org_id}/memberships/{membership_id}/permissions)
	GetGrant(w http.ResponseWriter, r *http.Request, orgId OrgId, membershipId MembershipId)
	// ExportUserData What this service keeps about one person, for their own export (the organization service only)
	// (GET /v1/internal/users/{user_id}/data)
	ExportUserData(w http.ResponseWriter, r *http.Request, userId openapi_types.UUID, params ExportUserDataParams)
	// SetRole Give a membership another org role (Owner only)
	// (PUT /v1/organizations/{org_id}/memberships/{membership_id}/role)
	SetRole(w http.ResponseWriter, r *http.Request, orgId OrgId, membershipId MembershipId)
	// ListOwnershipTransfers The open ownership transfer, for the Owner and for the person asked
	// (GET /v1/organizations/{org_id}/ownership-transfers)
	ListOwnershipTransfers(w http.ResponseWriter, r *http.Request, orgId OrgId)
	// RequestOwnershipTransfer Ask another member to take ownership (Owner only)
	// (POST /v1/organizations/{org_id}/ownership-transfers)
	RequestOwnershipTransfer(w http.ResponseWriter, r *http.Request, orgId OrgId)
	// CancelOwnershipTransfer Withdraw the request (the Owner) or decline it (the person asked)
	// (DELETE /v1/organizations/{org_id}/ownership-transfers/{transfer_id})
	CancelOwnershipTransfer(w http.ResponseWriter, r *http.Request, orgId OrgId, transferId TransferId)
	// AcceptOwnershipTransfer Take ownership (the person asked only)
	// (POST /v1/organizations/{org_id}/ownership-transfers/{transfer_id}/accept)
	AcceptOwnershipTransfer(w http.ResponseWriter, r *http.Request, orgId OrgId, transferId TransferId)
	// GetPermissions The organization's permission configuration and what every role can do
	// (GET /v1/organizations/{org_id}/permissions)
	GetPermissions(w http.ResponseWriter, r *http.Request, orgId OrgId)
	// SetPermissions Change which groups the Admin and Billing Admin roles hold (Owner only)
	// (PUT /v1/organizations/{org_id}/permissions)
	SetPermissions(w http.ResponseWriter, r *http.Request, orgId OrgId)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// PurgeOrgData operation middleware
func (siw *ServerInterfaceWrapper) PurgeOrgData(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "org_id" -------------
	var orgId OrgId

	err = runtime.BindStyledParameterWithOptions("simple", "org_id", r.PathValue("org_id"), &orgId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "org_id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PurgeOrgData(w, r, orgId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ExportOrgData operation middleware
func (siw *ServerInterfaceWrapper) ExportOrgData(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "org_id" -------------
	var orgId OrgId

	err = runtime.BindStyledParameterWithOptions("simple", "org_id", r.PathValue("org_id"), &orgId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "org_id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ExportOrgData(w, r, orgId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetGrant operation middleware
func (siw *ServerInterfaceWrapper) GetGrant(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "org_id" -------------
	var orgId OrgId

	err = runtime.BindStyledParameterWithOptions("simple", "org_id", r.PathValue("org_id"), &orgId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "org_id", Err: err})
		return
	}

	// ------------- Path parameter "membership_id" -------------
	var membershipId MembershipId

	err = runtime.BindStyledParameterWithOptions("simple", "membership_id", r.PathValue("membership_id"), &membershipId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "membership_id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetGrant(w, r, orgId, membershipId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ExportUserData operation middleware
func (siw *ServerInterfaceWrapper) ExportUserData(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "user_id" -------------
	var userId openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "user_id", r.PathValue("user_id"), &userId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "user_id", Err: err})
		return
	}

	// Parameter object where we will unmarshal all parameters from the context
	var params ExportUserDataParams

	// ------------- Optional query parameter "membership" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "membership", r.URL.Query(), &params.Membership, runtime.BindQueryParameterOptions{Type: "array", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "membership"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "membership", Err: err})
		}
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ExportUserData(w, r, userId, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// SetRole operation middleware
func (siw *ServerInterfaceWrapper) SetRole(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "org_id" -------------
	var orgId OrgId

	err = runtime.BindStyledParameterWithOptions("simple", "org_id", r.PathValue("org_id"), &orgId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "org_id", Err: err})
		return
	}

	// ------------- Path parameter "membership_id" -------------
	var membershipId MembershipId

	err = runtime.BindStyledParameterWithOptions("simple", "membership_id", r.PathValue("membership_id"), &membershipId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "membership_id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.SetRole(w, r, orgId, membershipId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListOwnershipTransfers operation middleware
func (siw *ServerInterfaceWrapper) ListOwnershipTransfers(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "org_id" -------------
	var orgId OrgId

	err = runtime.BindStyledParameterWithOptions("simple", "org_id", r.PathValue("org_id"), &orgId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "org_id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListOwnershipTransfers(w, r, orgId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// RequestOwnershipTransfer operation middleware
func (siw *ServerInterfaceWrapper) RequestOwnershipTransfer(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "org_id" -------------
	var orgId OrgId

	err = runtime.BindStyledParameterWithOptions("simple", "org_id", r.PathValue("org_id"), &orgId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "org_id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.RequestOwnershipTransfer(w, r, orgId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// CancelOwnershipTransfer operation middleware
func (siw *ServerInterfaceWrapper) CancelOwnershipTransfer(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "org_id" -------------
	var orgId OrgId

	err = runtime.BindStyledParameterWithOptions("simple", "org_id", r.PathValue("org_id"), &orgId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "org_id", Err: err})
		return
	}

	// ------------- Path parameter "transfer_id" -------------
	var transferId TransferId

	err = runtime.BindStyledParameterWithOptions("simple", "transfer_id", r.PathValue("transfer_id"), &transferId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "transfer_id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CancelOwnershipTransfer(w, r, orgId, transferId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// AcceptOwnershipTransfer operation middleware
func (siw *ServerInterfaceWrapper) AcceptOwnershipTransfer(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "org_id" -------------
	var orgId OrgId

	err = runtime.BindStyledParameterWithOptions("simple", "org_id", r.PathValue("org_id"), &orgId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "org_id", Err: err})
		return
	}

	// ------------- Path parameter "transfer_id" -------------
	var transferId TransferId

	err = runtime.BindStyledParameterWithOptions("simple", "transfer_id", r.PathValue("transfer_id"), &transferId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "transfer_id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.AcceptOwnershipTransfer(w, r, orgId, transferId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetPermissions operation middleware
func (siw *ServerInterfaceWrapper) GetPermissions(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "org_id" -------------
	var orgId OrgId

	err = runtime.BindStyledParameterWithOptions("simple", "org_id", r.PathValue("org_id"), &orgId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "org_id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetPermissions(w, r, orgId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// SetPermissions operation middleware
func (siw *ServerInterfaceWrapper) SetPermissions(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "org_id" -------------
	var orgId OrgId

	err = runtime.BindStyledParameterWithOptions("simple", "org_id", r.PathValue("org_id"), &orgId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "org_id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.SetPermissions(w, r, orgId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{})
}

// ServeMux is an abstraction of [http.ServeMux].
type ServeMux interface {
	HandleFunc(pattern string, handler func(http.ResponseWriter, *http.Request))
	http.Handler
}

type StdHTTPServerOptions struct {
	BaseURL          string
	BaseRouter       ServeMux
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, m ServeMux) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{
		BaseRouter: m,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, m ServeMux, baseURL string) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{
		BaseURL:    baseURL,
		BaseRouter: m,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options StdHTTPServerOptions) http.Handler {
	m := options.BaseRouter

	if m == nil {
		m = http.NewServeMux()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}

	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/v1/organizations/{org_id}/permissions", wrapper.GetPermissions)
	m.HandleFunc(http.MethodPut+" "+options.BaseURL+"/v1/organizations/{org_id}/permissions", wrapper.SetPermissions)
	m.HandleFunc(http.MethodPut+" "+options.BaseURL+"/v1/organizations/{org_id}/memberships/{membership_id}/role", wrapper.SetRole)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/v1/organizations/{org_id}/ownership-transfers", wrapper.ListOwnershipTransfers)
	m.HandleFunc(http.MethodPost+" "+options.BaseURL+"/v1/organizations/{org_id}/ownership-transfers", wrapper.RequestOwnershipTransfer)
	m.HandleFunc(http.MethodPost+" "+options.BaseURL+"/v1/organizations/{org_id}/ownership-transfers/{transfer_id}/accept", wrapper.AcceptOwnershipTransfer)
	m.HandleFunc(http.MethodDelete+" "+options.BaseURL+"/v1/organizations/{org_id}/ownership-transfers/{transfer_id}", wrapper.CancelOwnershipTransfer)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/v1/internal/organizations/{org_id}/memberships/{membership_id}/permissions", wrapper.GetGrant)
	m.HandleFunc(http.MethodDelete+" "+options.BaseURL+"/v1/internal/organizations/{org_id}/data", wrapper.PurgeOrgData)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/v1/internal/organizations/{org_id}/data", wrapper.ExportOrgData)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/v1/internal/users/{user_id}/data", wrapper.ExportUserData)

	return m
}

type ErrorJSONResponse Error

type PurgeOrgDataRequestObject struct {
	OrgId OrgId `json:"org_id"`
}

type PurgeOrgDataResponseObject interface {
	VisitPurgeOrgDataResponse(w http.ResponseWriter) error
}

type PurgeOrgData200JSONResponse DataPurged

func (response PurgeOrgData200JSONResponse) VisitPurgeOrgDataResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type PurgeOrgData403JSONResponse struct{ ErrorJSONResponse }

func (response PurgeOrgData403JSONResponse) VisitPurgeOrgDataResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(403)
	_, err := buf.WriteTo(w)
	return err
}

type PurgeOrgDatadefaultJSONResponse struct {
	Body       Error
	StatusCode int
}

func (response PurgeOrgDatadefaultJSONResponse) VisitPurgeOrgDataResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(response.StatusCode)
	_, err := buf.WriteTo(w)
	return err
}

type ExportOrgDataRequestObject struct {
	OrgId OrgId `json:"org_id"`
}

type ExportOrgDataResponseObject interface {
	VisitExportOrgDataResponse(w http.ResponseWriter) error
}

type ExportOrgData200JSONResponse DataPart

func (response ExportOrgData200JSONResponse) VisitExportOrgDataResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type ExportOrgData403JSONResponse struct{ ErrorJSONResponse }

func (response ExportOrgData403JSONResponse) VisitExportOrgDataResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(403)
	_, err := buf.WriteTo(w)
	return err
}

type ExportOrgDatadefaultJSONResponse struct {
	Body       Error
	StatusCode int
}

func (response ExportOrgDatadefaultJSONResponse) VisitExportOrgDataResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(response.StatusCode)
	_, err := buf.WriteTo(w)
	return err
}

type GetGrantRequestObject struct {
	OrgId        OrgId        `json:"org_id"`
	MembershipId MembershipId `json:"membership_id"`
}

type GetGrantResponseObject interface {
	VisitGetGrantResponse(w http.ResponseWriter) error
}

type GetGrant200JSONResponse Grant

func (response GetGrant200JSONResponse) VisitGetGrantResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type GetGrant401JSONResponse struct{ ErrorJSONResponse }

func (response GetGrant401JSONResponse) VisitGetGrantResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type GetGrant403JSONResponse Error

func (response GetGrant403JSONResponse) VisitGetGrantResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(403)
	_, err := buf.WriteTo(w)
	return err
}

type GetGrant404JSONResponse Error

func (response GetGrant404JSONResponse) VisitGetGrantResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)
	_, err := buf.WriteTo(w)
	return err
}

type GetGrantdefaultJSONResponse struct {
	Body       Error
	StatusCode int
}

func (response GetGrantdefaultJSONResponse) VisitGetGrantResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(response.StatusCode)
	_, err := buf.WriteTo(w)
	return err
}

type ExportUserDataRequestObject struct {
	UserId openapi_types.UUID `json:"user_id"`
	Params ExportUserDataParams
}

type ExportUserDataResponseObject interface {
	VisitExportUserDataResponse(w http.ResponseWriter) error
}

type ExportUserData200JSONResponse DataPart

func (response ExportUserData200JSONResponse) VisitExportUserDataResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type ExportUserData400JSONResponse struct{ ErrorJSONResponse }

func (response ExportUserData400JSONResponse) VisitExportUserDataResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)
	_, err := buf.WriteTo(w)
	return err
}

type ExportUserData403JSONResponse Error

func (response ExportUserData403JSONResponse) VisitExportUserDataResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(403)
	_, err := buf.WriteTo(w)
	return err
}

type ExportUserDatadefaultJSONResponse struct {
	Body       Error
	StatusCode int
}

func (response ExportUserDatadefaultJSONResponse) VisitExportUserDataResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(response.StatusCode)
	_, err := buf.WriteTo(w)
	return err
}

type SetRoleRequestObject struct {
	OrgId        OrgId        `json:"org_id"`
	MembershipId MembershipId `json:"membership_id"`
	Body         *SetRoleJSONRequestBody
}

type SetRoleResponseObject interface {
	VisitSetRoleResponse(w http.ResponseWriter) error
}

type SetRole200JSONResponse RoleAssignment

func (response SetRole200JSONResponse) VisitSetRoleResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type SetRole400JSONResponse struct{ ErrorJSONResponse }

func (response SetRole400JSONResponse) VisitSetRoleResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)
	_, err := buf.WriteTo(w)
	return err
}

type SetRole401JSONResponse Error

func (response SetRole401JSONResponse) VisitSetRoleResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type SetRole403JSONResponse Error

func (response SetRole403JSONResponse) VisitSetRoleResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(403)
	_, err := buf.WriteTo(w)
	return err
}

type SetRole404JSONResponse Error

func (response SetRole404JSONResponse) VisitSetRoleResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)
	_, err := buf.WriteTo(w)
	return err
}

type SetRole409JSONResponse Error

func (response SetRole409JSONResponse) VisitSetRoleResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(409)
	_, err := buf.WriteTo(w)
	return err
}

type SetRoledefaultJSONResponse struct {
	Body       Error
	StatusCode int
}

func (response SetRoledefaultJSONResponse) VisitSetRoleResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(response.StatusCode)
	_, err := buf.WriteTo(w)
	return err
}

type ListOwnershipTransfersRequestObject struct {
	OrgId OrgId `json:"org_id"`
}

type ListOwnershipTransfersResponseObject interface {
	VisitListOwnershipTransfersResponse(w http.ResponseWriter) error
}

type ListOwnershipTransfers200JSONResponse struct {
	Transfers []OwnershipTransfer `json:"transfers"`
}

func (response ListOwnershipTransfers200JSONResponse) VisitListOwnershipTransfersResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type ListOwnershipTransfers401JSONResponse struct{ ErrorJSONResponse }

func (response ListOwnershipTransfers401JSONResponse) VisitListOwnershipTransfersResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type ListOwnershipTransfers403JSONResponse Error

func (response ListOwnershipTransfers403JSONResponse) VisitListOwnershipTransfersResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(403)
	_, err := buf.WriteTo(w)
	return err
}

type ListOwnershipTransfersdefaultJSONResponse struct {
	Body       Error
	StatusCode int
}

func (response ListOwnershipTransfersdefaultJSONResponse) VisitListOwnershipTransfersResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(response.StatusCode)
	_, err := buf.WriteTo(w)
	return err
}

type RequestOwnershipTransferRequestObject struct {
	OrgId OrgId `json:"org_id"`
	Body  *RequestOwnershipTransferJSONRequestBody
}

type RequestOwnershipTransferResponseObject interface {
	VisitRequestOwnershipTransferResponse(w http.ResponseWriter) error
}

type RequestOwnershipTransfer201JSONResponse OwnershipTransfer

func (response RequestOwnershipTransfer201JSONResponse) VisitRequestOwnershipTransferResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(201)
	_, err := buf.WriteTo(w)
	return err
}

type RequestOwnershipTransfer400JSONResponse struct{ ErrorJSONResponse }

func (response RequestOwnershipTransfer400JSONResponse) VisitRequestOwnershipTransferResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)
	_, err := buf.WriteTo(w)
	return err
}

type RequestOwnershipTransfer401JSONResponse Error

func (response RequestOwnershipTransfer401JSONResponse) VisitRequestOwnershipTransferResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type RequestOwnershipTransfer403JSONResponse Error

func (response RequestOwnershipTransfer403JSONResponse) VisitRequestOwnershipTransferResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(403)
	_, err := buf.WriteTo(w)
	return err
}

type RequestOwnershipTransfer404JSONResponse Error

func (response RequestOwnershipTransfer404JSONResponse) VisitRequestOwnershipTransferResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)
	_, err := buf.WriteTo(w)
	return err
}

type RequestOwnershipTransferdefaultJSONResponse struct {
	Body       Error
	StatusCode int
}

func (response RequestOwnershipTransferdefaultJSONResponse) VisitRequestOwnershipTransferResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(response.StatusCode)
	_, err := buf.WriteTo(w)
	return err
}

type CancelOwnershipTransferRequestObject struct {
	OrgId      OrgId      `json:"org_id"`
	TransferId TransferId `json:"transfer_id"`
}

type CancelOwnershipTransferResponseObject interface {
	VisitCancelOwnershipTransferResponse(w http.ResponseWriter) error
}

type CancelOwnershipTransfer204Response struct {
}

func (response CancelOwnershipTransfer204Response) VisitCancelOwnershipTransferResponse(w http.ResponseWriter) error {
	w.WriteHeader(204)
	return nil
}

type CancelOwnershipTransfer401JSONResponse struct{ ErrorJSONResponse }

func (response CancelOwnershipTransfer401JSONResponse) VisitCancelOwnershipTransferResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type CancelOwnershipTransfer403JSONResponse Error

func (response CancelOwnershipTransfer403JSONResponse) VisitCancelOwnershipTransferResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(403)
	_, err := buf.WriteTo(w)
	return err
}

type CancelOwnershipTransfer404JSONResponse Error

func (response CancelOwnershipTransfer404JSONResponse) VisitCancelOwnershipTransferResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)
	_, err := buf.WriteTo(w)
	return err
}

type CancelOwnershipTransferdefaultJSONResponse struct {
	Body       Error
	StatusCode int
}

func (response CancelOwnershipTransferdefaultJSONResponse) VisitCancelOwnershipTransferResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(response.StatusCode)
	_, err := buf.WriteTo(w)
	return err
}

type AcceptOwnershipTransferRequestObject struct {
	OrgId      OrgId      `json:"org_id"`
	TransferId TransferId `json:"transfer_id"`
}

type AcceptOwnershipTransferResponseObject interface {
	VisitAcceptOwnershipTransferResponse(w http.ResponseWriter) error
}

type AcceptOwnershipTransfer200JSONResponse OwnershipTransfer

func (response AcceptOwnershipTransfer200JSONResponse) VisitAcceptOwnershipTransferResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type AcceptOwnershipTransfer401JSONResponse struct{ ErrorJSONResponse }

func (response AcceptOwnershipTransfer401JSONResponse) VisitAcceptOwnershipTransferResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type AcceptOwnershipTransfer403JSONResponse Error

func (response AcceptOwnershipTransfer403JSONResponse) VisitAcceptOwnershipTransferResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(403)
	_, err := buf.WriteTo(w)
	return err
}

type AcceptOwnershipTransfer404JSONResponse Error

func (response AcceptOwnershipTransfer404JSONResponse) VisitAcceptOwnershipTransferResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)
	_, err := buf.WriteTo(w)
	return err
}

type AcceptOwnershipTransfer409JSONResponse Error

func (response AcceptOwnershipTransfer409JSONResponse) VisitAcceptOwnershipTransferResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(409)
	_, err := buf.WriteTo(w)
	return err
}

type AcceptOwnershipTransferdefaultJSONResponse struct {
	Body       Error
	StatusCode int
}

func (response AcceptOwnershipTransferdefaultJSONResponse) VisitAcceptOwnershipTransferResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(response.StatusCode)
	_, err := buf.WriteTo(w)
	return err
}

type GetPermissionsRequestObject struct {
	OrgId OrgId `json:"org_id"`
}

type GetPermissionsResponseObject interface {
	VisitGetPermissionsResponse(w http.ResponseWriter) error
}

type GetPermissions200JSONResponse PermissionConfig

func (response GetPermissions200JSONResponse) VisitGetPermissionsResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type GetPermissions401JSONResponse struct{ ErrorJSONResponse }

func (response GetPermissions401JSONResponse) VisitGetPermissionsResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type GetPermissions403JSONResponse Error

func (response GetPermissions403JSONResponse) VisitGetPermissionsResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(403)
	_, err := buf.WriteTo(w)
	return err
}

type GetPermissionsdefaultJSONResponse struct {
	Body       Error
	StatusCode int
}

func (response GetPermissionsdefaultJSONResponse) VisitGetPermissionsResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(response.StatusCode)
	_, err := buf.WriteTo(w)
	return err
}

type SetPermissionsRequestObject struct {
	OrgId OrgId `json:"org_id"`
	Body  *SetPermissionsJSONRequestBody
}

type SetPermissionsResponseObject interface {
	VisitSetPermissionsResponse(w http.ResponseWriter) error
}

type SetPermissions200JSONResponse PermissionConfig

func (response SetPermissions200JSONResponse) VisitSetPermissionsResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type SetPermissions400JSONResponse struct{ ErrorJSONResponse }

func (response SetPermissions400JSONResponse) VisitSetPermissionsResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)
	_, err := buf.WriteTo(w)
	return err
}

type SetPermissions401JSONResponse Error

func (response SetPermissions401JSONResponse) VisitSetPermissionsResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type SetPermissions403JSONResponse Error

func (response SetPermissions403JSONResponse) VisitSetPermissionsResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(403)
	_, err := buf.WriteTo(w)
	return err
}

type SetPermissionsdefaultJSONResponse struct {
	Body       Error
	StatusCode int
}

func (response SetPermissionsdefaultJSONResponse) VisitSetPermissionsResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(response.StatusCode)
	_, err := buf.WriteTo(w)
	return err
}

// StrictServerInterface represents all server handlers.
type StrictServerInterface interface {
	// PurgeOrgData Delete everything this service keeps for an org, and count what is left (the organization service only)
	// (DELETE /v1/internal/organizations/{org_id}/data)
	PurgeOrgData(ctx context.Context, request PurgeOrgDataRequestObject) (PurgeOrgDataResponseObject, error)
	// ExportOrgData Everything this service keeps for an org, for its export (the organization service only)
	// (GET /v1/internal/organizations/{org_id}/data)
	ExportOrgData(ctx context.Context, request ExportOrgDataRequestObject) (ExportOrgDataResponseObject, error)
	// GetGrant What one membership may do right now (services only)
	// (GET /v1/internal/organizations/{org_id}/memberships/{membership_id}/permissions)
	GetGrant(ctx context.Context, request GetGrantRequestObject) (GetGrantResponseObject, error)
	// ExportUserData What this service keeps about one person, for their own export (the organization service only)
	// (GET /v1/internal/users/{user_id}/data)
	ExportUserData(ctx context.Context, request ExportUserDataRequestObject) (ExportUserDataResponseObject, error)
	// SetRole Give a membership another org role (Owner only)
	// (PUT /v1/organizations/{org_id}/memberships/{membership_id}/role)
	SetRole(ctx context.Context, request SetRoleRequestObject) (SetRoleResponseObject, error)
	// ListOwnershipTransfers The open ownership transfer, for the Owner and for the person asked
	// (GET /v1/organizations/{org_id}/ownership-transfers)
	ListOwnershipTransfers(ctx context.Context, request ListOwnershipTransfersRequestObject) (ListOwnershipTransfersResponseObject, error)
	// RequestOwnershipTransfer Ask another member to take ownership (Owner only)
	// (POST /v1/organizations/{org_id}/ownership-transfers)
	RequestOwnershipTransfer(ctx context.Context, request RequestOwnershipTransferRequestObject) (RequestOwnershipTransferResponseObject, error)
	// CancelOwnershipTransfer Withdraw the request (the Owner) or decline it (the person asked)
	// (DELETE /v1/organizations/{org_id}/ownership-transfers/{transfer_id})
	CancelOwnershipTransfer(ctx context.Context, request CancelOwnershipTransferRequestObject) (CancelOwnershipTransferResponseObject, error)
	// AcceptOwnershipTransfer Take ownership (the person asked only)
	// (POST /v1/organizations/{org_id}/ownership-transfers/{transfer_id}/accept)
	AcceptOwnershipTransfer(ctx context.Context, request AcceptOwnershipTransferRequestObject) (AcceptOwnershipTransferResponseObject, error)
	// GetPermissions The organization's permission configuration and what every role can do
	// (GET /v1/organizations/{org_id}/permissions)
	GetPermissions(ctx context.Context, request GetPermissionsRequestObject) (GetPermissionsResponseObject, error)
	// SetPermissions Change which groups the Admin and Billing Admin roles hold (Owner only)
	// (PUT /v1/organizations/{org_id}/permissions)
	SetPermissions(ctx context.Context, request SetPermissionsRequestObject) (SetPermissionsResponseObject, error)
}

type StrictHandlerFunc func(ctx context.Context, w http.ResponseWriter, r *http.Request, request any) (any, error)
type StrictMiddlewareFunc func(f StrictHandlerFunc, operationID string) StrictHandlerFunc

type StrictHTTPServerOptions struct {
	RequestErrorHandlerFunc  func(w http.ResponseWriter, r *http.Request, err error)
	ResponseErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

func NewStrictHandler(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: StrictHTTPServerOptions{
		RequestErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		},
		ResponseErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusInternalServerError)
		},
	}}
}

func NewStrictHandlerWithOptions(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc, options StrictHTTPServerOptions) ServerInterface {
	if options.RequestErrorHandlerFunc == nil {
		options.RequestErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}
	if options.ResponseErrorHandlerFunc == nil {
		options.ResponseErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusInternalServerError)
		}
	}
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: options}
}

type strictHandler struct {
	ssi         StrictServerInterface
	middlewares []StrictMiddlewareFunc
	options     StrictHTTPServerOptions
}

// PurgeOrgData operation middleware
func (sh *strictHandler) PurgeOrgData(w http.ResponseWriter, r *http.Request, orgId OrgId) {
	var request PurgeOrgDataRequestObject

	request.OrgId = orgId

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.PurgeOrgData(ctx, request.(PurgeOrgDataRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "PurgeOrgData")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(PurgeOrgDataResponseObject); ok {
		if err := validResponse.VisitPurgeOrgDataResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// ExportOrgData operation middleware
func (sh *strictHandler) ExportOrgData(w http.ResponseWriter, r *http.Request, orgId OrgId) {
	var request ExportOrgDataRequestObject

	request.OrgId = orgId

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.ExportOrgData(ctx, request.(ExportOrgDataRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "ExportOrgData")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(ExportOrgDataResponseObject); ok {
		if err := validResponse.VisitExportOrgDataResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetGrant operation middleware
func (sh *strictHandler) GetGrant(w http.ResponseWriter, r *http.Request, orgId OrgId, membershipId MembershipId) {
	var request GetGrantRequestObject

	request.OrgId = orgId
	request.MembershipId = membershipId

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetGrant(ctx, request.(GetGrantRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetGrant")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetGrantResponseObject); ok {
		if err := validResponse.VisitGetGrantResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// ExportUserData operation middleware
func (sh *strictHandler) ExportUserData(w http.ResponseWriter, r *http.Request, userId openapi_types.UUID, params ExportUserDataParams) {
	var request ExportUserDataRequestObject

	request.UserId = userId
	request.Params = params

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.ExportUserData(ctx, request.(ExportUserDataRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "ExportUserData")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(ExportUserDataResponseObject); ok {
		if err := validResponse.VisitExportUserDataResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// SetRole operation middleware
func (sh *strictHandler) SetRole(w http.ResponseWriter, r *http.Request, orgId OrgId, membershipId MembershipId) {
	var request SetRoleRequestObject

	request.OrgId = orgId
	request.MembershipId = membershipId

	var body SetRoleJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.SetRole(ctx, request.(SetRoleRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "SetRole")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(SetRoleResponseObject); ok {
		if err := validResponse.VisitSetRoleResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// ListOwnershipTransfers operation middleware
func (sh *strictHandler) ListOwnershipTransfers(w http.ResponseWriter, r *http.Request, orgId OrgId) {
	var request ListOwnershipTransfersRequestObject

	request.OrgId = orgId

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.ListOwnershipTransfers(ctx, request.(ListOwnershipTransfersRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "ListOwnershipTransfers")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(ListOwnershipTransfersResponseObject); ok {
		if err := validResponse.VisitListOwnershipTransfersResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// RequestOwnershipTransfer operation middleware
func (sh *strictHandler) RequestOwnershipTransfer(w http.ResponseWriter, r *http.Request, orgId OrgId) {
	var request RequestOwnershipTransferRequestObject

	request.OrgId = orgId

	var body RequestOwnershipTransferJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.RequestOwnershipTransfer(ctx, request.(RequestOwnershipTransferRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "RequestOwnershipTransfer")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(RequestOwnershipTransferResponseObject); ok {
		if err := validResponse.VisitRequestOwnershipTransferResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// CancelOwnershipTransfer operation middleware
func (sh *strictHandler) CancelOwnershipTransfer(w http.ResponseWriter, r *http.Request, orgId OrgId, transferId TransferId) {
	var request CancelOwnershipTransferRequestObject

	request.OrgId = orgId
	request.TransferId = transferId

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.CancelOwnershipTransfer(ctx, request.(CancelOwnershipTransferRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "CancelOwnershipTransfer")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(CancelOwnershipTransferResponseObject); ok {
		if err := validResponse.VisitCancelOwnershipTransferResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// AcceptOwnershipTransfer operation middleware
func (sh *strictHandler) AcceptOwnershipTransfer(w http.ResponseWriter, r *http.Request, orgId OrgId, transferId TransferId) {
	var request AcceptOwnershipTransferRequestObject

	request.OrgId = orgId
	request.TransferId = transferId

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.AcceptOwnershipTransfer(ctx, request.(AcceptOwnershipTransferRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "AcceptOwnershipTransfer")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(AcceptOwnershipTransferResponseObject); ok {
		if err := validResponse.VisitAcceptOwnershipTransferResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetPermissions operation middleware
func (sh *strictHandler) GetPermissions(w http.ResponseWriter, r *http.Request, orgId OrgId) {
	var request GetPermissionsRequestObject

	request.OrgId = orgId

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetPermissions(ctx, request.(GetPermissionsRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetPermissions")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetPermissionsResponseObject); ok {
		if err := validResponse.VisitGetPermissionsResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// SetPermissions operation middleware
func (sh *strictHandler) SetPermissions(w http.ResponseWriter, r *http.Request, orgId OrgId) {
	var request SetPermissionsRequestObject

	request.OrgId = orgId

	var body SetPermissionsJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.SetPermissions(ctx, request.(SetPermissionsRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "SetPermissions")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(SetPermissionsResponseObject); ok {
		if err := validResponse.VisitSetPermissionsResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}
