// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package store

import (
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type OwnershipTransfer struct {
	OrgID            uuid.UUID
	ID               uuid.UUID
	FromMembershipID uuid.UUID
	ToMembershipID   uuid.UUID
	ExpiresAt        time.Time
	AcceptedAt       pgtype.Timestamptz
	CancelledAt      pgtype.Timestamptz
	CreatedBy        string
	CreatedAt        time.Time
	LastModifiedBy   string
	LastModifiedAt   time.Time
}

type PermissionConfig struct {
	OrgID                   uuid.UUID
	AdminPermissions        []string
	BillingAdminPermissions []string
	CreatedBy               string
	CreatedAt               time.Time
	LastModifiedBy          string
	LastModifiedAt          time.Time
}
