// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: orgdata.sql

package store

import (
	"context"

	"github.com/google/uuid"
)

const countOrgRows = `-- name: CountOrgRows :one
SELECT (SELECT count(*) FROM permission_configs p WHERE p.org_id = $1)
     + (SELECT count(*) FROM ownership_transfers t WHERE t.org_id = $1) AS remaining
`

// What is left of the org, across every table here.
func (q *Queries) CountOrgRows(ctx context.Context, orgID uuid.UUID) (int32, error) {
	row := q.db.QueryRow(ctx, countOrgRows, orgID)
	var remaining int32
	err := row.Scan(&remaining)
	return remaining, err
}

const exportOwnershipTransfers = `-- name: ExportOwnershipTransfers :many
SELECT org_id, id, from_membership_id, to_membership_id, expires_at, accepted_at, cancelled_at, created_by, created_at, last_modified_by, last_modified_at FROM ownership_transfers WHERE org_id = $1 ORDER BY created_at, id
`

func (q *Queries) ExportOwnershipTransfers(ctx context.Context, orgID uuid.UUID) ([]OwnershipTransfer, error) {
	rows, err := q.db.Query(ctx, exportOwnershipTransfers, orgID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []OwnershipTransfer{}
	for rows.Next() {
		var i OwnershipTransfer
		if err := rows.Scan(
			&i.OrgID,
			&i.ID,
			&i.FromMembershipID,
			&i.ToMembershipID,
			&i.ExpiresAt,
			&i.AcceptedAt,
			&i.CancelledAt,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.LastModifiedBy,
			&i.LastModifiedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const exportPermissionConfigs = `-- name: ExportPermissionConfigs :many

SELECT org_id, admin_permissions, billing_admin_permissions, created_by, created_at, last_modified_by, last_modified_at FROM permission_configs WHERE org_id = $1
`

// An org's data, for its export and its purge (UO-183), and a person's
// ownership transfers, for their own export (UO-184).
func (q *Queries) ExportPermissionConfigs(ctx context.Context, orgID uuid.UUID) ([]PermissionConfig, error) {
	rows, err := q.db.Query(ctx, exportPermissionConfigs, orgID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PermissionConfig{}
	for rows.Next() {
		var i PermissionConfig
		if err := rows.Scan(
			&i.OrgID,
			&i.AdminPermissions,
			&i.BillingAdminPermissions,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.LastModifiedBy,
			&i.LastModifiedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const ownershipTransfersOfMembership = `-- name: OwnershipTransfersOfMembership :many
SELECT org_id, id, from_membership_id, to_membership_id, expires_at, accepted_at, cancelled_at, created_by, created_at, last_modified_by, last_modified_at FROM ownership_transfers
WHERE org_id = $1 AND (from_membership_id = $2 OR to_membership_id = $2)
ORDER BY created_at, id
`

type OwnershipTransfersOfMembershipParams struct {
	OrgID        uuid.UUID
	MembershipID uuid.UUID
}

// The transfers one membership started or was offered.
func (q *Queries) OwnershipTransfersOfMembership(ctx context.Context, arg OwnershipTransfersOfMembershipParams) ([]OwnershipTransfer, error) {
	rows, err := q.db.Query(ctx, ownershipTransfersOfMembership, arg.OrgID, arg.MembershipID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []OwnershipTransfer{}
	for rows.Next() {
		var i OwnershipTransfer
		if err := rows.Scan(
			&i.OrgID,
			&i.ID,
			&i.FromMembershipID,
			&i.ToMembershipID,
			&i.ExpiresAt,
			&i.AcceptedAt,
			&i.CancelledAt,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.LastModifiedBy,
			&i.LastModifiedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const purgeOwnershipTransfers = `-- name: PurgeOwnershipTransfers :execrows
DELETE FROM ownership_transfers WHERE org_id = $1
`

func (q *Queries) PurgeOwnershipTransfers(ctx context.Context, orgID uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, purgeOwnershipTransfers, orgID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const purgePermissionConfigs = `-- name: PurgePermissionConfigs :execrows
DELETE FROM permission_configs WHERE org_id = $1
`

func (q *Queries) PurgePermissionConfigs(ctx context.Context, orgID uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, purgePermissionConfigs, orgID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
