// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: email_outbox.sql

package store

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const claimDueEmails = `-- name: ClaimDueEmails :many
UPDATE email_outbox
SET state = 'sending'
WHERE (org_id, id) IN (
    SELECT org_id, id FROM email_outbox
    WHERE state = 'queued' AND next_attempt_at <= now()
    ORDER BY next_attempt_at
    LIMIT $1
    FOR UPDATE SKIP LOCKED
)
RETURNING org_id, id, to_address, subject, html_body, text_body, attempts, unsubscribe_url
`

type ClaimDueEmailsRow struct {
	OrgID          uuid.UUID
	ID             uuid.UUID
	ToAddress      string
	Subject        string
	HtmlBody       string
	TextBody       string
	Attempts       int32
	UnsubscribeUrl pgtype.Text
}

// global: the sender loop delivers every org's queued mail, oldest due first.
// Rows are locked and marked sending, so two loops (two nodes) never send twice.
func (q *Queries) ClaimDueEmails(ctx context.Context, limit int32) ([]ClaimDueEmailsRow, error) {
	rows, err := q.db.Query(ctx, claimDueEmails, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ClaimDueEmailsRow{}
	for rows.Next() {
		var i ClaimDueEmailsRow
		if err := rows.Scan(
			&i.OrgID,
			&i.ID,
			&i.ToAddress,
			&i.Subject,
			&i.HtmlBody,
			&i.TextBody,
			&i.Attempts,
			&i.UnsubscribeUrl,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getEmail = `-- name: GetEmail :one
SELECT org_id, id, template, state, attempts, next_attempt_at, sent_at, last_error
FROM email_outbox
WHERE org_id = $1 AND id = $2
`

type GetEmailParams struct {
	OrgID uuid.UUID
	ID    uuid.UUID
}

type GetEmailRow struct {
	OrgID         uuid.UUID
	ID            uuid.UUID
	Template      string
	State         string
	Attempts      int32
	NextAttemptAt time.Time
	SentAt        pgtype.Timestamptz
	LastError     pgtype.Text
}

func (q *Queries) GetEmail(ctx context.Context, arg GetEmailParams) (GetEmailRow, error) {
	row := q.db.QueryRow(ctx, getEmail, arg.OrgID, arg.ID)
	var i GetEmailRow
	err := row.Scan(
		&i.OrgID,
		&i.ID,
		&i.Template,
		&i.State,
		&i.Attempts,
		&i.NextAttemptAt,
		&i.SentAt,
		&i.LastError,
	)
	return i, err
}

const isSuppressed = `-- name: IsSuppressed :one
SELECT EXISTS (SELECT 1 FROM email_suppressions WHERE address = lower($1::text))
`

// global: a dead address is dead for every org.
func (q *Queries) IsSuppressed(ctx context.Context, address string) (bool, error) {
	row := q.db.QueryRow(ctx, isSuppressed, address)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const markEmailBouncedByProviderId = `-- name: MarkEmailBouncedByProviderId :many
UPDATE email_outbox
SET state = 'bounced', last_error = $2
WHERE provider_message_id = $1 AND state = 'sent'
RETURNING org_id, id
`

type MarkEmailBouncedByProviderIdParams struct {
	ProviderMessageID pgtype.Text
	LastError         pgtype.Text
}

type MarkEmailBouncedByProviderIdRow struct {
	OrgID uuid.UUID
	ID    uuid.UUID
}

// global: a bounce event names the provider's message id, not our org.
func (q *Queries) MarkEmailBouncedByProviderId(ctx context.Context, arg MarkEmailBouncedByProviderIdParams) ([]MarkEmailBouncedByProviderIdRow, error) {
	rows, err := q.db.Query(ctx, markEmailBouncedByProviderId, arg.ProviderMessageID, arg.LastError)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []MarkEmailBouncedByProviderIdRow{}
	for rows.Next() {
		var i MarkEmailBouncedByProviderIdRow
		if err := rows.Scan(&i.OrgID, &i.ID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markEmailFailed = `-- name: MarkEmailFailed :exec
UPDATE email_outbox
SET state = $3, attempts = attempts + 1, last_error = $4
WHERE org_id = $1 AND id = $2
`

type MarkEmailFailedParams struct {
	OrgID     uuid.UUID
	ID        uuid.UUID
	State     string
	LastError pgtype.Text
}

func (q *Queries) MarkEmailFailed(ctx context.Context, arg MarkEmailFailedParams) error {
	_, err := q.db.Exec(ctx, markEmailFailed,
		arg.OrgID,
		arg.ID,
		arg.State,
		arg.LastError,
	)
	return err
}

const markEmailRetry = `-- name: MarkEmailRetry :exec
UPDATE email_outbox
SET state = 'queued', attempts = attempts + 1, next_attempt_at = $3, last_error = $4
WHERE org_id = $1 AND id = $2
`

type MarkEmailRetryParams struct {
	OrgID         uuid.UUID
	ID            uuid.UUID
	NextAttemptAt time.Time
	LastError     pgtype.Text
}

func (q *Queries) MarkEmailRetry(ctx context.Context, arg MarkEmailRetryParams) error {
	_, err := q.db.Exec(ctx, markEmailRetry,
		arg.OrgID,
		arg.ID,
		arg.NextAttemptAt,
		arg.LastError,
	)
	return err
}

const markEmailSent = `-- name: MarkEmailSent :exec
UPDATE email_outbox
SET state = 'sent', attempts = attempts + 1, provider_message_id = $3, sent_at = now(), last_error = NULL
WHERE org_id = $1 AND id = $2
`

type MarkEmailSentParams struct {
	OrgID             uuid.UUID
	ID                uuid.UUID
	ProviderMessageID pgtype.Text
}

func (q *Queries) MarkEmailSent(ctx context.Context, arg MarkEmailSentParams) error {
	_, err := q.db.Exec(ctx, markEmailSent, arg.OrgID, arg.ID, arg.ProviderMessageID)
	return err
}

const queueEmail = `-- name: QueueEmail :one
INSERT INTO email_outbox (org_id, id, to_address, template, subject, html_body, text_body, state, next_attempt_at, unsubscribe_url)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10)
RETURNING org_id, id, template, state, attempts, next_attempt_at, sent_at, last_error
`

type QueueEmailParams struct {
	OrgID          uuid.UUID
	ID             uuid.UUID
	ToAddress      string
	Template       string
	Subject        string
	HtmlBody       string
	TextBody       string
	State          string
	NextAttemptAt  time.Time
	UnsubscribeUrl pgtype.Text
}

type QueueEmailRow struct {
	OrgID         uuid.UUID
	ID            uuid.UUID
	Template      string
	State         string
	Attempts      int32
	NextAttemptAt time.Time
	SentAt        pgtype.Timestamptz
	LastError     pgtype.Text
}

func (q *Queries) QueueEmail(ctx context.Context, arg QueueEmailParams) (QueueEmailRow, error) {
	row := q.db.QueryRow(ctx, queueEmail,
		arg.OrgID,
		arg.ID,
		arg.ToAddress,
		arg.Template,
		arg.Subject,
		arg.HtmlBody,
		arg.TextBody,
		arg.State,
		arg.NextAttemptAt,
		arg.UnsubscribeUrl,
	)
	var i QueueEmailRow
	err := row.Scan(
		&i.OrgID,
		&i.ID,
		&i.Template,
		&i.State,
		&i.Attempts,
		&i.NextAttemptAt,
		&i.SentAt,
		&i.LastError,
	)
	return i, err
}

const suppress = `-- name: Suppress :exec
INSERT INTO email_suppressions (id, address, reason, provider_event_id)
VALUES ($1, lower($2::text), $3, $4)
ON CONFLICT (address) DO NOTHING
`

type SuppressParams struct {
	ID              uuid.UUID
	Address         string
	Reason          string
	ProviderEventID pgtype.Text
}

// global: a dead address is dead for every org.
func (q *Queries) Suppress(ctx context.Context, arg SuppressParams) error {
	_, err := q.db.Exec(ctx, suppress,
		arg.ID,
		arg.Address,
		arg.Reason,
		arg.ProviderEventID,
	)
	return err
}
