//go:build go1.22

// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.8.0 DO NOT EDIT.
package api

import (
	"bytes"
	"context"
	"encoding/json"
	"errors"
	"fmt"
	"io"
	"net/http"
	"time"

	"github.com/oapi-codegen/runtime"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

// Defines values for DeliveryStatus.
const (
	Failed    DeliveryStatus = "failed"
	Pending   DeliveryStatus = "pending"
	Succeeded DeliveryStatus = "succeeded"
)

// Valid indicates whether the value is a known member of the DeliveryStatus enum.
func (e DeliveryStatus) Valid() bool {
	switch e {
	case Failed:
		return true
	case Pending:
		return true
	case Succeeded:
		return true
	default:
		return false
	}
}

// Attempt defines model for Attempt.
type Attempt struct {
	AttemptedAt time.Time          `json:"attempted_at"`
	Error       *string            `json:"error,omitempty"`
	Id          openapi_types.UUID `json:"id"`
	LatencyMs   int                `json:"latency_ms"`

	// Manual Sent by an admin (a resend or a test).
	Manual     bool `json:"manual"`
	StatusCode *int `json:"status_code,omitempty"`
}

// DataPart defines model for DataPart.
type DataPart struct {
	Data  map[string]interface{} `json:"data"`
	Files []struct {
		Key  string `json:"key"`
		Name string `json:"name"`
	} `json:"files"`
	Service string `json:"service"`
}

// DataPurged defines model for DataPurged.
type DataPurged struct {
	Remaining int `json:"remaining"`
}

// Delivery defines model for Delivery.
type Delivery struct {
	Attempts      int                `json:"attempts"`
	CreatedAt     time.Time          `json:"created_at"`
	EndpointId    openapi_types.UUID `json:"endpoint_id"`
	EventType     string             `json:"event_type"`
	Id            openapi_types.UUID `json:"id"`
	LastAttemptAt *time.Time         `json:"last_attempt_at,omitempty"`
	LastError     *string            `json:"last_error,omitempty"`
	LastLatencyMs *int               `json:"last_latency_ms,omitempty"`

	// LastStatusCode The endpoint's HTTP status on the last attempt; absent when it could not be reached.
	LastStatusCode *int `json:"last_status_code,omitempty"`

	// MessageId The webhook-id header, the same on every attempt.
	MessageId openapi_types.UUID `json:"message_id"`

	// NextAttemptAt When a pending delivery is tried again.
	NextAttemptAt *time.Time `json:"next_attempt_at,omitempty"`

	// Status pending until an attempt succeeds; failed once it has been tried six times, or its endpoint is turned off.
	Status DeliveryStatus `json:"status"`
}

// DeliveryDetail defines model for DeliveryDetail.
type DeliveryDetail struct {
	// AttemptLog Every attempt, oldest first.
	AttemptLog    []Attempt          `json:"attempt_log"`
	Attempts      int                `json:"attempts"`
	CreatedAt     time.Time          `json:"created_at"`
	EndpointId    openapi_types.UUID `json:"endpoint_id"`
	EventType     string             `json:"event_type"`
	Id            openapi_types.UUID `json:"id"`
	LastAttemptAt *time.Time         `json:"last_attempt_at,omitempty"`
	LastError     *string            `json:"last_error,omitempty"`
	LastLatencyMs *int               `json:"last_latency_ms,omitempty"`

	// LastStatusCode The endpoint's HTTP status on the last attempt; absent when it could not be reached.
	LastStatusCode *int `json:"last_status_code,omitempty"`

	// MessageId The webhook-id header, the same on every attempt.
	MessageId openapi_types.UUID `json:"message_id"`

	// NextAttemptAt When a pending delivery is tried again.
	NextAttemptAt *time.Time `json:"next_attempt_at,omitempty"`

	// Payload The body every attempt sends.
	Payload map[string]interface{} `json:"payload"`

	// Status pending until an attempt succeeds; failed once it has been tried six times, or its endpoint is turned off.
	Status DeliveryStatus `json:"status"`
}

// DeliveryPage defines model for DeliveryPage.
type DeliveryPage struct {
	Deliveries []Delivery `json:"deliveries"`

	// NextCursor Present when there is another page.
	NextCursor *string `json:"next_cursor,omitempty"`
}

// DeliveryStatus pending until an attempt succeeds; failed once it has been tried six times, or its endpoint is turned off.
type DeliveryStatus string

// Endpoint defines model for Endpoint.
type Endpoint struct {
	CreatedAt   time.Time `json:"created_at"`
	Description string    `json:"description"`
	Enabled     bool      `json:"enabled"`

	// EventTypes The types it receives; empty is every type.
	EventTypes     []string           `json:"event_types"`
	Id             openapi_types.UUID `json:"id"`
	LastModifiedAt time.Time          `json:"last_modified_at"`
	OrgId          openapi_types.UUID `json:"org_id"`

	// PreviousSecretExpiresAt While a rotation overlaps, when the old secret stops signing.
	PreviousSecretExpiresAt *time.Time `json:"previous_secret_expires_at,omitempty"`

	// SecretRotatedAt When its secret was last rotated, if ever.
	SecretRotatedAt *time.Time `json:"secret_rotated_at,omitempty"`
	Url             string     `json:"url"`
}

// EndpointUpdate defines model for EndpointUpdate.
type EndpointUpdate struct {
	Description *string   `json:"description,omitempty"`
	Enabled     *bool     `json:"enabled,omitempty"`
	EventTypes  *[]string `json:"event_types,omitempty"`
	Url         *string   `json:"url,omitempty"`
}

// EndpointWithSecret defines model for EndpointWithSecret.
type EndpointWithSecret struct {
	Endpoint Endpoint `json:"endpoint"`

	// Secret The signing secret, whsec_ and base64. Shown this once; it cannot be read again.
	Secret string `json:"secret"`
}

// Error defines model for Error.
type Error struct {
	Code    string             `json:"code"`
	Fields  *map[string]string `json:"fields,omitempty"`
	Message string             `json:"message"`
}

// EventAccepted defines model for EventAccepted.
type EventAccepted struct {
	// Deliveries How many endpoints it is being delivered to.
	Deliveries int                `json:"deliveries"`
	Id         openapi_types.UUID `json:"id"`
}

// EventType defines model for EventType.
type EventType struct {
	Description string `json:"description"`

	// Type Example: member.added
	Type string `json:"type"`
}

// EventTypeList defines model for EventTypeList.
type EventTypeList struct {
	// Available Whether the org's plan has webhooks now. When false, endpoints cannot be added and nothing is delivered.
	Available  bool        `json:"available"`
	EventTypes []EventType `json:"event_types"`

	// RequiredPlan The lowest plan with webhooks, when the org's has none.
	RequiredPlan *string `json:"required_plan,omitempty"`
}

// NewEndpoint defines model for NewEndpoint.
type NewEndpoint struct {
	Description *string `json:"description,omitempty"`
	Enabled     *bool   `json:"enabled,omitempty"`

	// EventTypes Registered types only; empty or left out is every type.
	EventTypes *[]string `json:"event_types,omitempty"`

	// Url https, on a public address.
	Url string `json:"url"`
}

// NewEvent defines model for NewEvent.
type NewEvent struct {
	// Data Ids and values only, never a name or an email. At most 16 KB.
	Data map[string]interface{} `json:"data"`

	// Id Makes the send idempotent; the same id twice is one event.
	Id         *openapi_types.UUID `json:"id,omitempty"`
	OccurredAt *time.Time          `json:"occurred_at,omitempty"`

	// Type Example: project.created
	Type string `json:"type"`
}

// DeliveryId defines model for DeliveryId.
type DeliveryId = openapi_types.UUID

// EndpointId defines model for EndpointId.
type EndpointId = openapi_types.UUID

// OrgId defines model for OrgId.
type OrgId = openapi_types.UUID

// ExportUserDataParams defines parameters for ExportUserData.
type ExportUserDataParams struct {
	// Membership Each of the person's memberships, as org_id:membership_id.
	Membership *[]string `form:"membership,omitempty" json:"membership,omitempty"`
}

// ListWebhookDeliveriesParams defines parameters for ListWebhookDeliveries.
type ListWebhookDeliveriesParams struct {
	// EndpointId Only this endpoint's.
	EndpointId *openapi_types.UUID `form:"endpoint_id,omitempty" json:"endpoint_id,omitempty"`
	Status     *DeliveryStatus     `form:"status,omitempty" json:"status,omitempty"`

	// Cursor From the previous page's next_cursor. Omit for the first page.
	Cursor *string `form:"cursor,omitempty" json:"cursor,omitempty"`
	Limit  *int    `form:"limit,omitempty" json:"limit,omitempty"`
}

// RotateWebhookSecretJSONBody defines parameters for RotateWebhookSecret.
type RotateWebhookSecretJSONBody struct {
	// OverlapHours How long the old secret keeps signing. 0 ends it now.
	OverlapHours *int `json:"overlap_hours,omitempty"`
}

// EmitWebhookEventJSONRequestBody defines body for EmitWebhookEvent for application/json ContentType.
type EmitWebhookEventJSONRequestBody = NewEvent

// CreateWebhookEndpointJSONRequestBody defines body for CreateWebhookEndpoint for application/json ContentType.
type CreateWebhookEndpointJSONRequestBody = NewEndpoint

// UpdateWebhookEndpointJSONRequestBody defines body for UpdateWebhookEndpoint for application/json ContentType.
type UpdateWebhookEndpointJSONRequestBody = EndpointUpdate

// RotateWebhookSecretJSONRequestBody defines body for RotateWebhookSecret for application/json ContentType.
type RotateWebhookSecretJSONRequestBody RotateWebhookSecretJSONBody

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// PurgeOrgData Delete everything this service keeps for an org, and count what is left (the organization service only)
	// (DELETE /v1/internal/organizations/{org_id}/data)
	PurgeOrgData(w http.ResponseWriter, r *http.Request, orgId OrgId)
	// ExportOrgData Everything this service keeps for an org, for its export (the organization service only)
	// (GET /v1/internal/organizations/{org_id}/data)
	ExportOrgData(w http.ResponseWriter, r *http.Request, orgId OrgId)
	// EmitWebhookEvent Send an event to the org's endpoints that subscribe to it (services only)
	// (POST /v1/internal/organizations/{org_id}/events)
	EmitWebhookEvent(w http.ResponseWriter, r *http.Request, orgId OrgId)
	// ExportUserData What this service keeps about one person, for their own export (the organization service only)
	// (GET /v1/internal/users/{user_id}/data)
	ExportUserData(w http.ResponseWriter, r *http.Request, userId openapi_types.UUID, params ExportUserDataParams)
	// ListWebhookDeliveries The org's deliveries, newest first
	// (GET /v1/organizations/{org_id}/webhook-deliveries)
	ListWebhookDeliveries(w http.ResponseWriter, r *http.Request, orgId OrgId, params ListWebhookDeliveriesParams)
	// GetWebhookDelivery One delivery, with the body sent and every attempt
	// (GET /v1/organizations/{org_id}/webhook-deliveries/{delivery_id})
	GetWebhookDelivery(w http.ResponseWriter, r *http.Request, orgId OrgId, deliveryId DeliveryId)
	// ResendWebhookDelivery Attempt a delivery again now, whatever its status, and answer with how it went
	// (POST /v1/organizations/{org_id}/webhook-deliveries/{delivery_id}/resend)
	ResendWebhookDelivery(w http.ResponseWriter, r *http.Request, orgId OrgId, deliveryId DeliveryId)
	// ListWebhookEndpoints The org's endpoints, oldest first
	// (GET /v1/organizations/{org_id}/webhook-endpoints)
	ListWebhookEndpoints(w http.ResponseWriter, r *http.Request, orgId OrgId)
	// CreateWebhookEndpoint Add an endpoint; its signing secret is in the answer, and only there
	// (POST /v1/organizations/{org_id}/webhook-endpoints)
	CreateWebhookEndpoint(w http.ResponseWriter, r *http.Request, orgId OrgId)
	// DeleteWebhookEndpoint Remove an endpoint and its deliveries
	// (DELETE /v1/organizations/{org_id}/webhook-endpoints/{endpoint_id})
	DeleteWebhookEndpoint(w http.ResponseWriter, r *http.Request, orgId OrgId, endpointId EndpointId)
	// GetWebhookEndpoint One endpoint
	// (GET /v1/organizations/{org_id}/webhook-endpoints/{endpoint_id})
	GetWebhookEndpoint(w http.ResponseWriter, r *http.Request, orgId OrgId, endpointId EndpointId)
	// UpdateWebhookEndpoint Change an endpoint's URL, description, event types, or turn it on or off
	// (PATCH /v1/organizations/{org_id}/webhook-endpoints/{endpoint_id})
	UpdateWebhookEndpoint(w http.ResponseWriter, r *http.Request, orgId OrgId, endpointId EndpointId)
	// RotateWebhookSecret Replace an endpoint's signing secret; the new one is in the answer, and only there
	// (POST /v1/organizations/{org_id}/webhook-endpoints/{endpoint_id}/rotate-secret)
	RotateWebhookSecret(w http.ResponseWriter, r *http.Request, orgId OrgId, endpointId EndpointId)
	// SendWebhookTest Send a webhook.test event to this endpoint now, and answer with how it went
	// (POST /v1/organizations/{org_id}/webhook-endpoints/{endpoint_id}/test)
	SendWebhookTest(w http.ResponseWriter, r *http.Request, orgId OrgId, endpointId EndpointId)
	// ListWebhookEventTypes The event types an endpoint may subscribe to, and whether the org's plan has webhooks
	// (GET /v1/organizations/{org_id}/webhook-event-types)
	ListWebhookEventTypes(w http.ResponseWriter, r *http.Request, orgId OrgId)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// PurgeOrgData operation middleware
func (siw *ServerInterfaceWrapper) PurgeOrgData(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "org_id" -------------
	var orgId OrgId

	err = runtime.BindStyledParameterWithOptions("simple", "org_id", r.PathValue("org_id"), &orgId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "org_id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PurgeOrgData(w, r, orgId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ExportOrgData operation middleware
func (siw *ServerInterfaceWrapper) ExportOrgData(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "org_id" -------------
	var orgId OrgId

	err = runtime.BindStyledParameterWithOptions("simple", "org_id", r.PathValue("org_id"), &orgId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "org_id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ExportOrgData(w, r, orgId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// EmitWebhookEvent operation middleware
func (siw *ServerInterfaceWrapper) EmitWebhookEvent(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "org_id" -------------
	var orgId OrgId

	err = runtime.BindStyledParameterWithOptions("simple", "org_id", r.PathValue("org_id"), &orgId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "org_id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.EmitWebhookEvent(w, r, orgId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ExportUserData operation middleware
func (siw *ServerInterfaceWrapper) ExportUserData(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "user_id" -------------
	var userId openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "user_id", r.PathValue("user_id"), &userId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "user_id", Err: err})
		return
	}

	// Parameter object where we will unmarshal all parameters from the context
	var params ExportUserDataParams

	// ------------- Optional query parameter "membership" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "membership", r.URL.Query(), &params.Membership, runtime.BindQueryParameterOptions{Type: "array", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "membership"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "membership", Err: err})
		}
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ExportUserData(w, r, userId, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListWebhookDeliveries operation middleware
func (siw *ServerInterfaceWrapper) ListWebhookDeliveries(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "org_id" -------------
	var orgId OrgId

	err = runtime.BindStyledParameterWithOptions("simple", "org_id", r.PathValue("org_id"), &orgId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "org_id", Err: err})
		return
	}

	// Parameter object where we will unmarshal all parameters from the context
	var params ListWebhookDeliveriesParams

	// ------------- Optional query parameter "endpoint_id" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "endpoint_id", r.URL.Query(), &params.EndpointId, runtime.BindQueryParameterOptions{Type: "string", Format: "uuid"})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "endpoint_id"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "endpoint_id", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "status" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "status", r.URL.Query(), &params.Status, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "status"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "status", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "cursor" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "cursor", r.URL.Query(), &params.Cursor, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "cursor"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "cursor", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "limit" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "limit", r.URL.Query(), &params.Limit, runtime.BindQueryParameterOptions{Type: "integer", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "limit"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "limit", Err: err})
		}
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListWebhookDeliveries(w, r, orgId, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetWebhookDelivery operation middleware
func (siw *ServerInterfaceWrapper) GetWebhookDelivery(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "org_id" -------------
	var orgId OrgId

	err = runtime.BindStyledParameterWithOptions("simple", "org_id", r.PathValue("org_id"), &orgId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "org_id", Err: err})
		return
	}

	// ------------- Path parameter "delivery_id" -------------
	var deliveryId DeliveryId

	err = runtime.BindStyledParameterWithOptions("simple", "delivery_id", r.PathValue("delivery_id"), &deliveryId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "delivery_id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetWebhookDelivery(w, r, orgId, deliveryId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ResendWebhookDelivery operation middleware
func (siw *ServerInterfaceWrapper) ResendWebhookDelivery(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "org_id" -------------
	var orgId OrgId

	err = runtime.BindStyledParameterWithOptions("simple", "org_id", r.PathValue("org_id"), &orgId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "org_id", Err: err})
		return
	}

	// ------------- Path parameter "delivery_id" -------------
	var deliveryId DeliveryId

	err = runtime.BindStyledParameterWithOptions("simple", "delivery_id", r.PathValue("delivery_id"), &deliveryId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "delivery_id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ResendWebhookDelivery(w, r, orgId, deliveryId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListWebhookEndpoints operation middleware
func (siw *ServerInterfaceWrapper) ListWebhookEndpoints(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "org_id" -------------
	var orgId OrgId

	err = runtime.BindStyledParameterWithOptions("simple", "org_id", r.PathValue("org_id"), &orgId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "org_id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListWebhookEndpoints(w, r, orgId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// CreateWebhookEndpoint operation middleware
func (siw *ServerInterfaceWrapper) CreateWebhookEndpoint(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "org_id" -------------
	var orgId OrgId

	err = runtime.BindStyledParameterWithOptions("simple", "org_id", r.PathValue("org_id"), &orgId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "org_id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CreateWebhookEndpoint(w, r, orgId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// DeleteWebhookEndpoint operation middleware
func (siw *ServerInterfaceWrapper) DeleteWebhookEndpoint(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "org_id" -------------
	var orgId OrgId

	err = runtime.BindStyledParameterWithOptions("simple", "org_id", r.PathValue("org_id"), &orgId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "org_id", Err: err})
		return
	}

	// ------------- Path parameter "endpoint_id" -------------
	var endpointId EndpointId

	err = runtime.BindStyledParameterWithOptions("simple", "endpoint_id", r.PathValue("endpoint_id"), &endpointId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "endpoint_id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.DeleteWebhookEndpoint(w, r, orgId, endpointId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetWebhookEndpoint operation middleware
func (siw *ServerInterfaceWrapper) GetWebhookEndpoint(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "org_id" -------------
	var orgId OrgId

	err = runtime.BindStyledParameterWithOptions("simple", "org_id", r.PathValue("org_id"), &orgId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "org_id", Err: err})
		return
	}

	// ------------- Path parameter "endpoint_id" -------------
	var endpointId EndpointId

	err = runtime.BindStyledParameterWithOptions("simple", "endpoint_id", r.PathValue("endpoint_id"), &endpointId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "endpoint_id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetWebhookEndpoint(w, r, orgId, endpointId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// UpdateWebhookEndpoint operation middleware
func (siw *ServerInterfaceWrapper) UpdateWebhookEndpoint(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "org_id" -------------
	var orgId OrgId

	err = runtime.BindStyledParameterWithOptions("simple", "org_id", r.PathValue("org_id"), &orgId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "org_id", Err: err})
		return
	}

	// ------------- Path parameter "endpoint_id" -------------
	var endpointId EndpointId

	err = runtime.BindStyledParameterWithOptions("simple", "endpoint_id", r.PathValue("endpoint_id"), &endpointId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "endpoint_id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.UpdateWebhookEndpoint(w, r, orgId, endpointId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// RotateWebhookSecret operation middleware
func (siw *ServerInterfaceWrapper) RotateWebhookSecret(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "org_id" -------------
	var orgId OrgId

	err = runtime.BindStyledParameterWithOptions("simple", "org_id", r.PathValue("org_id"), &orgId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "org_id", Err: err})
		return
	}

	// ------------- Path parameter "endpoint_id" -------------
	var endpointId EndpointId

	err = runtime.BindStyledParameterWithOptions("simple", "endpoint_id", r.PathValue("endpoint_id"), &endpointId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "endpoint_id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.RotateWebhookSecret(w, r, orgId, endpointId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// SendWebhookTest operation middleware
func (siw *ServerInterfaceWrapper) SendWebhookTest(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "org_id" -------------
	var orgId OrgId

	err = runtime.BindStyledParameterWithOptions("simple", "org_id", r.PathValue("org_id"), &orgId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "org_id", Err: err})
		return
	}

	// ------------- Path parameter "endpoint_id" -------------
	var endpointId EndpointId

	err = runtime.BindStyledParameterWithOptions("simple", "endpoint_id", r.PathValue("endpoint_id"), &endpointId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "endpoint_id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.SendWebhookTest(w, r, orgId, endpointId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListWebhookEventTypes operation middleware
func (siw *ServerInterfaceWrapper) ListWebhookEventTypes(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "org_id" -------------
	var orgId OrgId

	err = runtime.BindStyledParameterWithOptions("simple", "org_id", r.PathValue("org_id"), &orgId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "org_id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListWebhookEventTypes(w, r, orgId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{})
}

// ServeMux is an abstraction of [http.ServeMux].
type ServeMux interface {
	HandleFunc(pattern string, handler func(http.ResponseWriter, *http.Request))
	http.Handler
}

type StdHTTPServerOptions struct {
	BaseURL          string
	BaseRouter       ServeMux
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, m ServeMux) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{
		BaseRouter: m,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, m ServeMux, baseURL string) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{
		BaseURL:    baseURL,
		BaseRouter: m,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options StdHTTPServerOptions) http.Handler {
	m := options.BaseRouter

	if m == nil {
		m = http.NewServeMux()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}

	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/v1/organizations/{org_id}/webhook-event-types", wrapper.ListWebhookEventTypes)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/v1/organizations/{org_id}/webhook-endpoints", wrapper.ListWebhookEndpoints)
	m.HandleFunc(http.MethodPost+" "+options.BaseURL+"/v1/organizations/{org_id}/webhook-endpoints", wrapper.CreateWebhookEndpoint)
	m.HandleFunc(http.MethodDelete+" "+options.BaseURL+"/v1/organizations/{org_id}/webhook-endpoints/{endpoint_id}", wrapper.DeleteWebhookEndpoint)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/v1/organizations/{org_id}/webhook-endpoints/{endpoint_id}", wrapper.GetWebhookEndpoint)
	m.HandleFunc(http.MethodPatch+" "+options.BaseURL+"/v1/organizations/{org_id}/webhook-endpoints/{endpoint_id}", wrapper.UpdateWebhookEndpoint)
	m.HandleFunc(http.MethodPost+" "+options.BaseURL+"/v1/organizations/{org_id}/webhook-endpoints/{endpoint_id}/rotate-secret", wrapper.RotateWebhookSecret)
	m.HandleFunc(http.MethodPost+" "+options.BaseURL+"/v1/organizations/{org_id}/webhook-endpoints/{endpoint_id}/test", wrapper.SendWebhookTest)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/v1/organizations/{org_id}/webhook-deliveries", wrapper.ListWebhookDeliveries)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/v1/organizations/{org_id}/webhook-deliveries/{delivery_id}", wrapper.GetWebhookDelivery)
	m.HandleFunc(http.MethodPost+" "+options.BaseURL+"/v1/organizations/{org_id}/webhook-deliveries/{delivery_id}/resend", wrapper.ResendWebhookDelivery)
	m.HandleFunc(http.MethodPost+" "+options.BaseURL+"/v1/internal/organizations/{org_id}/events", wrapper.EmitWebhookEvent)
	m.HandleFunc(http.MethodDelete+" "+options.BaseURL+"/v1/internal/organizations/{org_id}/data", wrapper.PurgeOrgData)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/v1/internal/organizations/{org_id}/data", wrapper.ExportOrgData)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/v1/internal/users/{user_id}/data", wrapper.ExportUserData)

	return m
}

type ErrorJSONResponse Error

type PurgeOrgDataRequestObject struct {
	OrgId OrgId `json:"org_id"`
}

type PurgeOrgDataResponseObject interface {
	VisitPurgeOrgDataResponse(w http.ResponseWriter) error
}

type PurgeOrgData200JSONResponse DataPurged

func (response PurgeOrgData200JSONResponse) VisitPurgeOrgDataResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type PurgeOrgData403JSONResponse struct{ ErrorJSONResponse }

func (response PurgeOrgData403JSONResponse) VisitPurgeOrgDataResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(403)
	_, err := buf.WriteTo(w)
	return err
}

type PurgeOrgDatadefaultJSONResponse struct {
	Body       Error
	StatusCode int
}

func (response PurgeOrgDatadefaultJSONResponse) VisitPurgeOrgDataResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(response.StatusCode)
	_, err := buf.WriteTo(w)
	return err
}

type ExportOrgDataRequestObject struct {
	OrgId OrgId `json:"org_id"`
}

type ExportOrgDataResponseObject interface {
	VisitExportOrgDataResponse(w http.ResponseWriter) error
}

type ExportOrgData200JSONResponse DataPart

func (response ExportOrgData200JSONResponse) VisitExportOrgDataResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type ExportOrgData403JSONResponse struct{ ErrorJSONResponse }

func (response ExportOrgData403JSONResponse) VisitExportOrgDataResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(403)
	_, err := buf.WriteTo(w)
	return err
}

type ExportOrgDatadefaultJSONResponse struct {
	Body       Error
	StatusCode int
}

func (response ExportOrgDatadefaultJSONResponse) VisitExportOrgDataResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(response.StatusCode)
	_, err := buf.WriteTo(w)
	return err
}

type EmitWebhookEventRequestObject struct {
	OrgId OrgId `json:"org_id"`
	Body  *EmitWebhookEventJSONRequestBody
}

type EmitWebhookEventResponseObject interface {
	VisitEmitWebhookEventResponse(w http.ResponseWriter) error
}

type EmitWebhookEvent202JSONResponse EventAccepted

func (response EmitWebhookEvent202JSONResponse) VisitEmitWebhookEventResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(202)
	_, err := buf.WriteTo(w)
	return err
}

type EmitWebhookEvent400JSONResponse struct{ ErrorJSONResponse }

func (response EmitWebhookEvent400JSONResponse) VisitEmitWebhookEventResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)
	_, err := buf.WriteTo(w)
	return err
}

type EmitWebhookEvent401JSONResponse Error

func (response EmitWebhookEvent401JSONResponse) VisitEmitWebhookEventResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type EmitWebhookEvent403JSONResponse Error

func (response EmitWebhookEvent403JSONResponse) VisitEmitWebhookEventResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(403)
	_, err := buf.WriteTo(w)
	return err
}

type EmitWebhookEvent429JSONResponse Error

func (response EmitWebhookEvent429JSONResponse) VisitEmitWebhookEventResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(429)
	_, err := buf.WriteTo(w)
	return err
}

type EmitWebhookEventdefaultJSONResponse struct {
	Body       Error
	StatusCode int
}

func (response EmitWebhookEventdefaultJSONResponse) VisitEmitWebhookEventResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(response.StatusCode)
	_, err := buf.WriteTo(w)
	return err
}

type ExportUserDataRequestObject struct {
	UserId openapi_types.UUID `json:"user_id"`
	Params ExportUserDataParams
}

type ExportUserDataResponseObject interface {
	VisitExportUserDataResponse(w http.ResponseWriter) error
}

type ExportUserData200JSONResponse DataPart

func (response ExportUserData200JSONResponse) VisitExportUserDataResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type ExportUserData403JSONResponse struct{ ErrorJSONResponse }

func (response ExportUserData403JSONResponse) VisitExportUserDataResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(403)
	_, err := buf.WriteTo(w)
	return err
}

type ExportUserDatadefaultJSONResponse struct {
	Body       Error
	StatusCode int
}

func (response ExportUserDatadefaultJSONResponse) VisitExportUserDataResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(response.StatusCode)
	_, err := buf.WriteTo(w)
	return err
}

type ListWebhookDeliveriesRequestObject struct {
	OrgId  OrgId `json:"org_id"`
	Params ListWebhookDeliveriesParams
}

type ListWebhookDeliveriesResponseObject interface {
	VisitListWebhookDeliveriesResponse(w http.ResponseWriter) error
}

type ListWebhookDeliveries200JSONResponse DeliveryPage

func (response ListWebhookDeliveries200JSONResponse) VisitListWebhookDeliveriesResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type ListWebhookDeliveries400JSONResponse struct{ ErrorJSONResponse }

func (response ListWebhookDeliveries400JSONResponse) VisitListWebhookDeliveriesResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)
	_, err := buf.WriteTo(w)
	return err
}

type ListWebhookDeliveries401JSONResponse Error

func (response ListWebhookDeliveries401JSONResponse) VisitListWebhookDeliveriesResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type ListWebhookDeliveries403JSONResponse Error

func (response ListWebhookDeliveries403JSONResponse) VisitListWebhookDeliveriesResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(403)
	_, err := buf.WriteTo(w)
	return err
}

type ListWebhookDeliveriesdefaultJSONResponse struct {
	Body       Error
	StatusCode int
}

func (response ListWebhookDeliveriesdefaultJSONResponse) VisitListWebhookDeliveriesResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(response.StatusCode)
	_, err := buf.WriteTo(w)
	return err
}

type GetWebhookDeliveryRequestObject struct {
	OrgId      OrgId      `json:"org_id"`
	DeliveryId DeliveryId `json:"delivery_id"`
}

type GetWebhookDeliveryResponseObject interface {
	VisitGetWebhookDeliveryResponse(w http.ResponseWriter) error
}

type GetWebhookDelivery200JSONResponse DeliveryDetail

func (response GetWebhookDelivery200JSONResponse) VisitGetWebhookDeliveryResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type GetWebhookDelivery401JSONResponse struct{ ErrorJSONResponse }

func (response GetWebhookDelivery401JSONResponse) VisitGetWebhookDeliveryResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type GetWebhookDelivery403JSONResponse Error

func (response GetWebhookDelivery403JSONResponse) VisitGetWebhookDeliveryResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(403)
	_, err := buf.WriteTo(w)
	return err
}

type GetWebhookDelivery404JSONResponse Error

func (response GetWebhookDelivery404JSONResponse) VisitGetWebhookDeliveryResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)
	_, err := buf.WriteTo(w)
	return err
}

type GetWebhookDeliverydefaultJSONResponse struct {
	Body       Error
	StatusCode int
}

func (response GetWebhookDeliverydefaultJSONResponse) VisitGetWebhookDeliveryResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(response.StatusCode)
	_, err := buf.WriteTo(w)
	return err
}

type ResendWebhookDeliveryRequestObject struct {
	OrgId      OrgId      `json:"org_id"`
	DeliveryId DeliveryId `json:"delivery_id"`
}

type ResendWebhookDeliveryResponseObject interface {
	VisitResendWebhookDeliveryResponse(w http.ResponseWriter) error
}

type ResendWebhookDelivery200JSONResponse DeliveryDetail

func (response ResendWebhookDelivery200JSONResponse) VisitResendWebhookDeliveryResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type ResendWebhookDelivery401JSONResponse struct{ ErrorJSONResponse }

func (response ResendWebhookDelivery401JSONResponse) VisitResendWebhookDeliveryResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type ResendWebhookDelivery403JSONResponse Error

func (response ResendWebhookDelivery403JSONResponse) VisitResendWebhookDeliveryResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(403)
	_, err := buf.WriteTo(w)
	return err
}

type ResendWebhookDelivery404JSONResponse Error

func (response ResendWebhookDelivery404JSONResponse) VisitResendWebhookDeliveryResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)
	_, err := buf.WriteTo(w)
	return err
}

type ResendWebhookDeliverydefaultJSONResponse struct {
	Body       Error
	StatusCode int
}

func (response ResendWebhookDeliverydefaultJSONResponse) VisitResendWebhookDeliveryResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(response.StatusCode)
	_, err := buf.WriteTo(w)
	return err
}

type ListWebhookEndpointsRequestObject struct {
	OrgId OrgId `json:"org_id"`
}

type ListWebhookEndpointsResponseObject interface {
	VisitListWebhookEndpointsResponse(w http.ResponseWriter) error
}

type ListWebhookEndpoints200JSONResponse struct {
	Endpoints []Endpoint `json:"endpoints"`
}

func (response ListWebhookEndpoints200JSONResponse) VisitListWebhookEndpointsResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type ListWebhookEndpoints401JSONResponse struct{ ErrorJSONResponse }

func (response ListWebhookEndpoints401JSONResponse) VisitListWebhookEndpointsResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type ListWebhookEndpoints403JSONResponse Error

func (response ListWebhookEndpoints403JSONResponse) VisitListWebhookEndpointsResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(403)
	_, err := buf.WriteTo(w)
	return err
}

type ListWebhookEndpointsdefaultJSONResponse struct {
	Body       Error
	StatusCode int
}

func (response ListWebhookEndpointsdefaultJSONResponse) VisitListWebhookEndpointsResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(response.StatusCode)
	_, err := buf.WriteTo(w)
	return err
}

type CreateWebhookEndpointRequestObject struct {
	OrgId OrgId `json:"org_id"`
	Body  *CreateWebhookEndpointJSONRequestBody
}

type CreateWebhookEndpointResponseObject interface {
	VisitCreateWebhookEndpointResponse(w http.ResponseWriter) error
}

type CreateWebhookEndpoint201JSONResponse EndpointWithSecret

func (response CreateWebhookEndpoint201JSONResponse) VisitCreateWebhookEndpointResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(201)
	_, err := buf.WriteTo(w)
	return err
}

type CreateWebhookEndpoint400JSONResponse struct{ ErrorJSONResponse }

func (response CreateWebhookEndpoint400JSONResponse) VisitCreateWebhookEndpointResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)
	_, err := buf.WriteTo(w)
	return err
}

type CreateWebhookEndpoint401JSONResponse Error

func (response CreateWebhookEndpoint401JSONResponse) VisitCreateWebhookEndpointResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type CreateWebhookEndpoint403JSONResponse Error

func (response CreateWebhookEndpoint403JSONResponse) VisitCreateWebhookEndpointResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(403)
	_, err := buf.WriteTo(w)
	return err
}

type CreateWebhookEndpoint409JSONResponse Error

func (response CreateWebhookEndpoint409JSONResponse) VisitCreateWebhookEndpointResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(409)
	_, err := buf.WriteTo(w)
	return err
}

type CreateWebhookEndpointdefaultJSONResponse struct {
	Body       Error
	StatusCode int
}

func (response CreateWebhookEndpointdefaultJSONResponse) VisitCreateWebhookEndpointResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(response.StatusCode)
	_, err := buf.WriteTo(w)
	return err
}

type DeleteWebhookEndpointRequestObject struct {
	OrgId      OrgId      `json:"org_id"`
	EndpointId EndpointId `json:"endpoint_id"`
}

type DeleteWebhookEndpointResponseObject interface {
	VisitDeleteWebhookEndpointResponse(w http.ResponseWriter) error
}

type DeleteWebhookEndpoint204Response struct {
}

func (response DeleteWebhookEndpoint204Response) VisitDeleteWebhookEndpointResponse(w http.ResponseWriter) error {
	w.WriteHeader(204)
	return nil
}

type DeleteWebhookEndpoint401JSONResponse struct{ ErrorJSONResponse }

func (response DeleteWebhookEndpoint401JSONResponse) VisitDeleteWebhookEndpointResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type DeleteWebhookEndpoint403JSONResponse Error

func (response DeleteWebhookEndpoint403JSONResponse) VisitDeleteWebhookEndpointResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(403)
	_, err := buf.WriteTo(w)
	return err
}

type DeleteWebhookEndpoint404JSONResponse Error

func (response DeleteWebhookEndpoint404JSONResponse) VisitDeleteWebhookEndpointResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)
	_, err := buf.WriteTo(w)
	return err
}

type DeleteWebhookEndpointdefaultJSONResponse struct {
	Body       Error
	StatusCode int
}

func (response DeleteWebhookEndpointdefaultJSONResponse) VisitDeleteWebhookEndpointResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(response.StatusCode)
	_, err := buf.WriteTo(w)
	return err
}

type GetWebhookEndpointRequestObject struct {
	OrgId      OrgId      `json:"org_id"`
	EndpointId EndpointId `json:"endpoint_id"`
}

type GetWebhookEndpointResponseObject interface {
	VisitGetWebhookEndpointResponse(w http.ResponseWriter) error
}

type GetWebhookEndpoint200JSONResponse Endpoint

func (response GetWebhookEndpoint200JSONResponse) VisitGetWebhookEndpointResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type GetWebhookEndpoint401JSONResponse struct{ ErrorJSONResponse }

func (response GetWebhookEndpoint401JSONResponse) VisitGetWebhookEndpointResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type GetWebhookEndpoint403JSONResponse Error

func (response GetWebhookEndpoint403JSONResponse) VisitGetWebhookEndpointResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(403)
	_, err := buf.WriteTo(w)
	return err
}

type GetWebhookEndpoint404JSONResponse Error

func (response GetWebhookEndpoint404JSONResponse) VisitGetWebhookEndpointResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)
	_, err := buf.WriteTo(w)
	return err
}

type GetWebhookEndpointdefaultJSONResponse struct {
	Body       Error
	StatusCode int
}

func (response GetWebhookEndpointdefaultJSONResponse) VisitGetWebhookEndpointResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(response.StatusCode)
	_, err := buf.WriteTo(w)
	return err
}

type UpdateWebhookEndpointRequestObject struct {
	OrgId      OrgId      `json:"org_id"`
	EndpointId EndpointId `json:"endpoint_id"`
	Body       *UpdateWebhookEndpointJSONRequestBody
}

type UpdateWebhookEndpointResponseObject interface {
	VisitUpdateWebhookEndpointResponse(w http.ResponseWriter) error
}

type UpdateWebhookEndpoint200JSONResponse Endpoint

func (response UpdateWebhookEndpoint200JSONResponse) VisitUpdateWebhookEndpointResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type UpdateWebhookEndpoint400JSONResponse struct{ ErrorJSONResponse }

func (response UpdateWebhookEndpoint400JSONResponse) VisitUpdateWebhookEndpointResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)
	_, err := buf.WriteTo(w)
	return err
}

type UpdateWebhookEndpoint401JSONResponse Error

func (response UpdateWebhookEndpoint401JSONResponse) VisitUpdateWebhookEndpointResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type UpdateWebhookEndpoint403JSONResponse Error

func (response UpdateWebhookEndpoint403JSONResponse) VisitUpdateWebhookEndpointResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(403)
	_, err := buf.WriteTo(w)
	return err
}

type UpdateWebhookEndpoint404JSONResponse Error

func (response UpdateWebhookEndpoint404JSONResponse) VisitUpdateWebhookEndpointResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)
	_, err := buf.WriteTo(w)
	return err
}

type UpdateWebhookEndpointdefaultJSONResponse struct {
	Body       Error
	StatusCode int
}

func (response UpdateWebhookEndpointdefaultJSONResponse) VisitUpdateWebhookEndpointResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(response.StatusCode)
	_, err := buf.WriteTo(w)
	return err
}

type RotateWebhookSecretRequestObject struct {
	OrgId      OrgId      `json:"org_id"`
	EndpointId EndpointId `json:"endpoint_id"`
	Body       *RotateWebhookSecretJSONRequestBody
}

type RotateWebhookSecretResponseObject interface {
	VisitRotateWebhookSecretResponse(w http.ResponseWriter) error
}

type RotateWebhookSecret200JSONResponse EndpointWithSecret

func (response RotateWebhookSecret200JSONResponse) VisitRotateWebhookSecretResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type RotateWebhookSecret400JSONResponse struct{ ErrorJSONResponse }

func (response RotateWebhookSecret400JSONResponse) VisitRotateWebhookSecretResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)
	_, err := buf.WriteTo(w)
	return err
}

type RotateWebhookSecret401JSONResponse Error

func (response RotateWebhookSecret401JSONResponse) VisitRotateWebhookSecretResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type RotateWebhookSecret403JSONResponse Error

func (response RotateWebhookSecret403JSONResponse) VisitRotateWebhookSecretResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(403)
	_, err := buf.WriteTo(w)
	return err
}

type RotateWebhookSecret404JSONResponse Error

func (response RotateWebhookSecret404JSONResponse) VisitRotateWebhookSecretResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)
	_, err := buf.WriteTo(w)
	return err
}

type RotateWebhookSecretdefaultJSONResponse struct {
	Body       Error
	StatusCode int
}

func (response RotateWebhookSecretdefaultJSONResponse) VisitRotateWebhookSecretResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(response.StatusCode)
	_, err := buf.WriteTo(w)
	return err
}

type SendWebhookTestRequestObject struct {
	OrgId      OrgId      `json:"org_id"`
	EndpointId EndpointId `json:"endpoint_id"`
}

type SendWebhookTestResponseObject interface {
	VisitSendWebhookTestResponse(w http.ResponseWriter) error
}

type SendWebhookTest200JSONResponse DeliveryDetail

func (response SendWebhookTest200JSONResponse) VisitSendWebhookTestResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type SendWebhookTest401JSONResponse struct{ ErrorJSONResponse }

func (response SendWebhookTest401JSONResponse) VisitSendWebhookTestResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type SendWebhookTest403JSONResponse Error

func (response SendWebhookTest403JSONResponse) VisitSendWebhookTestResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(403)
	_, err := buf.WriteTo(w)
	return err
}

type SendWebhookTest404JSONResponse Error

func (response SendWebhookTest404JSONResponse) VisitSendWebhookTestResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)
	_, err := buf.WriteTo(w)
	return err
}

type SendWebhookTestdefaultJSONResponse struct {
	Body       Error
	StatusCode int
}

func (response SendWebhookTestdefaultJSONResponse) VisitSendWebhookTestResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(response.StatusCode)
	_, err := buf.WriteTo(w)
	return err
}

type ListWebhookEventTypesRequestObject struct {
	OrgId OrgId `json:"org_id"`
}

type ListWebhookEventTypesResponseObject interface {
	VisitListWebhookEventTypesResponse(w http.ResponseWriter) error
}

type ListWebhookEventTypes200JSONResponse EventTypeList

func (response ListWebhookEventTypes200JSONResponse) VisitListWebhookEventTypesResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type ListWebhookEventTypes401JSONResponse struct{ ErrorJSONResponse }

func (response ListWebhookEventTypes401JSONResponse) VisitListWebhookEventTypesResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type ListWebhookEventTypes403JSONResponse Error

func (response ListWebhookEventTypes403JSONResponse) VisitListWebhookEventTypesResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(403)
	_, err := buf.WriteTo(w)
	return err
}

type ListWebhookEventTypesdefaultJSONResponse struct {
	Body       Error
	StatusCode int
}

func (response ListWebhookEventTypesdefaultJSONResponse) VisitListWebhookEventTypesResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(response.StatusCode)
	_, err := buf.WriteTo(w)
	return err
}

// StrictServerInterface represents all server handlers.
type StrictServerInterface interface {
	// PurgeOrgData Delete everything this service keeps for an org, and count what is left (the organization service only)
	// (DELETE /v1/internal/organizations/{org_id}/data)
	PurgeOrgData(ctx context.Context, request PurgeOrgDataRequestObject) (PurgeOrgDataResponseObject, error)
	// ExportOrgData Everything this service keeps for an org, for its export (the organization service only)
	// (GET /v1/internal/organizations/{org_id}/data)
	ExportOrgData(ctx context.Context, request ExportOrgDataRequestObject) (ExportOrgDataResponseObject, error)
	// EmitWebhookEvent Send an event to the org's endpoints that subscribe to it (services only)
	// (POST /v1/internal/organizations/{org_id}/events)
	EmitWebhookEvent(ctx context.Context, request EmitWebhookEventRequestObject) (EmitWebhookEventResponseObject, error)
	// ExportUserData What this service keeps about one person, for their own export (the organization service only)
	// (GET /v1/internal/users/{user_id}/data)
	ExportUserData(ctx context.Context, request ExportUserDataRequestObject) (ExportUserDataResponseObject, error)
	// ListWebhookDeliveries The org's deliveries, newest first
	// (GET /v1/organizations/{org_id}/webhook-deliveries)
	ListWebhookDeliveries(ctx context.Context, request ListWebhookDeliveriesRequestObject) (ListWebhookDeliveriesResponseObject, error)
	// GetWebhookDelivery One delivery, with the body sent and every attempt
	// (GET /v1/organizations/{org_id}/webhook-deliveries/{delivery_id})
	GetWebhookDelivery(ctx context.Context, request GetWebhookDeliveryRequestObject) (GetWebhookDeliveryResponseObject, error)
	// ResendWebhookDelivery Attempt a delivery again now, whatever its status, and answer with how it went
	// (POST /v1/organizations/{org_id}/webhook-deliveries/{delivery_id}/resend)
	ResendWebhookDelivery(ctx context.Context, request ResendWebhookDeliveryRequestObject) (ResendWebhookDeliveryResponseObject, error)
	// ListWebhookEndpoints The org's endpoints, oldest first
	// (GET /v1/organizations/{org_id}/webhook-endpoints)
	ListWebhookEndpoints(ctx context.Context, request ListWebhookEndpointsRequestObject) (ListWebhookEndpointsResponseObject, error)
	// CreateWebhookEndpoint Add an endpoint; its signing secret is in the answer, and only there
	// (POST /v1/organizations/{org_id}/webhook-endpoints)
	CreateWebhookEndpoint(ctx context.Context, request CreateWebhookEndpointRequestObject) (CreateWebhookEndpointResponseObject, error)
	// DeleteWebhookEndpoint Remove an endpoint and its deliveries
	// (DELETE /v1/organizations/{org_id}/webhook-endpoints/{endpoint_id})
	DeleteWebhookEndpoint(ctx context.Context, request DeleteWebhookEndpointRequestObject) (DeleteWebhookEndpointResponseObject, error)
	// GetWebhookEndpoint One endpoint
	// (GET /v1/organizations/{org_id}/webhook-endpoints/{endpoint_id})
	GetWebhookEndpoint(ctx context.Context, request GetWebhookEndpointRequestObject) (GetWebhookEndpointResponseObject, error)
	// UpdateWebhookEndpoint Change an endpoint's URL, description, event types, or turn it on or off
	// (PATCH /v1/organizations/{org_id}/webhook-endpoints/{endpoint_id})
	UpdateWebhookEndpoint(ctx context.Context, request UpdateWebhookEndpointRequestObject) (UpdateWebhookEndpointResponseObject, error)
	// RotateWebhookSecret Replace an endpoint's signing secret; the new one is in the answer, and only there
	// (POST /v1/organizations/{org_id}/webhook-endpoints/{endpoint_id}/rotate-secret)
	RotateWebhookSecret(ctx context.Context, request RotateWebhookSecretRequestObject) (RotateWebhookSecretResponseObject, error)
	// SendWebhookTest Send a webhook.test event to this endpoint now, and answer with how it went
	// (POST /v1/organizations/{org_id}/webhook-endpoints/{endpoint_id}/test)
	SendWebhookTest(ctx context.Context, request SendWebhookTestRequestObject) (SendWebhookTestResponseObject, error)
	// ListWebhookEventTypes The event types an endpoint may subscribe to, and whether the org's plan has webhooks
	// (GET /v1/organizations/{org_id}/webhook-event-types)
	ListWebhookEventTypes(ctx context.Context, request ListWebhookEventTypesRequestObject) (ListWebhookEventTypesResponseObject, error)
}

type StrictHandlerFunc func(ctx context.Context, w http.ResponseWriter, r *http.Request, request any) (any, error)
type StrictMiddlewareFunc func(f StrictHandlerFunc, operationID string) StrictHandlerFunc

type StrictHTTPServerOptions struct {
	RequestErrorHandlerFunc  func(w http.ResponseWriter, r *http.Request, err error)
	ResponseErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

func NewStrictHandler(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: StrictHTTPServerOptions{
		RequestErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		},
		ResponseErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusInternalServerError)
		},
	}}
}

func NewStrictHandlerWithOptions(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc, options StrictHTTPServerOptions) ServerInterface {
	if options.RequestErrorHandlerFunc == nil {
		options.RequestErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}
	if options.ResponseErrorHandlerFunc == nil {
		options.ResponseErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusInternalServerError)
		}
	}
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: options}
}

type strictHandler struct {
	ssi         StrictServerInterface
	middlewares []StrictMiddlewareFunc
	options     StrictHTTPServerOptions
}

// PurgeOrgData operation middleware
func (sh *strictHandler) PurgeOrgData(w http.ResponseWriter, r *http.Request, orgId OrgId) {
	var request PurgeOrgDataRequestObject

	request.OrgId = orgId

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.PurgeOrgData(ctx, request.(PurgeOrgDataRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "PurgeOrgData")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(PurgeOrgDataResponseObject); ok {
		if err := validResponse.VisitPurgeOrgDataResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// ExportOrgData operation middleware
func (sh *strictHandler) ExportOrgData(w http.ResponseWriter, r *http.Request, orgId OrgId) {
	var request ExportOrgDataRequestObject

	request.OrgId = orgId

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.ExportOrgData(ctx, request.(ExportOrgDataRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "ExportOrgData")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(ExportOrgDataResponseObject); ok {
		if err := validResponse.VisitExportOrgDataResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// EmitWebhookEvent operation middleware
func (sh *strictHandler) EmitWebhookEvent(w http.ResponseWriter, r *http.Request, orgId OrgId) {
	var request EmitWebhookEventRequestObject

	request.OrgId = orgId

	var body EmitWebhookEventJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.EmitWebhookEvent(ctx, request.(EmitWebhookEventRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "EmitWebhookEvent")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(EmitWebhookEventResponseObject); ok {
		if err := validResponse.VisitEmitWebhookEventResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// ExportUserData operation middleware
func (sh *strictHandler) ExportUserData(w http.ResponseWriter, r *http.Request, userId openapi_types.UUID, params ExportUserDataParams) {
	var request ExportUserDataRequestObject

	request.UserId = userId
	request.Params = params

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.ExportUserData(ctx, request.(ExportUserDataRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "ExportUserData")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(ExportUserDataResponseObject); ok {
		if err := validResponse.VisitExportUserDataResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// ListWebhookDeliveries operation middleware
func (sh *strictHandler) ListWebhookDeliveries(w http.ResponseWriter, r *http.Request, orgId OrgId, params ListWebhookDeliveriesParams) {
	var request ListWebhookDeliveriesRequestObject

	request.OrgId = orgId
	request.Params = params

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.ListWebhookDeliveries(ctx, request.(ListWebhookDeliveriesRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "ListWebhookDeliveries")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(ListWebhookDeliveriesResponseObject); ok {
		if err := validResponse.VisitListWebhookDeliveriesResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetWebhookDelivery operation middleware
func (sh *strictHandler) GetWebhookDelivery(w http.ResponseWriter, r *http.Request, orgId OrgId, deliveryId DeliveryId) {
	var request GetWebhookDeliveryRequestObject

	request.OrgId = orgId
	request.DeliveryId = deliveryId

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetWebhookDelivery(ctx, request.(GetWebhookDeliveryRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetWebhookDelivery")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetWebhookDeliveryResponseObject); ok {
		if err := validResponse.VisitGetWebhookDeliveryResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// ResendWebhookDelivery operation middleware
func (sh *strictHandler) ResendWebhookDelivery(w http.ResponseWriter, r *http.Request, orgId OrgId, deliveryId DeliveryId) {
	var request ResendWebhookDeliveryRequestObject

	request.OrgId = orgId
	request.DeliveryId = deliveryId

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.ResendWebhookDelivery(ctx, request.(ResendWebhookDeliveryRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "ResendWebhookDelivery")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(ResendWebhookDeliveryResponseObject); ok {
		if err := validResponse.VisitResendWebhookDeliveryResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// ListWebhookEndpoints operation middleware
func (sh *strictHandler) ListWebhookEndpoints(w http.ResponseWriter, r *http.Request, orgId OrgId) {
	var request ListWebhookEndpointsRequestObject

	request.OrgId = orgId

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.ListWebhookEndpoints(ctx, request.(ListWebhookEndpointsRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "ListWebhookEndpoints")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(ListWebhookEndpointsResponseObject); ok {
		if err := validResponse.VisitListWebhookEndpointsResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// CreateWebhookEndpoint operation middleware
func (sh *strictHandler) CreateWebhookEndpoint(w http.ResponseWriter, r *http.Request, orgId OrgId) {
	var request CreateWebhookEndpointRequestObject

	request.OrgId = orgId

	var body CreateWebhookEndpointJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.CreateWebhookEndpoint(ctx, request.(CreateWebhookEndpointRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "CreateWebhookEndpoint")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(CreateWebhookEndpointResponseObject); ok {
		if err := validResponse.VisitCreateWebhookEndpointResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// DeleteWebhookEndpoint operation middleware
func (sh *strictHandler) DeleteWebhookEndpoint(w http.ResponseWriter, r *http.Request, orgId OrgId, endpointId EndpointId) {
	var request DeleteWebhookEndpointRequestObject

	request.OrgId = orgId
	request.EndpointId = endpointId

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.DeleteWebhookEndpoint(ctx, request.(DeleteWebhookEndpointRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "DeleteWebhookEndpoint")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(DeleteWebhookEndpointResponseObject); ok {
		if err := validResponse.VisitDeleteWebhookEndpointResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetWebhookEndpoint operation middleware
func (sh *strictHandler) GetWebhookEndpoint(w http.ResponseWriter, r *http.Request, orgId OrgId, endpointId EndpointId) {
	var request GetWebhookEndpointRequestObject

	request.OrgId = orgId
	request.EndpointId = endpointId

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetWebhookEndpoint(ctx, request.(GetWebhookEndpointRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetWebhookEndpoint")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetWebhookEndpointResponseObject); ok {
		if err := validResponse.VisitGetWebhookEndpointResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// UpdateWebhookEndpoint operation middleware
func (sh *strictHandler) UpdateWebhookEndpoint(w http.ResponseWriter, r *http.Request, orgId OrgId, endpointId EndpointId) {
	var request UpdateWebhookEndpointRequestObject

	request.OrgId = orgId
	request.EndpointId = endpointId

	var body UpdateWebhookEndpointJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.UpdateWebhookEndpoint(ctx, request.(UpdateWebhookEndpointRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "UpdateWebhookEndpoint")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(UpdateWebhookEndpointResponseObject); ok {
		if err := validResponse.VisitUpdateWebhookEndpointResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// RotateWebhookSecret operation middleware
func (sh *strictHandler) RotateWebhookSecret(w http.ResponseWriter, r *http.Request, orgId OrgId, endpointId EndpointId) {
	var request RotateWebhookSecretRequestObject

	request.OrgId = orgId
	request.EndpointId = endpointId

	var body RotateWebhookSecretJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		if !errors.Is(err, io.EOF) {
			sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
			return
		}
	} else {
		request.Body = &body
	}

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.RotateWebhookSecret(ctx, request.(RotateWebhookSecretRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "RotateWebhookSecret")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(RotateWebhookSecretResponseObject); ok {
		if err := validResponse.VisitRotateWebhookSecretResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// SendWebhookTest operation middleware
func (sh *strictHandler) SendWebhookTest(w http.ResponseWriter, r *http.Request, orgId OrgId, endpointId EndpointId) {
	var request SendWebhookTestRequestObject

	request.OrgId = orgId
	request.EndpointId = endpointId

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.SendWebhookTest(ctx, request.(SendWebhookTestRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "SendWebhookTest")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(SendWebhookTestResponseObject); ok {
		if err := validResponse.VisitSendWebhookTestResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// ListWebhookEventTypes operation middleware
func (sh *strictHandler) ListWebhookEventTypes(w http.ResponseWriter, r *http.Request, orgId OrgId) {
	var request ListWebhookEventTypesRequestObject

	request.OrgId = orgId

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.ListWebhookEventTypes(ctx, request.(ListWebhookEventTypesRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "ListWebhookEventTypes")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(ListWebhookEventTypesResponseObject); ok {
		if err := validResponse.VisitListWebhookEventTypesResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}
